### ISSUE TITLE
Order completed timecards by date: most recent first

### ISSUE THREAD

**Issue by jenniferthibault** [18F/tock#100]
Can't see any logic in the current list order:
![screen shot 2015-05-04 at 11 47 42 am](https://cloud.githubusercontent.com/assets/11636908/7456581/83088f0e-f253-11e4-9171-5b75553abe7f.png)

In some cases, when filling out a current timesheet, it would be helpful to be able to compare/reference my most recent timesheet to see what categories I used.  Suggested order:

Reporting Periods You've Filed a Timecard for:
* Last week
* Two weeks ago
* Three weeks ago
* etc

**Comment by konklone** [comment]
:+1: Just saw this myself, came to file an issue, noted it was already filed. Agree on showing the most recent up top, since these will pile up over time.

**Comment by seanherron** [comment]
This has now been fixed! I also limited this to the previous five reporting periods so it doesn't get too cray cray.
