### ISSUE TITLE
add dependency for soupsieve 2

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1003]
details: https://pypi.org/project/soupsieve/
upcoming requirement by beautifulsoup4 4.8.2

**Comment by tbaxter-18f** [comment]
This was covered in #1007, right?

**Comment by tbaxter-18f** [comment]
Given that I think this was covered in #1007, I'm closing. If I'm wrong, please reopen.

**Comment by cryptofilegsa** [comment]
this is correct.  soupsieve==2.0
current from late Feb. 
https://pypi.org/project/soupsieve/#history
