### ISSUE TITLE
investigate accuracy of the "is 18F employee" and "is 18F billable" data

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1005]
Two binary fields are tracked:
  "is 18F employee"
  "is 18F billable employee"
Tracked but accuracy of the data is not 100% known
Affects utilization reports.

**Comment by tbaxter-18f** [comment]
This probably duplicates #873

**Comment by tbaxter-18f** [comment]
I'm going to close this in favor of 873. If you feel that one doesn't capture something, please add it!
