### ISSUE TITLE
Update python dependencies

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1007]
Let's update our python dependencies to their latest versions where possible.

We've documented the process [here](https://github.com/18F/tock/blob/master/docs/dependency-management.md).

_Originally posted by @Jkrzy in https://github.com/18F/tock/issues/947#issuecomment-608536816_

**Comment by Jkrzy** [comment]
@cryptofilegsa can you tackle this as your next priority, would be great to get into the next release.

**Comment by cryptofilegsa** [comment]
from pipfile and lock I get these versions:

  **default**
beautifulsoup4             version ==4.8.2
bleach             version ==3.1.4
certifi             version ==2019.11.28
cfenv             version ==0.5.3        cg-django-uaa             version ==2.0.0
chardet             version ==3.0.4
dj-database-url             version ==0.5.0
django           version ==2.2.10
django-webtest             version ==1.9.7
djangorestframework             version ==3.11.0
djangorestframework-csv             version ==2.1.0
furl             version ==2.1.0
 gevent             version ==1.4.0
greenlet             version ==0.4.15
gunicorn             version ==20.0.4
idna             version ==2.9
markdown             version ==3.1.1
newrelic             version ==5.6.0.135
orderedmultidict             version ==1.0.1
psycopg2-binary             version ==2.8.4
pyjwt             version ==1.7.1
pytz             version ==2019.3
requests            version ==2.23.0
six             version ==1.14.0
soupsieve             version ==2.0
sqlparse             version ==0.3.1
unicodecsv             version ==0.14.1
urllib3             version ==1.25.8
waitress           version ==1.4.3
webencodings             version ==0.5.1
webob             version ==1.8.6
webtest             version ==2.0.34
whitenoise             version ==5.0.1


    **develop** 
asgiref             version ==3.2.7
bandit             version ==1.6.2
beautifulsoup4             version ==4.8.2
blinker             version ==1.4
certifi             version ==2019.11.28
chardet             version ==3.0.4
codecov             version ==2.0.15
coverage             version ==5.0.3
django             version ==2.2.10        
django-debug-toolbar             version ==2.2        
django-webtest             version ==1.9.7        
entrypoints             version ==0.3        
factory-boy             version ==2.12.0        
faker             version ==4.0.2        
flake8             version ==3.7.9        
gitdb             version ==4.0.2        
gitpython             version ==3.1.0        
idna             version ==2.9        
mccabe             version ==0.6.1        
nplusone             version ==1.0.0        
pbr             version ==5.4.4        
pycodestyle             version ==2.5.0        
pyflakes             version ==2.1.1        
python-dateutil             version ==2.8.1        
pytz             version ==2019.3        
pyyaml             version ==5.3.1        
requests             version ==2.23.0        
six             version ==1.14.0        
smmap             version ==3.0.1        
soupsieve             version ==2.0        
sqlparse             version ==0.3.1        
stevedore             version ==1.32.0        
text-unidecode             version ==1.3        
urllib3             version ==1.25.8        
waitress             version ==1.4.3        
webob             version ==1.8.6
webtest           version ==2.0.34

**Comment by cryptofilegsa** [comment]
following the process mentioned above inside a docker that has been updated for dev:

>
pipenv lock --requirements > requirements.txt
root@9a44566fbaf7:/tock# cat requirements.txt 
-i https://pypi.python.org/simple
beautifulsoup4==4.9.0
bleach==3.1.4
certifi==2020.4.5.1
cfenv==0.5.3
cg-django-uaa==2.0.0
chardet==3.0.4
dj-database-url==0.5.0
django-webtest==1.9.7
django==2.2.12
djangorestframework-csv==2.1.0
djangorestframework==3.11.0
furl==2.1.0
gevent==1.4.0
greenlet==0.4.15 ; platform_python_implementation == 'CPython'
gunicorn==20.0.4
idna==2.9
markdown==3.2.1
newrelic==5.10.0.138
orderedmultidict==1.0.1
psycopg2-binary==2.8.5
pyjwt==1.7.1
pytz==2019.3
requests==2.23.0
six==1.14.0
soupsieve==2.0
sqlparse==0.3.1
unicodecsv==0.14.1
urllib3==1.25.8
waitress==1.4.3
webencodings==0.5.1
webob==1.8.6
webtest==2.0.34
whitenoise==5.0.1

**Comment by cryptofilegsa** [comment]
see commit: https://github.com/18F/tock/commit/665952a4d2b19f1761bc05147bc2c4425d0e6d6b

**Comment by Jkrzy** [comment]
Thanks @cryptofilegsa, we'll need an updated `Pipfile.lock` to match. Propose those changes with a pull request against `master` please

**Comment by cryptofilegsa** [comment]
was unclear about the "treat file as binary" so I put this here: https://github.com/18F/tock/pull/1012
