### ISSUE TITLE
add administrative guidance such as how to add users

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1008]
add written guidance on administrative functions that can be added to the [tock documentation here in github](https://github.com/18F/tock/tree/master/docs).

Attached here is a draft:
[Tock Administrative Functions Documentation.docx](https://github.com/18F/tock/files/4440327/Tock.Administrative.Functions.Documentation.docx)

**Comment by kfoley-18F** [comment]
I think this should be written as a markdown file - *.md using the Github markdown annotations. 
Can you please move out of .docx and into .md for folks to review in GH? 

Thanks!

**Comment by cryptofilegsa** [comment]
resolved with documentation submitted, ready for review here: https://github.com/18F/tock/pull/1011
