### ISSUE TITLE
Make "organization" a required field

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1024]
With us sorting and filtering and reporting utilization on it, we need this data available for each user in Tock.

## We'll know we're done when
- [x] The `organization` field on the `UserData` model has been updated to be a required field for form validation
- [x] Migrations have been generated to update the database
- [x] `UserDataAdmin` has been updated so that `organization` is sortable
- [x] `UserDataAdmin` has been updated allowing filtering for instances with no values for `organization`

**Comment by tbaxter-18f** [comment]
@cryptofilegsa can you give an update on how this is coming? Are there blockers?

**Comment by cryptofilegsa** [comment]
can sensible data mean "18F" is default?

**Comment by tbaxter-18f** [comment]
I don't see a problem with that.

**Comment by cryptofilegsa** [comment]
change at https://github.com/18F/tock/commit/777a73fca228f7e6c6524c03c4d9c3a67a6830bb , more may be needed once I give migrate.py a shot.

**Comment by cryptofilegsa** [comment]
OK, I have the change made locally that works, the migration has been produced, running the migration works locally and puts the database in a state that is operational and I've tested the fix.  However, I don't think this will work on CircleCI or with testing on other devices without changes to the default data set.

**Comment by Jkrzy** [comment]
Updated original issue `We'll know we're done when` from convo in :slack:

**Comment by cryptofilegsa** [comment]
@tbaxter-18f changes here are ongoing discussion in #tock-dev.   @Jkrzy question re: github etiquette: given **all** of the criterion (definition of done) have changed here, can we open a new issue to track the new work?  happy to change focus to new issue as you suggest.  Where possible would like to avoid anything that could be intentionally confusing to anyone following the trail of thought in our work.

**Comment by tbaxter-18f** [comment]
If we were to create a new issue it would duplicate this one and require cross-linking the two, so I'm not seeing an advantage in doing so. The issue we're solving is unchanged, only our approach to solving it.

**Comment by cryptofilegsa** [comment]
for the new approach with four steps from June 3, late yesterday, tutorials pointed out to me were inadequate but I found needed documentation in the #modeladmin-options section of the django documents here: https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#modeladmin-options
