### ISSUE TITLE
Utilization should respect Org

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1025]
Currently the utilization charts https://tock.18f.gov/utilization/ do not filter or sort by Org, so they jump from 18F to PIFs to TTS ops.

If we need to show utilization for other parts of TTS, then we should sort/filter by org. We also need clear headings so we can see which Org a BU belongs to.

If we do not need to show utilization for other parts of TTS, then we should make the page truly 18F-only.

**Comment by tbaxter-18f** [comment]
@abrouilette do you have any background knowledge on whether or not other parts of TTS are using Tock as a utilization reporting tool?

**Comment by martyspence** [comment]
CoE tracks utilization so they may want to see this as well. Was going to ping David Warren here but not sure if he's got an account, sending him a link.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
