### ISSUE TITLE
Use preferred, friendly name

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1027]
currently names are your legal name, in a john.doe format. It'd be nice if we accounted for preferred names.

It's possible we may just be able to modify the username for the preferred output, maybe splitting on the ., or it may require a new field.

**Comment by tbaxter-18f** [comment]
I noticed today we already capture firstname and last name, so this is really just a display question, not a model question. 

I think we should start by scoping it simply to the utilization reports, since that's where names are most noticeable

**Comment by Sgtpluck** [comment]
Closed with https://github.com/18F/tock/pull/1167
