### ISSUE TITLE
screenshot from 2015 outdated, replace screenshot with something current

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1029]
old:
![image](https://user-images.githubusercontent.com/22898229/79004078-9efcfc00-7b19-11ea-81fc-a3e9685a70e3.png)

proposed new:
![image](https://user-images.githubusercontent.com/22898229/79005107-cf459a00-7b1b-11ea-9453-c2a6735426b7.png)

**Comment by tbaxter-18f** [comment]
We should block this on the USWDS and some other front-end stories we have pending.
