### ISSUE TITLE
Set a ceiling for target billable hours

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1030]
The current approach calculates target hours by multiplying total hours worked and billing expectation. When a user tocks more than 40 hours in a week, their target hours may exceed 40.

There should be a maximum applied to target_hours.

## We'll know we're done when
- [ ] We've researched and defined a maximum value for `target_hours`
- [ ] We've implemented the maximum in the codebase

**Comment by tbaxter-18f** [comment]
I'm not sure I understand. Your target hours as a Supe is 16. That shouldn't change. What am I missing?

**Comment by Jkrzy** [comment]
Current calculation is:
```python
target_hours = billable_expectation * (billable_hours + non_billable_hours)
```

If someone works more than 40 hours, target hours can go to the 🌔.

e.g.
Bob's billing expectation is 80%.
On a normal week, Bob's target hours would be 32.
Last week Bob worked 65 hours, so tock calculates his target hours as 52:

```python
target_hours = billable_expectation * (billable_hours + non_billable_hours)
# 0.8 * (65.0 + 0.0)
# target_hours = 52
```

**Comment by tbaxter-18f** [comment]
I see. it seems like it's maybe related to https://github.com/18F/tock/issues/1020
 or at least having that would enable reuse as the cap.
