### ISSUE TITLE
Migrate billable expectations for past time cards

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1031]
If we correct someone's billable expectations it does not work for past time cards, only future ones. In order to have accurate historical data we will have to know, for each person:

Name
Expected hours
When that expectation began

We will then have to convert that to a data structure, and write a script to migrate the data.

We'll know we're done when:
[ x ] Correct info is collected
[ x ] Usable data structure written
[  ] Migration script written
[  ] migration script run

**Comment by tbaxter-18f** [comment]
I am collecting the data with SMT

**Comment by tbaxter-18f** [comment]
@Jkrzy I'm thinking a simple dict of dicts, with the logic we can key off name, then iterate through on the match:
```
{
firstname.lastname: {
		expectation: 12,
		since: 10/01/19
	},
	firstname.lastname: {
		expectation: 16,
		since: 01/01/20
	},
}
```
what do you think?

**Comment by tbaxter-18f** [comment]
Talked with Joe. We'll do a CSV instead

**Comment by tbaxter-18f** [comment]
Sheet for CSV: https://docs.google.com/spreadsheets/d/1QkvP3IfwuUow9PmHR1gD_FCGYQ12NngOQB3FbVsrfgs/edit#gid=0

**Comment by Jkrzy** [comment]
Tested against staging and 👍 

We'll complete this by executing the management command in #1039 w/ the latest data from the above referenced spreadsheet against production as part of the next release.

**Comment by Jkrzy** [comment]
Successfully run against production DB
