### ISSUE TITLE
alphabetize the employees listing

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1032]
Employees listed on tock.18f.gov/employees to be sorted by alphabet: lastname, firstname.

**Comment by tbaxter-18f** [comment]
Alphabetize within Org and BU. Those remain the primary keys to sort on.

**Comment by tbaxter-18f** [comment]
Probably blocked on (or could be combined with) #1027

**Comment by cryptofilegsa** [comment]
product of our pair programming today PR: 95b77b

**Comment by tbaxter-18f** [comment]
@cryptofilegsa Please focus on #1024 as assigned. This issue is not a part of our current efforts. Thanks!
