### ISSUE TITLE
Cannot access user details page of non-billable users

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1033]
Tock is attempting to display utilization data for each user on the `UserDetails` page.

When attempting to calculate this for `non-billable` users, we're encountering a `NotImplementedError` because `non-billable` users are excluded from utilization data. This exception isn't handled gracefully by the backend and results in a 500 error to the user.

We'll know we're done when:
- [ ] UserDetail view for non-billable users loads as expected

**Comment by Jkrzy** [comment]
This will be resolved by #1034

**Comment by tbaxter-18f** [comment]
Given #1034, I'm going to close this.
