### ISSUE TITLE
Current tock showing up as "No hours submitted."

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1036]
May be related to Tocks that aren't submitted on Friday, but we're seeing people who have definitely Tocked showing up as No hours submitted. in the utilization reports.

**Comment by tbaxter-18f** [comment]
Hmm. This is coming from https://github.com/18F/tock/blob/575c2ce803d1e15c316fc6311980976fb4987329/tock/utilization/utils.py#L12 and appears to be due to `calculate_utilization()` not getting hours in some usage, but I didn't dig deeper than that.

**Comment by Jkrzy** [comment]
Thanks for the pointer @tbaxter-18f!!

We're not handling `target_hours = 0` correctly, tackling now.

**Comment by Jkrzy** [comment]
How should we represent folks who exceeded their billing targets by an `undefined` amount? 😅 

```
Joe's billing expectation for a given week is 0.
Joe tocked 24 hours to a billable project.

Joe's utilization is `undefined`
```

**Comment by tbaxter-18f** [comment]
I'm still gathering opinions, but I'm thinking the best behavior is:

1. In case of undefined/non-billable, display "--" or "Non-billable" or something like that.
2. Any hours work should roll up and contribute to the BU/Org level numbers
3. Add an asterisk or something to explain what we're doing

That's what I'm thinking, anyway. Subject to change.
