### ISSUE TITLE
Onboarding for Tim Ballard

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1049]
- [x] Generate a Tock API authorization token in the admin for the new developer. 
- [x] Grant access to New Relic.
- [x] Grant access to the GitHub repository.
- [x] Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x] Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x] Grant access to gsa-18f-tock org on Snyk.
- [x] Run through log auditing at: https://github.com/18F/tock/blob/master/docs/logging.md#tock-log-auditing

**Comment by Jkrzy** [comment]
Hey @timoballard, welcome to :tock: and thanks for your help!

Feel free to get started here when able.

### New developer checklist
- [ ] Familiarize yourself with the systems and scripts your onboarding partner has granted access to
- [ ] Review the Tock deployment process
