### ISSUE TITLE
Revive Angry Tock bot

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1052]
At one time Tock would auto-post to Slack on Mondays to nudge folks who hadn't Tocked. We should do that again.

**Comment by Jkrzy** [comment]
@mgwalker is exploring the potential to enhance Charlie with similar functionality

**Comment by tbaxter-18f** [comment]
Yeah, I logged this just to help track the work, and so we could capture any API or model changes we might need. I'm still not sure how we'll match up Tock users to Slack users.

**Comment by mgwalker** [comment]
Related to #653?

**Comment by tbaxter-18f** [comment]
Yes, @mgwalker I think so. I'll close this one in favor of #653, since it was logged first.
