### ISSUE TITLE
Remove vestigial utilization views and reporting

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1056]
As a tock user I want utilization reporting to be consistent across the application so that I can be confident of the numbers being reported.

There is utilization data being reported on the `ReportingPeriodUserDetailView` which does not match the current approach.

## We'll know we're done when 
- [ ] Conflicting utilization data has been removed from the `ReportingPeriodUserDetailView`

**Comment by tbaxter-18f** [comment]
People use that per-person utilization view. Are you suggesting removal, or just get the math aligned with utilization elsewhere?

**Comment by tbaxter-18f** [comment]
Just wanted to link this to #1058, since I think we may have two different user-level utilization views in play.

**Comment by Jkrzy** [comment]
The one that sticks out at the moment is the reporting period view also referenced in #1058 for it's lack of table styling. This issue is intended to focus on the content of that page where utilization is being calculated and displayed as `total billable hours / total hours`.

We should remove that, and if utilization information is useful on that page -- replace with the table/template in use on the employee details page where we render recent tocks.

**Comment by tbaxter-18f** [comment]
Agreed. I wasn't aware we had two different views both reporting individual utilization. I'd say if there's anything useful on the visually-borked one, we port that over to the individual page. Or are you thinking there's a reason to keep the one referenced here?

Either way, it seems like we should tackle this one and #1058 concurrently.
