### ISSUE TITLE
When aggregating utilization data better account for movement throughout TTS

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1057]
As a tock user reporting on utilization I need complete and accurate data for the fiscal year therefore hours billed by staff no longer at 18F should be included in business unit and organizational aggregates.

The current approach to utilization reporting only aggregates data from users which are current and active 18F employees. If a user departs TTS, their billable and target hours within a reporting period should still count towards business unit and organization levels.

## We'll know we're done when
- [x] We've defined the conditions when the timecards of employees no longer with 18F  should be included in utilization aggregates
- [ ] We've implemented timecard level attributes to allow inclusion of said timecards
- [ ] We've updated the documentation

**Comment by tbaxter-18f** [comment]
@Jkrzy does that address your first point?

**Comment by timoballard** [comment]
Notes from offline chat w/ @Jkrzy:

There are complicating factors related to this ticket, such as:

- Users that transition from one `Organization` to another potentially do so in the middle of a reporting period, so their `Timecard` entries for that period could legitimately be split across multiple `Organizations`.
- There's likely to be some delay between the date that a user functionally transitions to a new `Organization` and the date that the change is reflected in Tock.
- There's currently nothing technically preventing users from Tocking to `Projects` belonging to other `Organizations`. This prevents us from simply inferring the user's `Organization` by looking at the `Projects` they Tocked time toward for a given reporting period. This is issue #1060.

For the purposes of this issue, @Jkrzy and I agreed that we should simply associate the user's assigned `Organization` to the `Timecard` at the time of submission.
