### ISSUE TITLE
Add Email Addresses

### ISSUE THREAD

**Issue by saraheckert** [18F/tock#1059]
It appears that some 18Fers are missing email addresses; the email addresses will be needed for the angry tock bot. Can we ensure the email addresses that are missing are added, thank you!

**Comment by Jkrzy** [comment]
Thanks @saraheckert! We'll correct these manually in the admin interface.

Currently 10 by my count.

**Comment by Jkrzy** [comment]
Complete, all active now users have an email address.

**Comment by saraheckert** [comment]
thank you so much! cc: @mgwalker

**Comment by tbaxter-18f** [comment]
@Jkrzy what do you think about a new issue to just make it a required field?

**Comment by Jkrzy** [comment]
I'd like to do a bit of broader thinking around how users are added to the system before going down the path of a new user model or customizing the admin. At the moment there are two paths for users being created. Automatically when authenticated and no account exists, and manually via the admin on a request in Slack.

**Comment by tbaxter-18f** [comment]
Ah, I forgot email is on the User object, not the Employee object. I agree, in that case we really can't do it until we think about our User objects in general. We have #701 to do that.
