### ISSUE TITLE
Data validation request

### ISSUE THREAD

**Issue by saraheckert** [18F/tock#1060]
Would it be possible to add data validation by organization. For example, there are non 18F-ers using 18F non-billable GSA mandated.

For the folks who are non 18F using these codes, I am unsure of how this is calculating into our numbers or if it matters. I think Matt Spencer may be pulling the GSA mandated hours when calculating overhead costs, but this may be something we want to run by him. 

Ex. 
 https://tock.18f.gov/employees/e/anil.chaudhry/ has had 16 hrs/week for several weeks, https://tock.18f.gov/employees/e/brandon.kirby/ has a couple of hours,
https://tock.18f.gov/employees/e/matthew.montano/ was 20 hours last week,
https://tock.18f.gov/employees/e/edward.golden/ had 15 hours,
https://tock.18f.gov/employees/e/kathy.mcneill/ had 40 hours last week (looks new)
https://tock.18f.gov/employees/e/tamieca.hamlin/ had 15 hours, also looks new,
https://tock.18f.gov/employees/e/ambuj.neupane/ had 12, also looks new.)

## ([update](https://github.com/18F/tock/issues/1060#issuecomment-629375775))We'll know we're done when:
- [ ] When creating a new billable Project, Organization will be a required field
- [ ] When creating a new non-billable Project, Organization will be an optional field
- [ ] Employees are allowed to tock to:
  - [ ] Projects associated with their Organization
  - [ ] Projects not associated with any Organization
- [ ] Existing Projects will have their Organization backfilled, which Matt offered to take the lead on

**Comment by Jkrzy** [comment]
Thanks @saraheckert!

Definitely possible, we'd only need to sort out the logic behind who can tock to which project lines and if CoE folks need a new `non-billable GSA mandated` line for their own use.

**Comment by saraheckert** [comment]
I can follow-up with CoE, if that helps.

**Comment by Jkrzy** [comment]
_Someone_ should, I'm not sure if that's you @saraheckert 😄 . We're happy to handle it from within the Tock team as part of refining and planning for the implementation of this issue.

**Comment by tbaxter-18f** [comment]
I would think -- and this is just me thinking -- that who can Tock to a given line may depend on the P&L. Given that we now have every user asssigned to an Org (or are getting there) and every Tock line is associated to a P&L, I think we might be able to filter on the P&L so a given user only sees Tock Lines that relate back to their org P&L.

That may not be a good read, and I may be overcomplicating the issue, though.

**Comment by martyspence** [comment]
if this would be helpful to managing if folks are tocking to correct lines i don't have any issues with it being an added feature. I would just request there be an option to select something like "all can tock to this line" for some lines (e.g. everyone uses Out of Office).

**Comment by timoballard** [comment]
Picking this up - here's what I'm seeing:

- `Projects` have a (nullable) `Org` reference. This doesn't appear to be actively used -- `Project.Org` is null in all cases as far as I can tell.
- `Projects` have a `ProfitLossAccount` reference, which is filled in for all `Projects` for the past several years.
- `ProfitLossAccounts` and `Orgs` have no relationship at the database level.
- Each `Employee` is (at a given point in time) associated with a single `Org` -- sounds like we're at least close to having this data filled out in production?

So, that leaves us with (at least) two implementation options:
- Populate the `Org` reference for existing `Projects`, and restrict `Employees` so that they can only Tock time to `Projects` associated with their assigned `Org` (or `Projects` with no `Org` association, e.g. OOO).
- Establish a database-level relationship between `ProfitLossAccounts` and `Orgs`, and use that to relate `Projects` back to `Orgs`, enabling the same tocking limits as the first option.

---
Does anyone feel strongly about either of those?

**Comment by tbaxter-18f** [comment]
I think @saraheckert and @martyspence  may have some opinions that are move valid than mine on this one, but here's mine for what their worth.

I don't think the Project > Org relationship is important, which is probably why we never did it.
The P&L > Project relationship IS important, as that ties back to budgets and such.

I think we have an informal, unenforced knowledge of the P&L/Org relationship and we're overdue for enforcing it. Because no one should be Tocking outside their P&L (at least as far as I know). So Option 2 sounds to me like simply enforcing what we already intend.

@hannahkane may also have thoughts.

**Comment by hannahkane** [comment]
It's likely I'm misunderstanding something, but one possible exception I can think of to people tocking outside of their P&L - we *do* want OA team members to tock to 18F project lines if they're serving as the CO for an assisted acquisition. Not sure if that would cause a problem here (what P&L does OA fall under?), or if it's worth making a decision based on this edge case.

**Comment by martyspence** [comment]
I prefer the second option (P&L/Orgs relationship), but i do think we might find ourselves in situations where we want someone who isn't on X Org to tock to an X P&L project, so if there's a workaround for those cases that'd be nice (maybe that workaround is just not to un-select P&L for that particular project)

**Comment by tbaxter-18f** [comment]
Hmmm. I'm out of my lane here, but I _think_ in the past when we've had someone working outside of their own P&L we've created a new Tock line within the P&L to account for it. LIke 1053 for example: https://tock.18f.gov/projects/1053/

If that's right, then we already have a mechanism for the edge case. Right?

**Comment by saraheckert** [comment]
I agree with @martyspence, as long as there is a workaround in those unique tock situations, we should be good.

**Comment by martyspence** [comment]
@tbaxter-18f you're right that workaround is something we've done in that past and should be able to do in these edge case situations going forward.

**Comment by timoballard** [comment]
@martyspence - should there be no assigned Org for the P&L Accounts associated with Projects such as [OOO](https://tock.18f.gov/projects/670/)? That way, Employees could see/tock to Projects mapped to their Org and projects not mapped to any Org

**Comment by martyspence** [comment]
yes, i would say let's leave an option to not assign a P&L to all projects so something like OOO can be used by everyone

**Comment by timoballard** [comment]
@martyspence - Projects like OOO do have an assigned P&L currently, so would we remove that association, or just not associate OOO's P&L to any particular Org? Sorry for getting into the weeds, just want to make sure we're on the same page as this will affect how the validation is performed

**Comment by martyspence** [comment]
hmm, i think there will need to be some cleanup with the non-billable P&Ls. I think right now all (or at least most) non-billable lines share the same P&L accounting string whether it's intended to be used by CoE, 18F, Login, or all offices as in the case of OOO. happy to jump on a hangout and sync on this in more detail.

**Comment by tbaxter-18f** [comment]
Question: Why does a non-billable tock line need a P&L set at all?

**Comment by martyspence** [comment]
Honestly it doesn't. We really just need a field or fields when creating new projects where we select 1. whether the project is billable, 2. which P&L owns it/should be tocking to it (with ability to be left blank or to select all)

If billable is chosen for 1. then a field to enter which Agency or office is paying would be good as well.

If that means scrapping/renaming the existing fields I wouldn't have any issues.

**Comment by tbaxter-18f** [comment]
@timoballard does it feel to scope-creepish to you to make P&L optional and enforce its presence only on billable lines?

And does that clear up your concerns?

**Comment by timoballard** [comment]
I don't think it's scope-creep per se, but there would be a data cleanup step here to remove the P&L account associated with non-billable lines, so that those would show up for all Employees.

Assuming ⬆️ sounds right, this approach does address my concerns

**Comment by tbaxter-18f** [comment]
I don't think we'd want to do that data cleanup manually. If I'm searching correctly, it looks like there are 165 non-billable active Tock lines. That's a lot more than I thought. 

On the other hand, it may be that there are only a handful, like OOO, that are used cross-orgs. That would be a @martyspence question.

**Comment by timoballard** [comment]
Right. Assuming there are no (or few) special cases, and we simply want to remove the P&L Account for _all_ non-billable projects, it could be done as part of the migration

**Comment by martyspence** [comment]
yeah there are definitely only a few cross-org lines at most right now, though at different times in TTS history there have been more. OOO is actually the only one I can think of in use right now off the top of my head.

**Comment by timoballard** [comment]
@martyspence and I spoke offline about this this morning. According to Matt, the most useful/important thing from his perspective is to establish the relationship between Projects and Orgs. That relationship does exist, but up to this point hasn't been populated, so we agreed on this approach:

- When creating a new **billable** Project, Organization will be a required field
- When creating a new **non-billable** Project, Organization will be an optional field
- Employees are allowed to tock to:
  - Projects associated with their Organization
  - Projects not associated with any Organization
- Existing Projects will have their Organization backfilled, which Matt offered to take the lead on
