### ISSUE TITLE
get_default_org function needed for Organization

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1066]
to make default value for a foreign key implies setting default values in organization that can be referenced.

note the sample code in https://stackoverflow.com/questions/7080486/how-do-you-specify-a-default-for-the-django-foreignkey-field/7081062#7081062

proposing something like:
`def get_default_org():
    result, _ = Organization.objects.get_or_create(id=1)
    return result`

so that 
the employees/models.py can read:
`organization = models.ForeignKey(Organization, default=get_default_org(), on_delete=models.CASCADE)`

unclear on where this function needs to be due to python inheritance model

reference:
https://github.com/18F/tock/issues/1024

**Comment by tbaxter-18f** [comment]
I don't think we need to do this.
