### ISSUE TITLE
UserData API returns some incorrect data

### ISSUE THREAD

**Issue by mgwalker** [18F/tock#1071]
Some of the user data returned by the UserData API is incorrect. E.g., some people who are no longer with 18F still have the `current_employee` flag set to true. In other cases, non-18F employees have the `is_18f_employee` flag.

You can see the list that popped up for me when testing Angry Tock here: https://gsa-tts.slack.com/archives/C1JFYCX3P/p1588016935306000?thread_ts=1588016905.305900&cid=C1JFYCX3P

**Comment by Jkrzy** [comment]
Proposing we close this one out by:
- [x] Merging #1074 
- [ ] Deprecating `current_employee` and `is_18f_employee` attributes, replacing them with properties that evaluate based on other data. I _think_ we can calculate these and feels duplicative to track this data in multiple attributes if so.

`current_employee` -  True if `user__is_active`
`is_18f_employee` -  True if `organization.name == "18f"`
