### ISSUE TITLE
Complete annual SSP review/update

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1087]
It's that time of year! 🥂 🎄 🎆 

Once this is assigned, let's set a meeting cadence to sync on progress.

Need to complete by July 1, 2020.

## We'll know we're done when
- [x] We've reviewed the current SSP
- [x] If needed, we've made updates
- [x] We've submitted the SSP

**Comment by Jkrzy** [comment]
Dove into this today, working my way through diagrams and control narratives. 

Will need review/signature from @tbaxter-18f as final step.

**Comment by Jkrzy** [comment]
Ready for signatures

**Comment by tbaxter-18f** [comment]
Joe, I've reviewed it and it looks good to me. I'm not seeing the mechanism to sign the Google doc. Are we going to move it into docusign or... ?
