### ISSUE TITLE
Prefill Tock timecards

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1091]
As a Tocker, I want Tock to know my current project and prefill my billable expectation for it, so that I can tock more easily.

Backstory: We've been advising people that counting their non-billable hours is easier and more effective than counting their billable, so this is an attempt to codify that, as well as make it easier to tock, and to more effectively account for underbilling in a more intentional way.

Before we can get far, we'll need to figure out the mechanism by which we associate projects with people ahead of time?

Could we simply prefill with the prior week, or should we assign a project to folks? And if we assign, what's the mechanism to change it? Who does that? Individual? Supe? Sarah?

**Comment by tbaxter-18f** [comment]
cc @saraheckert

**Comment by saraheckert** [comment]
We would need a mechanism to change the hours since expectations change throughout the life of the project. Given this, I think AMs are best equipped to report any changes to the billable hours by role/person on an engagement. @hannahkane is this something you agree with?

If Hannah agrees, we would want a very simple way to note that the hourly expectation on an engagement has changes.

**Comment by hannahkane** [comment]
Interesting. @Jkrzy and I had a conversation about this very thing last week! 

I think it might make sense to let individuals establish in Tock their expected project commitment and be responsible for changing it when it needed. They would be most impacted by it (e.g. noticing when it's wrong) so it would be a natural part of their Tocking workflow; whereas it wouldn't fit into any AM workflows.

**Comment by saraheckert** [comment]
I think initially I was thinking of limiting the number of folks required to update, but this seems like a plausible way of doing it as well and something I did not initially think of. I am good going with individuals updating.

**Comment by Jkrzy** [comment]
[WIP]Initial thinking,

We already have the concept of `pre-fills`, allowing admins to populate timecards with projects/hours for users to either submit as-is or edit as needed.

If we gave users access to modify those pre-fills, we _could_:
1. If none already exists, Ask them to create an initial set of `pre-fills`
2. Render a message on the timecard page along the lines of:
>Your timecard has been pre-filled, please make any necessary changes. If your staffing or billing expectations have changed going forward, please update the pre-fill (link to pre-fill editor)

Considerations
* users may not creating pre-fills and continue to populate weekly
* users may not update pre-fills and continue to populate weekly

**Comment by tbaxter-18f** [comment]
Joe, what do you think about prefilling based on the prior week's data?

My thinking is that week-to-week is _probably_  pretty stable, and when it does change, the change is likely to be reflected for some time to come. Thoughts?

**Comment by Jkrzy** [comment]
🤔 @tbaxter-18f, That would be _real_ quick to implement since we're already bringing project lines from last week's timecard forward. It gets us data to pre-fill timecards, but I'm not sure how close it gets us to "pre-populating with expected billing" -- for 18F at least.

I took a quick look at FY19 timecards, Across all orgs, ~45% of timecards were identical to the previous weeks. Most common for folks outside of 18F.

**Comment by tbaxter-18f** [comment]
My question is how close are they to the same? My gut says that in most cases, they're very close, with just a few hours shifting from one to another, or maybe a few hours over here that wasn't there before.

I'm thinking is this:
1.  we might be able to focus attention on the diff, which is probably the important bit anyway
2. It's really easy, fast and uncomplicated to implement
3. It provides an easy hook to add in "hey, we noticed you underbilled last week. Did that get better this week."

We could also conceivably split the difference and say "if you created a prefill, we'll use it. Otherwise we'll use last week's info as a starting point. Either way, you can edit it."

We could also use last week's as a first step and have true prefills as a follow-up, if needed.

**Comment by saraheckert** [comment]
Spoke to Dan at OGC and this was approved.
