### ISSUE TITLE
pipenv is unhappy in the Dockerfile.

### ISSUE THREAD

**Issue by jadudm** [18F/tock#1092]
It appears that pipenv does not like to work in the root directory anymore. It complains:

```
?1 tock % docker-compose build                                                                                                     (master)tock

db uses an image, skipping
sass uses an image, skipping
Building app
Step 1/6 : FROM python:3.6.5
 ---> 9a58cce9b09f
Step 2/6 : RUN apt-get update && apt-get install -y postgresql-client
 ---> Using cache
 ---> 16d70d96e9e7
Step 3/6 : COPY Pipfile Pipfile
 ---> Using cache
 ---> 12cb06adb27f
Step 4/6 : COPY Pipfile.lock Pipfile.lock
 ---> Using cache
 ---> a8aa92ee21c5
Step 5/6 : RUN pip install pipenv
 ---> Using cache
 ---> 40dab789cd4a
Step 6/6 : RUN pipenv install --support --dev
 ---> Running in 8a11ebc62c69
ERROR: Pipenv is not intended to work under the root directory, please choose another path.
ERROR: Service 'app' failed to build: The command '/bin/sh -c pipenv install --support --dev' returned a non-zero code: 1
```

I did the following to the Dockerfile and it "worked."

```
FROM python:3.6.5

WORKDIR /app
RUN apt-get update && apt-get install -y postgresql-client
```

That is, I changed the working directory for the Dockerfile to an arbitrary path via the WORKDIR directive.

```
WORKDIR /app
```

Whether this is a good path to change it to, etc., I do not know. However, it "worked" in as much as it allowed the Dockerfile to complete, and I was able to stand up a dev environment.

**Comment by Jkrzy** [comment]
🤔 not able to reproduce this one with a copy of `develop`.  That looks like it might be a modified `Dockerfile`?

I'd expect the output to be:
```
Step 6/6 : RUN pipenv install --system --dev
```

**Comment by jadudm** [comment]
As per conversation (off-issue-thread), this should be against `master`; context switch confusion. 

We're both investigating further.

**Comment by Jkrzy** [comment]
OOoo, pipenv may have [addressed this in _yesterday's_ release](https://github.com/pypa/pipenv/releases/tag/v2020.6.2) which get's picked up by a fresh build on my end. 
>Fixed a regression which caused Pipenv to fail when running under /. #4273

🤞 that's the cause of our varying experiences.

@jadudm, can you confirm if it's building successfully on your end with the latest version of pipenv?

**Comment by jadudm** [comment]
Things that make me go "hmm."

Yes, it appears that after removing all images/containers, and doing a fresh build, I get a good front-to-back launch with the sequence described here:

https://github.com/18F/tock/blob/master/docs/local-development.md

I want to do one more run, and make sure I haven't missed something, but assuming everything builds correctly, I'll close the ticket.

**Comment by tbaxter-18f** [comment]
Can we close this?

**Comment by jadudm** [comment]
This was addressed by pipenv upstream updates. No changes required locally.
