### ISSUE TITLE
Onboard @jadudm

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1095]
Welcome and thanks for your help @jadudm!

I'll run through this checklist to get you set-up as part of the Tock development team.

## For @Jkrzy
- [x] Generate a Tock API authorization token in the admin for the new developer.
- [x]  Grant access to New Relic.
- [x]  Grant access to the GitHub repository.
- [x]  Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x]  Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x]  Grant access to gsa-18f-tock org on Snyk.

## For @jadudm
- [x] Familiarize yourself with the systems and scripts your onboarding partner has granted access to
- [x] Review the Tock deployment process

**Comment by Jkrzy** [comment]
All set! I know you've already dove into the docs and other pats of Tock, ✔️ that last box above when you've had a chance to review [the deploy process ](https://github.com/18F/tock/blob/master/docs/deployment-process.md)

**Comment by jadudm** [comment]
Distracted by logging, other deep dive/research. Reviewing deploy.

**Comment by jadudm** [comment]
I have reviewed the deploy process, but have not managed a deploy. However, I think it is reasonable to say I am onboarded at this point, and the ticket can be closed.

I'm closing it, and we can re-open if we decide my onboarding was insufficient.
