### ISSUE TITLE
add more visualizations to assist in audit logging reviews

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1097]
There are a number of visualizations in kibana that may be of service to audit logging review, per comments:  https://github.com/18F/tock/issues/944

Visualization options look like this:
![image](https://user-images.githubusercontent.com/22898229/83569779-a40f7380-a4ea-11ea-8b2b-d8912ea815e0.png)

**Comment by jadudm** [comment]
Yep. I've investigated some of these, and have started a dashboard that collects some of this in one place for consideration/discussion. Will share/talk more in a coming chat.

**Comment by tbaxter-18f** [comment]
Holding off on triaging this pending @jadudm's notes ^

**Comment by cryptofilegsa** [comment]
I'm listed as one of the assignees.  Will follow your directions whenever they are clear.  Am I being gaslighted?  Wouldn't you unassign me if you want that?  Confused about a clearly contradictory guidance, Carter!

**Comment by cryptofilegsa** [comment]
Will pivot our meeting to audit logging handoff over visualizations.

**Comment by tbaxter-18f** [comment]
> I'm listed as one of the assignees. Will follow your directions whenever they are clear. Am I being gaslighted? Wouldn't you unassign me if you want that? Confused about a clearly contradictory guidance, Carter!

You assigned yourself. Please don't assign yourself to stories. I'll correct it.
