### ISSUE TITLE
Update Django and other python dependencies

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1099]
Django team issued 3.0.7 and 2.2.13 as part of their security process and we should use and test this asap. Details here:
https://www.djangoproject.com/weblog/2020/jun/03/security-releases/

**Comment by Jkrzy** [comment]
Let's go ahead and update all of our python dependencies to close this issue out.

a-la: #1007

**Comment by tbaxter-18f** [comment]
Snyk took care of the Django upgrade for us in #1100, so I'm de-prioritizing this.
