### ISSUE TITLE
Weekly Tock Logging Audit [20200612]

### ISSUE THREAD

**Issue by jadudm** [18F/tock#1103]
Complete weekly audit for week ending 2020-06-12 using the instructions on https://github.com/18F/tock/blob/master/docs/logging.md#tock-log-auditing

- [x] Do the audit via Kibana with indicated queries
- [x] Create issue for next week
- [x] check NewRelic output for anything anomalous
- [x] [CircleCI log](https://circleci.com/gh/18F/workflows/tock/tree/master) is consistent with above and known releases

**Comment by Jkrzy** [comment]
Reviewed logs for the week ending 2020-06-12.
