### ISSUE TITLE
Make updating existing timecards easier

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1105]
As a tock administrator I need to update existing/previously submitted timecards so that they accurately reflect the state of world at the time of their submission. Currently this can be done via the admin on a per timecard basis, but modifying multiple timecards at once would greatly facilitate this work and make it easier to remedy incorrect utilization data.

Tuning the Tock admin feels like the most reasonable approach here.

## We'll know we're done when the the Timecard admin page has been updated so that

- [x] Tock Admins can perform in-line edits for fields used in utilization calculations (billable_expectation, organization, ???)
- [x] Tock Admins can filter timecards by Employee

**Comment by cryptofilegsa** [comment]
I took a look and the current /admin/hours/timecard/ is filterable by reporting period only.
Apparently employee is labelled as _User_ in that form.
In any case, a filter by User (employee) can be added.

billable_expectation is editable as a text field.  
organization is editable as a pop-up menu
Can you clarify what is meant by "in-line edits" ?

While doing this, any others to be added?

**Comment by Jkrzy** [comment]
In-line edits being, we want the ability to edit multiple timecards at once from the listing page of the admin. There are a few other models for which we've provided this functionality, like `ProfitLossAccount`
