### ISSUE TITLE
Update base branch, naming, documentation, and configuration

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1108]
Our default git branch for development should be named `main`.

### We'll know we're done when
- [x] The default git branch is `main`
- [x] Documentation has been updated to reflect the new default branch
- [x] CircleCI configuration has been updated

**Comment by cryptofilegsa** [comment]
from Hanselman.com blog post, consider: "git branch -m master main" that -m is --move so history isn't changed and "git push -u origin main" to set the upstream at the same time.  Looks like this will require all of us changing default branch in our GitHub settings.

**Comment by Jkrzy** [comment]
Default branch is now `main`
