### ISSUE TITLE
Adjust billable hour expectations

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1119]
Per https://gsa-tts.slack.com/archives/C0XUF8XL1/p1592837760105000 we need to adjust billable hour expectations for almost everyone. 

Generally speaking, most everyone will be +4 higher, for 36 hours. Exceptions are noted here: https://docs.google.com/spreadsheets/d/1QkvP3IfwuUow9PmHR1gD_FCGYQ12NngOQB3FbVsrfgs/edit#gid=0

**Comment by Jkrzy** [comment]
Let's create an updated sheet and use the command introduced in d15043a1ce39c9140f1fc972072390cda84463f0 to apply changes the week of July 6th.

**Comment by tbaxter-18f** [comment]
Sheet is noted above. I'll post here when it's been fully reviewed.

**Comment by Jkrzy** [comment]
If possible I'd like to run through an audit of 18F folks across the board as part of this effort. There's a few guild leads that I already see need corrections and backfills.

**Comment by tbaxter-18f** [comment]
I could put that on the SMT. I'm already asking them to note _any_ exceptions in the spreadsheet above.

**Comment by tbaxter-18f** [comment]
@Jkrzy I don't have final confirmation from Elizabeth, but I believe the sheet is done and ready to use now. Thanks for your additions to it!

**Comment by Jkrzy** [comment]
Thanks! We'll roll this out the week of 7/6/2020!

**Comment by Jkrzy** [comment]
Realizing now that the existing management command only effects changes to existing Timecards. We need to update billable_expectations on the `UserData` model here.

We'll need another approach

**Comment by Jkrzy** [comment]
Given the short week and need to get this in place for next week, let's make these changes via the admin.

Each employee on this sheet needs to have their `Employee` billable expectation value confirmed and updated if necessary.
https://docs.google.com/spreadsheets/d/1QkvP3IfwuUow9PmHR1gD_FCGYQ12NngOQB3FbVsrfgs/edit#gid=32063559

From [this starting point (current 18F employees)](https://tock.18f.gov/admin/employees/userdata/?current_employee__exact=1&organization__id__exact=1), we can filter by business unit and divide the work amongst a few administrators.

**Comment by Jkrzy** [comment]
As of today this backfill hasn't happened.

We'll now also need to update previous timecards for the weeks starting:
* Aug. 2, 2020
* July 26, 2020
* July 19, 2020
* July 12, 2020
* July 5, 2020

**Comment by Jkrzy** [comment]
To close this out, the management command with changes proposed in #1143 is be executed against the production database with a csv file derived from [this sheet ](https://docs.google.com/spreadsheets/d/1QkvP3IfwuUow9PmHR1gD_FCGYQ12NngOQB3FbVsrfgs/edit#gid=1250072498)

**Comment by Jkrzy** [comment]
Run against the production database
