### ISSUE TITLE
Improve Tock feed to SSOT

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1120]
The 18F and TTS operations teams both use an SSOT spreadsheet to track utilization (among other things). We have identified that Tock could feed more data to this sheet to reduce duplication and improve accuracy. 

*We'll know we're done when:*
-  We've met with Matt Spencer and have identified which data points Tock could be providing but is not currently.
- We have modified Tock to provide any additional data points in the API as needed.
- We have developed a mechanism (or modified existing mechanisms) to allow Tock to feed that data directly from the API

**Comment by tbaxter-18f** [comment]
One definite need: Ability to capture billable hour expectations and keep them updated in the SSOT.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
