### ISSUE TITLE
Update jquery 

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1127]
With #1044 still in process and jquery still hanging around, we need to update the version in use on Tock.

## We'll know we're done when:
- [ ] jquery is updated, per our [docs](https://github.com/18F/tock/blob/main/docs/dependency-management.md), to the latest version

**Comment by jadudm** [comment]
Gah. Would it be better for me to try and accelerate removal?

**Comment by cryptofilegsa** [comment]
code.jquery.com indicates that this is 3.5.1

**Comment by Jkrzy** [comment]
I don't think so @jadudm, this should be a quick lift and can be done independently. Thanks for the offer!
