### ISSUE TITLE
Hiring as a Service - USDS is showing up as non-billable time

### ISSUE THREAD

**Issue by esgoodman** [18F/tock#113]
![screen shot 2015-05-11 at 1 43 26 pm](https://cloud.githubusercontent.com/assets/10067318/7574756/909a4428-f7e4-11e4-941b-eb6665dc7020.png)

...Both of those little dollar icons should be green.

**Comment by wslack** [comment]
This is known and due to our policy about holding that icon until we have a funding mechanism nicely signed and stamped. That being said, all USDS HaaS activities are expected to be formally funded.

**Comment by esgoodman** [comment]
Ah, okay! Thanks for the clarification.

On Mon, May 11, 2015 at 1:54 PM, Will Slack <notifications@github.com>
wrote:

> This is known and due to our policy about holding that icon until we have
> a funding mechanism nicely signed and stamped. That being said, all USDS
> HaaS activities are expected to be formally funded.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/issues/113#issuecomment-101044044>.
>



-- 
Elizabeth Goodman
Design research & UX strategy
18F / GSA
50 UN Plaza
San Francisco, CA 94103
