### ISSUE TITLE
Include_in_utilization to be included in calculations and views

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#1131]
Definition of done in #1084 has been changed a number of times.  
Filing this issue to help clarify what is being asked around the reporting and invoicing requirements.
Current work in #1084 in PR#1121  has the variable and it is editable.

Edge Case for current Tock use: projects on time cards that count towards billability but are not to be invoiced.

This is from written notes taken during July 9 meeting with @hannahkane

Background:

Opposite of most partners.  Some requests are billed up front for 140 hours each, then tock captures ad hoc requests for time, sometimes called microrequests.

In general, billability and utilization have two use cases:
 - Provides data for invoicing currently done by Matt Spencer 
 - Reports on billability targets and percentage achieved for management decisioning
 
Note that microrequests is an ambiguous word and may be used in several contexts with different meanings.

Some parts of 18F are paid up front for a fraction (for example 1/10) a year of work for one person.
This involves four tock lines including: 18F/login  18F/PIF  and 18F/cloud
Currently include_in_utilization only applies to those four specific tock projects.

Definition of done to include changes to calculations in the areas:

1. Tock Projects view shows new calculation

2. Employee  view under utilization 
     Right below billable status put in utilization 
3. For utilization reports by unit
   make the label view of calculated hours different:   
4. calculations are updated in any invoices in use by Matt Spencer

“Pre-billed”  or “truly billable” are alternate language options.
Agreed upon language to describe the calculation is the following:
% billable ( billable + utilized hours / target hours )

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
