### ISSUE TITLE
Use or Lose PermissionMixin

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1138]
We should refactor our usage of `PermisisonMixin`, removing it or replacing with [LoginRequiredMixin](https://docs.djangoproject.com/en/2.2/topics/auth/default/#the-loginrequired-mixin) and defining `permissions_classes` where needed.

In most of our class based views we're inheriting from `tock.utils.PermissionMixin`.

A handful of those views do not then define a `permission_classes` attribute which results in the mixin having no effect. 

Yet another subset of that group then overrides the `dispatch` function to handle permission checking like looking for unauthenticated users. 

e.g. `tock.utilization.views.GroupUtilizationView`

_Originally posted by @Jkrzy in https://github.com/18F/tock/pull/1136/files/6e5cbf42e9d368baad6db6aa60a162e3569c672b_

**Comment by tbaxter-18f** [comment]
We should probably think about writing a test to check for missing permission_classes, too. 

Or just rethink how we do perms altogether.
