### ISSUE TITLE
Utilize Tock data analytics for business intelligence purposes

### ISSUE THREAD

**Issue by neilmb** [18F/tock#1142]
As a member of 18F, or a member of SMT, or a member of TTS BizOps, I want to understand 18F staffing and utilization. There is a great deal of data on that inside of the Tock database and we should be able to analyze and display that data in ways that help people make decisions. Call this goal broadly "Tock Analytics".

We'll need to do user research to figure out what data is valuable to the stakeholders and then surface that data in the Tock app. 

https://github.com/18F/tock/pull/1136 and https://github.com/18F/tock/pull/1141 are first steps in that direction.

**Comment by tbaxter-18f** [comment]
This should probably go hand-in-hand with #1120 

FWIW, I see little interest (at this point in time, anyway) for TTS BizOps to come to Tock for insights. That could change, but for the short term our focus probably needs to be on better feeding data to them. 

On the other hand, I see considerable (and growing) interest among SMT and GMT for more useful tools for tracking these things.

**Comment by neilmb** [comment]
From standup today, @arouault  suggested two more improvements:

- Default the displayed timeline to 2017-10 forward to show the most consistent data by default.
- Implement a UI to display information by one organization at a time, perhaps with a drop-down menu for "organization" in the form that sets the time frame.

**Comment by tbaxter-18f** [comment]
One note on showing data from 2017 forward.. this is something that can be overcome depending on how we display, but when we were showing multi-year data previously, the number of data points made it difficult to extract anything useful from it. I wonder if a 12-month rolling data set would work better?

We could also key off the user org to show their orgs data by default.

**Comment by Jkrzy** [comment]
We've got a solid foundation on this with #1144, #1148, and #1221. Going forward we'll open new issues for our next iterations.
