### ISSUE TITLE
Sidebar links have empty `href` values on production site

### ISSUE THREAD

**Issue by iamjolly** [18F/tock#1145]
On the tock homepage, all of the links in the sidebar under "Using Tock" and "Help and feedback" have empty `href` values when rendered in the DOM. All of these links point to the same page as a result.

I can see that someone recently committed [Fix missing links in sidebar](https://github.com/18F/tock/commit/f9b996c761a3f57d76af8c3d195837e716df32bb) but perhaps this isn't pushed to the production site yet?

Screenshot:
![tock-sidebar-anchors-broken](https://user-images.githubusercontent.com/1093423/90072772-3be0c900-dcb5-11ea-9d88-c207a1eb36a5.png)

**Comment by Jkrzy** [comment]
Thanks @iamjolly! This fix rolled out today, https://github.com/18F/tock/releases/tag/v20200813.1
