### ISSUE TITLE
Update our deploy strategy to use latest and greatest of what cloud.gov has to offer

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1149]
Since we last revisited our deploy approach,   ~2-3 years ago,  the state of CloudFoundry deploys and CLI has changed quite a bit.

Let's revisit our current approach with the goal of moving to a [rolling deployment](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html#deploy), maybe using [sub-commands](https://docs.cloudfoundry.org/devguide/push-sub-commands.html) for migrations, and with the latest version of the cloudfoundry CLI (v7).

Thanks @ccostino!!

ref [slack thread](https://gsa-tts.slack.com/archives/C1JFYCX3P/p1597421252364500?thread_ts=1597326108.362100&cid=C1JFYCX3P)

**Comment by ccostino** [comment]
Please let us know if you have any questions! :-)
