### ISSUE TITLE
Provide revision to NewRelic when recording deploys

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1166]
In addition to the description we provide when recording deployments with NewRelic, we should include the specific revision so it is referenced throughout the NewRelic app.

We track all deployments in NewRelic via their API and python agent `record-deploy` command in `run.sh`

https://docs.newrelic.com/docs/agents/python-agent/installation/python-agent-admin-script-advanced-usage#record-deploy

## We'll know we're done when
- [ ] Revision is provided during Tock deploy recording and tracked by NewRelic

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
