### ISSUE TITLE
Investigate whether to create tock line to track COVID-related admin leave

### ISSUE THREAD

**Issue by arouault** [18F/tock#1168]
- Should we create a tock line to track this type of OOO time called `Administrative Leave - COVID` ?
- Privacy considerations? 
- Possibly add guidance from this doc: https://docs.google.com/document/d/1kiIowld8JIY-ORa1Udaj8EosoHjJXF64IekusOsGtdw/edit?usp=drive_web&ouid=114410930609250902809
- Visualize in analytics tab, over time

**Comment by Jkrzy** [comment]
We decided to not track this in Tock
