### ISSUE TITLE
When creating a time period, default to 7 days

### ISSUE THREAD

**Issue by konklone** [18F/tock#12]
When selecting the start of the time period, automatically set the end of the time period to 6 days later.

**Comment by seanherron** [comment]
I'm not too sure what you mean by this - we don't actually support a user creating their own time period, instead it is created by an admin as a "reporting period". This is because, while a reporting period normally == a week, sometimes they are cut differently, such as during fiscal year changes.

**Comment by konklone** [comment]
Yep, I meant this as a feature to help the admin.
