### ISSUE TITLE
Input lock after no results found

### ISSUE THREAD

**Issue by lauraGgit** [18F/tock#1240]
When you enter a query in the tock line input (for example "ooo") that returns "no results", and then try to have a query (like 670) you are unable to select that tock line. This appears to prevent the total hours calculation and all subsequent added inputs have the same problem.

As a work around a timesheet can be refreshed to clear it

**Comment by Jkrzy** [comment]
This was resolved in https://github.com/18F/tock/pull/1239, thanks for reporting @lauraGgit!
