### ISSUE TITLE
remove 40-hour requirement

### ISSUE THREAD

**Issue by jpyuda** [18F/tock#125]
I would like to build my timesheet through the week as I work day-to-day. The requirement to only ever submit 40 hours (and exactly 40 hours) prevents this. It also prevents me from partially filling out a timesheet and going to check on something in the interim.

At the very least, give me some kind of draft status so it's not an all-or-nothing situation.

**Comment by seanherron** [comment]
I have mixed feelings about this. What do you think @batemapf?

**Comment by fureigh** [comment]
Another reason to have this feature: employees observing religious holidays are required to make up those hours at a different time, which means there will be weeks when there need to be >40 hours to compensate for the times when there are <40 hours.

**Comment by fureigh** [comment]
Perhaps also related: #117.
