### ISSUE TITLE
Create timecard api endpoint 

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1259]
As a tock user, I want to be able to retrieve a list of timecards, along with their attributes, via the API so that I can generate adhoc reports in sheets.

### We'll know we're done when
- [x] We've added an API endpoint with django restframework that serializes and serves the `Timecard` model

**Comment by nick-jones-gov** [comment]
Took a quick look into this, is this something that the existing `/api/timecards.json` endpoint (defined [here](https://github.com/18F/tock/blob/main/tock/api/urls.py#L22)) could be used for? Or maybe there's additional/different data you're looking for here?

**Comment by Jkrzy** [comment]
The existing `timecards.json` endpoint returns a `TimeCardObject` queryset and instances of `TimecardObject`.

The naming here is super confusing but this framing has helped me navigate it:

An instance of `TimecardObject` is one project-entry on an associated `TimeCard`.

The existing `timecards.json` exports "timecard data" by returning all entries  -- `TimecardObjects -- on all timecards for a given query.

What we're looking for here is an endpoint which returns only the data from `hours.models.Timecard`.

**Comment by nick-jones-gov** [comment]
Ah ok, that's helpful - thanks @Jkrzy!

**Comment by nick-jones-gov** [comment]
are there specific fields you're looking to filter on here? I'm assuming that you don't want all `Timecard`s that exist in the DB. I'm imagining that filtering by `submitted` status, user, some concept of time (i.e. "all timecards whose reporting period ended after X date"), maybe business unit? Or if this is a more open question, I can start with what makes sense to me and we can refine in code review.
