### ISSUE TITLE
Upgrade Django to 3.2.latest

### ISSUE THREAD

**Issue by kfoley-18F** [18F/tock#1283]
Django 2.2.latest goes out of long-term support by early 2022. 
The next LTS version is 3.2.latest. 
We'll need to update to latest Django before LTS ends for 2.2.x. 

https://www.djangoproject.com/download/#supported-versions

**Comment by kewlguy781** [comment]
https://docs.djangoproject.com/en/3.2/howto/upgrade-version/

The thing to note here: 


> If you're upgrading through more than one feature version (e.g. 2.0 to 2.2), it's usually easier to upgrade through each feature release incrementally (2.0 to 2.1 to 2.2) rather than to make all the changes for each feature release at once. For each feature release, use the latest patch release (e.g. for 2.1, use 2.1.15).
> **The same incremental upgrade approach is recommended when upgrading from one LTS to the next.**


We will need to figure out how to process this. We need to do every incremental release, which in that case we are looking at updating to latest 2.2 build (as we are not on the latest rev), then 3.0, then 3.1, then finally 3.2!

**Comment by kewlguy781** [comment]
the release is on 2.2.24, so 2.2 is done. focusing on 3.0

**Comment by kewlguy781** [comment]
pull #1317 now have Django 3.1.17. working on 3.2 now.

**Comment by kfoley-18F** [comment]
This is done and merged. closing ticket.
