### ISSUE TITLE
swap out node-sass for dart-sass

### ISSUE THREAD

**Issue by kfoley-18F** [18F/tock#1293]
node-sass is deprecated - https://www.npmjs.com/package/node-sass has details. 
Recommended replacement is dart-sass: https://sass-lang.com/dart-sass

node-sass is also the source of a number of vulnerabilites - https://snyk.io/test/github/18f/tock?targetFile=package.json

Time to update!

**Comment by matthinz** [comment]
@kfoley-18F I can have a look at this!
