### ISSUE TITLE
JS errors

### ISSUE THREAD

**Issue by LindsayYoung** [18F/tock#1295]
Hello friends,

The typeahead and add a line functionality are not working for me. I am getting some JS errors.
Using url: https://tock.18f.gov/reporting_period/2020-06-14/

```
Uncaught TypeError: Cannot read property 'checked' of null
    at timecard.js:20
    at Array.forEach (<anonymous>)
    at getFormData (timecard.js:19)
    at getHoursReport (timecard.js:79)
    at populateHourTotals (timecard.js:116)
    at HTMLDocument.<anonymous> (timecard.js:383)
info.svg:1 Failed to load resource: the server responded with a status of 404 ()
check_circle.svg:1 Failed to load resource: the server responded with a status of 404 ()
```
I tried a hard refresh and it did not help. I am using Chrome Version 91.0.4472.101 (Official Build) (x86_64)

**Comment by LindsayYoung** [comment]
It does look like my time was successfully submitted.
Feel free to close this if you cannot reproduce the issue.

**Comment by matthinz** [comment]
I'm having trouble reproducing this. I'll close, but please re-open if the problem recurs.
