### ISSUE TITLE
PostgreSQL version should be updated to v10

### ISSUE THREAD

**Issue by kbighorse** [18F/tock#1329]
The final release of current version 9.6 is November 11, 2021
https://www.postgresql.org/support/versioning/

The final release of version 10 is November 10, 2022

**Comment by lauraGgit** [comment]
For upgrading the prod-db we'd have to email cg support:

> A note about upgrading major versions
You cannot update an existing instance to a new major version with the update-service command. If you’d like to update your existing database instance to a new major version, please email support for assistance.

[cloud.gov - RDS - Relational databases](https://cloud.gov/docs/services/relational-database/)
