### ISSUE TITLE
Weekly Billing - Allocation Value not represented in Timecard CSV

### ISSUE THREAD

**Issue by colinmurphy01** [18F/tock#1346]
Reproduce

- [View Reports > Timecard Reports](https://tock.app.cloud.gov/reports/) > Complete Timecard Data - FY21
- Downloaded CSV
- CSV does not include Allocation 

Expected

- Allocation data would be included in CSV similar to how it's included in the DB and API
- This field should be included in the following CSVs: Complete timecard data, Complete timecard data with fewer fields

**Comment by colinmurphy01** [comment]
Low priority, not critical for initial weekly billing rollout

**Comment by colinmurphy01** [comment]
Is this being worked on? CC @kfoley-18F

**Comment by neilmb** [comment]
@colinmurphy01 I am working on getting the allocations displayed correctly in the admin console. I haven't been successful yet and we might need to get some stronger Django assistance. Let me make a ticket so we don't lose track of it...

**Comment by neilmb** [comment]
@colinmurphy01 New ticket at https://github.com/18F/tock/issues/1363
