### ISSUE TITLE
Weekly Billing - Staging, Submitting timecards older than PoP

### ISSUE THREAD

**Issue by colinmurphy01** [18F/tock#1347]
Reproduction

- [Example timecard from 04/04/21](https://tock.app.cloud.gov/reports/2021-04-04/colin.murphy/)
- Project, 1233 - 18f test 1, had a PoP that started in Sept 2021
- Project rendered in list and was able to submit

Expected

- Project should not render in dropdown if timecard date is outside of PoP

Additional test - worked as expected...

- Test 5 - is a future start date 10/30
- Project code is hidden in dropdown from user project, until 10/30

**Comment by colinmurphy01** [comment]
Low priority, not critical for weekly billing rollout

**Comment by kewlguy781** [comment]
I do not think its to do with the new codes as the code for the project render from dropdown has not been touched. (and how often do people ran into this in the past?). May will need to triage this for future release.

**Comment by colinmurphy01** [comment]
If this bug is believed to be in production, based on Matt Spencer's experience managing timecard data, we haven't encountered issues with it yet. So this might be something to close and monitor if it comes up again.
