### ISSUE TITLE
Remove sum total tracking from timecard page when weekly billing is present

### ISSUE THREAD

**Issue by neilmb** [18F/tock#1354]
The current situation of counting 100% allocation as 32 hours in the running totals at the bottom of the timecard entry page leads to strange, more-than-40 hours situations when mixing in OOO time with 100% allocation and non-billable time.

In a meeting, we decided to start with removing the running totals when there is at least one project selected that uses weekly billing. This issue is to change `timecard.js` to hide those totals when a weekly billing project is selected on the page. We should be able to make a test to that effect in the Jest/Puppeteer test suite that currently exists.

See https://github.com/18F/tock/blob/weekly-jon/tock/tock/static/js/components/timecard.js#L211 for a similar handler that changes from "project allocation" to "hours spent".

**Comment by colinmurphy01** [comment]
**V1 Copy** to be used as placeholder for now:
Head: Do not work over 40 hours (unless given special approval).
Body: With weekly billing, you are still responsible for working within a basic 40-hour work week.

**Comment by colinmurphy01** [comment]
**V2 for replacing 40 hour sum UI element**
Head: Do not work more than 40 hours.
Body: Under weekly billing, you are still expected to work a 40-hour work week. For those on AWS, this translates to 44 hours one week and 36 hours the following week.
