### ISSUE TITLE
Weekly Billing - Allocation % doesn't display in dropdown when user "saves" (instead of submit)

### ISSUE THREAD

**Issue by colinmurphy01** [18F/tock#1373]
Reproduce:
- Open a new timecard
- Select weekly billing project and select allocation %
- Select "Save your time card for later"
- Timecard saves and page reloads
- Allocation % saved doesn't render in dropdown, similar to hours

Expected:
- Saved allocation % is rendered in dropdown

I don't know how many people save their timecards continuously, so I can't assess this impact this bug has on people.

**Comment by caleywoods** [comment]
Thanks @colinmurphy01. I think @neilmb has already been looking at this but I'm not sure what its most recent status is. We were thinking the fix could be similar to the change made in the Admin area to get the allocation percentage to show up correctly.
