### ISSUE TITLE
18F Practices line items

### ISSUE THREAD

**Issue by mbland** [18F/tock#140]
Just got funding for the following 18F Practices line items; would appreciate getting them added:

- [ ] 18F Hub - A repository for team documentation and a means of surfacing the structure and work of the 18F organization
- [ ] USDS Hub - Aims to facilitate discovery of individuals, teams and projects across all agencies in the broader US Digital Service effort
- [ ] 18F Guides - Aims to disseminate software development and bureaucracy-hacking best practices across 18F and for our partners' digital service teams
- [ ] 18F EDU - Self-directed training materials and proctored workshops to develop the skill sets of 18F and our partners

**Comment by mbland** [comment]
Would appreciate getting this in soon. Got billable hours burning a hole in my pocket.

**Comment by batemapf** [comment]
can you drop a <20 word description for each one of those in here?

**Comment by mbland** [comment]
Added descriptions to the checklist. Where do the descriptions show up?

Also, all of these are paid for using E-Gov funds.

**Comment by batemapf** [comment]
we store them in a field in the tock data set. very helpful for me when someone asks "what project is this?"  hopefully we can move these out of the back end and into some front facing content, but haven't talked about best way to do this.

**Comment by seanherron** [comment]
> but haven't talked about best way to do this.

*tocked

**Comment by batemapf** [comment]
:+1: @seanherron

**Comment by batemapf** [comment]
done.

**Comment by mbland** [comment]
Hey @batemapf, I'm not seeing these items surface in Tock.

**Comment by mbland** [comment]
Ah, they're there now, thanks.
