### ISSUE TITLE
Bunch of squares

### ISSUE THREAD

**Issue by beechnut** [18F/tock#1403]
![Screen Shot 2022-01-07 at 4 31 19 PM](https://user-images.githubusercontent.com/1887182/148610082-94432e84-edb1-4018-8247-a8f3d6de8978.png)
----
![Screen Shot 2022-01-07 at 4 31 17 PM](https://user-images.githubusercontent.com/1887182/148610086-99b601ad-5b54-4bc0-8c44-9b1fd26418fb.png)
----
![Screen Shot 2022-01-07 at 4 31 23 PM](https://user-images.githubusercontent.com/1887182/148610080-57362cfd-4129-4818-a29e-28d82687d4b9.png)

I'm seeing lots of square blocks that I assume are supposed to be icons that aren't rendering properly.

Using Chrome version 97.0.4692.71

**Comment by lauraGgit** [comment]
Thank you for reporting! Fixed by #1408 .
