### ISSUE TITLE
fix datepicker for analytics

### ISSUE THREAD

**Issue by lauraGgit** [18F/tock#1412]
On [the analytics page](https://tock.18f.gov/utilization/analytics)
![image](https://user-images.githubusercontent.com/5840989/150407420-224fa54e-7b68-40aa-90f8-1599d729200c.png) this date picker says that it expects a date in `yyyy-mm-dd` format which is inconsistent with the [uswds datepicker](https://designsystem.digital.gov/components/date-picker/) validation.

Acceptance criteria:
As a user looking to query tock usage data, I can put in a date and query the data.
- without recieving this validation error
![image](https://user-images.githubusercontent.com/5840989/150407851-38c3deea-fc3a-427e-8ecb-3cd06af16103.png)
- without recieving a server error (if use the calendar dropdown data picker)

**Comment by neilmb** [comment]
Fix is likely to make the analytics view convert inputted USWDS-format dates (mm/dd/yyyy) into ISO dates on the backend so that we can keep using the date filtering from the Tock API layer which takes all of its dates in ISO YYY-MM-DD format.
