### ISSUE TITLE
October 2nd Tock error

### ISSUE THREAD

**Issue by SoleCastellano** [18F/tock#1493]
Hello,

I need to edit my last time sheet since looks like my hours where not submitted properly. 

Thanks!

**Comment by cantsin** [comment]
Did an error come up? Otherwise, please join #tock on the TTS Slack and we can discuss there.

**Comment by cantsin** [comment]
Worth noting that we also have a [Tock change request form](https://docs.google.com/forms/d/e/1FAIpQLSe5RDFOlyWm0IXv7_eXjZ3CEjaGj2CmM-_TNgqwMjdspfQz7Q/viewform) but I'm unsure if this will work for your situation.

**Comment by SoleCastellano** [comment]
Hello,

I'm having an error again where I try to submit my time card for 20 hours,
and when I submit and then review it goes to 0 hours.

Best,

Soledad Castellano | O. 202.808.9591
Sr. Graphic Designer | Contractor | Bixal.com <http://bixal.com/> | Centers
of Excellence | GSA

**Comment by SoleCastellano** [comment]
Hello James,

I think I still have an error on my tock time sheet. Please let me know if
I'm able to contact you.

Best,

Soledad Castellano | O. 202.808.9591
Sr. Graphic Designer | Contractor | Bixal.com <http://bixal.com/> | Centers
of Excellence | GSA

**Comment by SoleCastellano** [comment]
Hello, sorry I'm new to this platform. Are you able to edit my timesheet?

**Comment by cantsin** [comment]
Can you please go on the TTS slack and join #tock so we can discuss there? Thank you.

**Comment by cantsin** [comment]
Yep, let's continue the conversation on Slack. When we figure out the bug, I'll open an issue here and you can track the bug fix status if you wish.
