### ISSUE TITLE
Update https://tock.18f.gov/utilization/analytics to account for weekly billed project allocation please!

### ISSUE THREAD

**Issue by kfoley-18F** [18F/tock#1499]
https://tock.18f.gov/utilization/analytics doesn't seem to handle weekly billing, only hourly billing. 

It's worth keeping hourly billed and weekly billed projects separate so that there's a way to see how much of a book of work is weekly vs. hourly. It just needs to show the additional hours.

**Comment by neilmb** [comment]
The solution here is not to make up pretend hours for people on weekly billing, but rather to add charts showing the growth of weekly billing.

**Comment by neilmb** [comment]
Need to add a `project_allocation` column to the query in `utilization_data` and then plot that column in a chart in `utilization_plot` in the file `tock/utilization/analytics.py`.

**Comment by carjug** [comment]
Note to self: `https://github.com/cloud-gov/cf-service-connect/releases/download/1.1.0/cf-service-connect-darwin-amd64` is the plugin binary that worked for me to install the `cf` plugin required for `connect-to-service`

**Comment by carjug** [comment]
I forgot to link this issue to the PR, so I'll paste a link to the PR given that it's already been merged.
https://github.com/18F/tock/pull/1506

**Comment by edwintorres** [comment]
> Note to self: `https://github.com/cloud-gov/cf-service-connect/releases/download/1.1.0/cf-service-connect-darwin-amd64` is the plugin binary that worked for me to install the `cf` plugin required for `connect-to-service`

Thank you @carjug , I was not sure what version to use either. I added a comment to the repo so it's a [little bit more clear in the future ](https://github.com/cloud-gov/cf-service-connect/pull/63)
