### ISSUE TITLE
Add Open Opportunities as Project in Tock

### ISSUE THREAD

**Issue by joshuabailes** [18F/tock#156]
OCSIT/18F MOU 
The Office of 18F and the Office of Citizen Services and Innovative Technologies are separate divisions within OCSIT/18F. This Memorandum of Understanding (MOU) describes the general terms and conditions for technical support activities that the Office of 18F (18F) will provide to the Office of Citizen Services and Innovative Technologies (OCSIT) for the Open Opportunities Platform https://midas.18f.us/.

**Comment by batemapf** [comment]
completed
