### ISSUE TITLE
Add the 18F Delivery Assurance team as an admin

### ISSUE THREAD

**Issue by mgwalker** [18F/tock#1562]
The [18F Delivery Assurance team](https://github.com/orgs/18F/teams/18f-delivery-assurance/members) should be given permissions on this repo. Admin permissions are preferable to reduce friction for the DA team going forward, but this repo's owners have discretion.

**Comment by cantsin** [comment]
@mgwalker 👋🏻 Can you say a bit more how the DA team would use permissions on this repo?

**Comment by mgwalker** [comment]
I would also agree that Tock is a special case compared to other DA projects, since it has an ATO to maintain. 😄

**Comment by cantsin** [comment]
Thanks for the clarification! Yep, adding admin rights is problematic from a compliance/security standpoint. That being said, I just added the `18f-delivery-assurance` team with write permissions so the relationship is more explicit; as you note, `18f-delivery-assurance` ⊆ `18f-staff` so nothing has really changed in regards to permissions.

**Comment by cantsin** [comment]
I think we can close, but leaving this open in case further discussion is needed. CC @edwintorres

**Comment by edwintorres** [comment]
Why the explicit write permissions? That makes it difficult to maintain.

**Comment by cantsin** [comment]
@edwintorres It's a bit of a hassle but I don't think it's a lot to maintain, unless I'm missing something here. 

`18f-delivery-assurance` is its own Github team and they can onboard/offboard folks to/from that team as they wish, we don't do anything on that end. I believe `write` permissions makes sense for that team. As you know, users can't push directly to `main` -- they can make branches, sure, but if they want these merged to `main`, they have to go through a peer review process _anyway_. So I think this is pretty much what we had before. Again, I think we are making the relationship a bit more explicit in Github. 

Does the above help? Is there anything I'm missing here?

**Comment by edwintorres** [comment]
Thank you for the answer. I don't see major issues. If both GitHub teams have the same permission, and one already inherits from the other one, I am not seeing how this contributed. But I don't have a reason to stop the change either. So LGTM.
