### ISSUE TITLE
Accessibility: Color contrast on subtitles in table headers

### ISSUE THREAD

**Issue by sarahmhgov** [18F/tock#1568]
### Steps to Reproduce:

Location:
https://tock.18f.gov/utilization/

Expected:
All text should meet color contrast requirements. 

Actual:
<img width="811" alt="222297716-df4b8ad6-e555-439b-8244-6555fe569bf5" src="https://user-images.githubusercontent.com/124302726/225386907-17a8d778-9a05-492d-8186-0a2ca57289d2.png">

Subheaders in tables do not meet color contrast requirements.

Very low contrast (3.49:1)
Very low contrast between text and background colors.

### Remediation guidance:
Guideline: 1.4.3 Contrast (Minimum)

**Comment by melchoyce** [comment]
What if we tried `#f3f3f3` (`gray-4`) for the table header, and `#5c5c5c` (`gray-60`) for the subtitle color? That's a contrast ratio of 6.02:1, which passes AA.

**Comment by jasnakai** [comment]
PR #1582 created for resolution of issue.
