### ISSUE TITLE
Accessibility: Access keys are present in navigation, can conflict with screen readers

### ISSUE THREAD

**Issue by sarahmhgov** [18F/tock#1569]
Steps to Reproduce:

Issue exists in navigation across tock: 
https://tock.18f.gov/#

Expected:
Access keys are not recommended due to potential conflicts with user shortcut keys.

Actual:

Access keys are present in the tock navigation (see image)

Standards: 

[2.4.1 Bypass Blocks (Level A)](https://webaim.org/standards/wcag/checklist#sc2.4.1)

Remediation guidance:

Consider removing access key in order to reduce potential issues. 

<img width="825" alt="image" src="https://user-images.githubusercontent.com/124302726/222798183-ef2022ee-e4d6-4282-8095-b5000dfcad36.png">

**Comment by jasnakai** [comment]
Closing since this is done.
