### ISSUE TITLE
[utilization] Understanding the impact to the billing process

### ISSUE THREAD

**Issue by jduss4** [18F/tock#1588]
Sub-task of https://github.com/18F/tock/issues/1500

Before we update utilization in Tock, we need a better understanding of how information is used for generating billing statements. Data from Tock is exported to a G-doc / sheet, manually manipulated, then exported as CSVs. The CSVs are fed into an [invoice processing script](https://github.com/18F/TTS-invoice-process) which crunches numbers and creates PDFs.

Talk to the people involved in this process to understand how they interact with the data in Tock and how changes we may make while updating the utilization values may impact them.

- [x] Talk to Matt Spencer about the initial export and manipulation
- [X] Talk to Matt Jadud about the invoice processing script

**Done when**
- [x] Spoke with both parties
- [x] Documented anything about the process that seems relevant to our utilization work

**Comment by jduss4** [comment]
Added notes to [the mega doc](https://docs.google.com/document/d/1EeUHQO86HX1dN29POiEeOeGapN9jbTf6ZaSKDLPGMyQ/edit#heading=h.x3qvjl1b7ys2) 🔒

**Comment by alexbielen** [comment]
LGTM! Moving to done.
