### ISSUE TITLE
[utilization] Adjust total_allocation_hours calculation

### ISSUE THREAD

**Issue by jduss4** [18F/tock#1612]
Related to epic #1500 

Currently, [`timecard.total_allocation_hours`](https://github.com/18F/tock/blob/main/tock/hours/models.py#L369) uses a [hardcoded value from `base.py`](https://github.com/18F/tock/blob/main/tock/tock/settings/base.py#L154) of 32 hours to calculate the equivalent amount of hours the _billable_ weekly allocation represents.

We may want to adjust this calculation to begin with the [`timecard.target_hours`](https://github.com/18F/tock/blob/main/tock/hours/models.py#L307) value instead of the hardcoded base.py value.

Done when:
- [x] total_allocation_hours has been altered to correctly estimate a weekly to hourly conversion
- [x] tests have been added to or updated to reflect the new field values

**Comment by cantsin** [comment]
I agree -- I think hard-coding 32h/week was a small mistake, in hindsight (the relevant PR is from December 2022). Besides, we've had general 36h/week billable requirements in the past (and to be clear, not expecting that to happen again!). Anyway doing it on the timecard level makes sense. CC @kfoley-18F
