### ISSUE TITLE
18F billable expectation audit

### ISSUE THREAD

**Issue by alexbielen** [18F/tock#1627]
The problem: An 18F individual contributor's default billable expectation is 32 hours (or .8 in Tock). This was not universally updated in Tock when the organization switched from a 36 hour billable expectation for individual contributors. Additionally, staff have changed roles in the organization and billable expectations may not be correctly set on a role basis (e.g., supervisory expectation is typically .4). 

 What we'd like to do: To start, we want to make these discrepancies visible. We suggest building a spreadsheet that lists 18F staff name, their current billable expectation in Tock (`Employee.expected_billable_hours`) and their current expected project allocation (`Employee.expected_project_allocation`)  and what we believe their billable expectation and allocation should be.

Next, we'd give this to the Director of Ops to confirm these expectations and then they can give to a Tock admin to make the changes. 

These discrepancies were uncovered during work on #1500 so @jduss4 and @kingcomma have context on this. 

@cantsin @edwintorres and @kfoley-18F : Do you all see any issues with this? We'd like to take this on as part of TLC Crew's increment.

- [x] Announce this change to 18F staff so that they are not surprised if they a change to their billable expectation.

**Comment by cantsin** [comment]
Wonderful idea.

A couple of notes:

1. I don't think the Tock API has these fields exposed so we'd have to add them which means a PR (and a release) is necessary. Fortunately, these changes will be easy to do. (Or maybe you had another way to pull in that information?)
2. Can we document this process as we go through -- assuming it is a one-time process for now -- so we can repeat in the future? It's quite difficult to keep billable expectations up to date automatically but perhaps we can make it easier for future us, should we have to do this process again.

**Comment by kfoley-18F** [comment]
We've done a billable expectations audit twice before in my time at 18F. 
They aren't frequent but DO happen. 

I believe there are 2 ways to update: 
1) DB select statement + write transaction
2) I *think* this can be updated manually per person in the Tock Admin views but would have to double check.

**Comment by cantsin** [comment]
For updating, I have a slight bias towards a data migration since that helps staging as well and is an explicit record of these changes. (But I don't feel too strongly -- any of the proposed approaches will work just fine)

**Comment by jduss4** [comment]
My understanding of this issue may differ from that of @alexbielen and @kingcomma 's, but we were focused on pulling information out and helping you identify where billable expectation may be incorrect. We had not been planning on making the changes ourselves. I think we (or at least I) had assumed admins would make the changes by hand.  Would it make sense for the updates to spin off into a separate issue, rather than increasing the scope of this one?

**Comment by alexbielen** [comment]
Yup, I was hoping the deliverable from TLC here would be something that Kelsey can check and then one of the Tock admins can implement.

**Comment by alexbielen** [comment]
Also, @jduss4 and @kingcomma I could see documenting the process as follow-on work. What do you all think?

**Comment by alexbielen** [comment]
@jduss4 and @cantsin 

I added an acceptance criteria re: announcing this change to the org so they're not surprised.

**Comment by jduss4** [comment]
I forgot to update this issue, but if someone is on detail they should have a normal billable expectation (.8 for IC, .4 supervisor, etc) and then Tock to a "detail" line.

**Comment by jduss4** [comment]
I created a couple slides in the TLC Crew coffee share-out!

**Comment by alexbielen** [comment]
Criteria ACCEPTED. Are we good to call this closed now?
