### ISSUE TITLE
Add Total Hours Counter even with Weekly Billing Projects in Reporting Period Page

### ISSUE THREAD

**Issue by edwintorres** [18F/tock#1638]
**Problem**
As a user of the application, I noticed that whenever I add a project with weekly billing on the Reporting Period Page, the total hours counter at the bottom of the page is removed. This feature is extremely useful in tracking the total amount of hours spent across all projects, irrespective of their billing type.

Example when a user has a weekly billing project.

![image](https://github.com/18F/tock/assets/4247796/ad2dff6d-8a2f-4914-b4ca-ebf31a48792a)

Example when a user do not have a weekly billing project

![image](https://github.com/18F/tock/assets/4247796/4dfefc7d-127e-4b37-8396-89c60357520f)

**Describe the solution you'd like**
Ideally, the total hours counter should persist on the Reporting Period Page regardless of the billing method used for the project. This feature would improve usability by providing a consistent and holistic view of hours spent across all types of projects at the time of weekly timesheet completion. 

Calculating and displaying total hours is useful for most users. However, AWS schedule users may find the chart's color-coding (which turns red after 40 hours a week) less relevant. Thus, maintaining the chart's visibility, despite color discrepancies with AWS schedules, is more beneficial than the current setup, providing a visual representation of logged hours for all users.

**Describe alternatives you've considered**
An alternative could be to provide separate counters for different types of billing (e.g., one for hourly and another for weekly billing), but it may cause fragmentation and could make the overall view less clear. A unified counter would make tracking and analysis much simpler.

**Comment by edwintorres** [comment]
@rrefoy @cantsin 

With a minor adjustment, we can display the "Total hours" counter continuously. I've set the color for "Total hours" to grey. However, I'm concerned that the "Total hours" displayed here might differ from those in the utilization report, given that they are calculated in different places. 


![image](https://github.com/18F/tock/assets/4247796/589a15ac-29a3-483f-8c5a-ef2218f01ce3)


![image](https://github.com/18F/tock/assets/4247796/6537565a-176a-4953-854d-2372dfffddf7)

**Comment by cantsin** [comment]
I think having the utilization calculation in two different places is something we're going to have to live with 🤷🏻‍♂️ so the above idea LGTM
