### ISSUE TITLE
add naming conventions / style rules to django "new project" interface

### ISSUE THREAD

**Issue by batemapf** [18F/tock#166]
- no CamelCase
- spaces between slashes
- no commas!
- identify consulting projects by "Consulting / [NAME]"

@quepol other suggestions?

**Comment by quepol** [comment]
How about:

In an effort to make each project as searchable as possible, please apply the following conventions to project names:

- no commas!
- no CamelCase
- surround slashes with spaces 
- identify projects with [OFFICE] / [NAME] where appropriate; e.g. Consulting / Navy
- use words not abbreviations; e.g. Manager, not Mngr

??? @batemapf

**Comment by batemapf** [comment]
works for me.  associating this issue with #167 if i haven't already

**Comment by batemapf** [comment]
@martyspence would you mind updating this issue with the current naming conventions?  from there, we can add into the admin panel.
