### ISSUE TITLE
Data migration for 18F/CoE

### ISSUE THREAD

**Issue by cantsin** [18F/tock#1680]
Original ask: "would it be possible to update so that 18F and CoE staff can record time to either office's billable tock codes?"

I believe so, but we need to do some groundwork first:
- Investigate the ramifications of assigning two organizations to a single employee
- Let's make sure changes to org do not impact the invoicing script/process
- Are we making the assumption that one organization == one billing structure?
- Or, can we unify billing codes under one org?
- Or, can we set it up so that multiple tock codes bill to the same line?
- Consider a data migration for CoE/18F employees so that they can bill to either organization

**Comment by edwintorres** [comment]
Data migration refers to reassigning everyone to a new organization (eg TTS Consulting) ?

**Comment by edwintorres** [comment]
No needed after https://github.com/18F/tock/pull/1829
