### ISSUE TITLE
new categories: College Choice and GovConnect

### ISSUE THREAD

**Issue by ultrasaurus** [18F/tock#171]
College Choice: Dept of Education project to engage and educate potential college students of any age or background, and those that support and advise them, to find schools best suited to them. (aka PICC, Project Inform College Choice)

GovConnect: OPM operates GovConnect, which is an agile workforce initiative to crowdsource talent and professional development opportunities.  This is a research project to evaluate pilots and exisiting programs, including Open Opportunities.  This is part of the Midas line of business, and the research will inform future product development efforts.  It may or may not lead to follow-on OPM software development work.

**Comment by batemapf** [comment]
added!
