### ISSUE TITLE
Make Platform as a Service billable!

### ISSUE THREAD

**Issue by NoahKunin** [18F/tock#172]
We got funded! As of last week, PaaS (cloud.gov) should now accrue as billable to our ASF budget (I think, or maybe since this is the first of its kind, we do something else, raising the issue here).

**Comment by batemapf** [comment]
done.

**Comment by NoahKunin** [comment]
This seems to have been borked. We now have two line items.

**Comment by NoahKunin** [comment]
This was resolved, but not closed. Closing!
