### ISSUE TITLE
Possible bug: Server error after clicking on tock line 1668 - 18F / ARP FAC

### ISSUE THREAD

**Issue by amandarkennedy** [18F/tock#1740]
While working on [TLC issue #100: Add project tock code for every project](https://github.com/18F/TLC-crew/issues/100), I was looking into the Tock code for the FAC project. I encountered a "system error" when clicking on tock code 1668 - 18F/ARP FAC.

Steps to reproduce:

1. [Click on the Tock profile for Tadhg O'Higgins](https://tock.18f.gov/employees/tadhg.ohiggins/)
2. Select "[1668 - 18F/ARP FAC](https://tock.18f.gov/projects/1668/)" under "Projects" 
3. You should see an error message, "Server error: A server error has occurred." See screenshot below.
<img width="1122" alt="Screenshot 2024-03-26 at 12 39 09 PM" src="https://github.com/18F/tock/assets/121978626/0861762d-cd7d-40bf-b8cd-e5ff9a6c8f78">

**Comment by cantsin** [comment]
We have a release happening today that might fix this. Please stay tuned :)

**Comment by cantsin** [comment]
This is fixed now! If you go to https://tock.18f.gov/projects/1668/ it all shows up now. Many thanks to @neilmb for doing the actual fix, all I did was click some buttons to release Tock 😄

**Comment by amandarkennedy** [comment]
Awesome! Thank you so much, @neilmb and @cantsin :)
