### ISSUE TITLE
Save option

### ISSUE THREAD

**Issue by vzvenyach** [18F/tock#177]
As a BILLABLE EMPLOYEE, I want to save a draft of the timecard during the week so that I can log my time over the course of the week.

**Comment by batemapf** [comment]
temporary hack - enter the hours you want and drop the rest in general so total = 40.  you can always revise your time cards at any time.

**Comment by batemapf** [comment]
@vzvenyach happy to move this one toward the top of the list if you think it is a good candidate for MP...

cc @adelevie @allalala

**Comment by batemapf** [comment]
addressed via #300. feature deployed. @vzvenyach good to close this issue?

**Comment by vzvenyach** [comment]
:+1:
