### ISSUE TITLE
Project Table

### ISSUE THREAD

**Issue by vzvenyach** [18F/tock#178]
As a SUPERVISOR, I want to see a table describing the hours for a given project (e.g. https://tock.18f.gov/projects/65/) in addition to the visualization, so that I can track the burn rate for a project.

**Comment by mbland** [comment]
I'd imagine not just as a supervisor, but as a project manager as well. I hacked together [a Ruby script to query billable hours by project on the command-line](https://github.com/mbland/mbland-18f-utils/tree/master/tock), the output of which I plug into a spreadsheet with the hourly rates to track the burndown. It's a nice stopgap until this feature becomes native.

**Comment by batemapf** [comment]
table has been added, but needs work via #259
