### ISSUE TITLE
Convert hours to percentages automatically

### ISSUE THREAD

**Issue by kaitlin** [18F/tock#18]
allow the user to enter hours instead and calculate the percentage based on a 40 hour workweek automatically.

**Comment by seanherron** [comment]
I was thinking of basically providing two `input` fields next to each other, like this:

`| HOUR | PERCENTAGE |`

You could enter in either a number of hours (which would then automatically fill in the relevant percentage) or fill in a percentage (which would then automatically fill in the number of hours). It may be a bit complicated looking though - any ideas for a simpler solution?

**Comment by konklone** [comment]
I do think that would be a bit complicated looking. I think putting in hours is the more straightforward solution, both conceptually and UX-wise. But you could allow people who prefer entering %'s for some reason to toggle their input mode to that too, either with a user-wide default or on a per-form basis.

**Comment by kaitlin** [comment]
Yeah I think I might just have a toggle button that switches between percentages and hours for all the fields.

**Comment by seanherron** [comment]
This does bring up a tangentially related question - should we account for federal holidays/snow days/etc in reporting periods, or continue to have users add them in as `Out of Office`. For instance, if we have a federal holiday on a monday, should users put 20%/8 hours in "Out of Office", or should that be assumed on the backend and they would simply fill out for the remaining 4 days of the week?

**Comment by jpyuda** [comment]
At the very least it would be nice to allow half-percentages. 1 hour is 2.5%.

**Comment by esgoodman** [comment]
+1. A choice of hours as well as percentages would speed up timesheet completion considerably for those of us who work different hours on different projects each week.

**Comment by vzvenyach** [comment]
Until direction from higher ups, wontfix.

**Comment by seanherron** [comment]
I just pushed a trial for this that allows people (well, requires people) to report in hours instead of percentages! For example, here's @kaitlin's new timecard: https://hub.18f.us/tock/reports/2015-04-26/kaitlin.devine%40gsa.gov/

Stephanie is going to be sending out some guidance before the next reporting period is due around this.
