### ISSUE TITLE
Add CAP projects

### ISSUE THREAD

**Issue by phirefly** [18F/tock#181]
Please add these projects
* C2: Core Platform
* C2: National Capital Region
* C2: Public Buildings Service

**Comment by batemapf** [comment]
@phirefly to @ethanheppner question in #tock channel - are these all still billable to FAS under the CAP Communicart agreement?  also can you add in a super short (<20 words) description of each item?

**Comment by ethanheppner** [comment]
Done! Please let me know if the descriptions need to be revised.

**Comment by ethanheppner** [comment]
Updated C2: Core Platform's description to clarify that it replaces the now-depreciated CAP Communicart.
