### ISSUE TITLE
Add Project Review line for time logging

### ISSUE THREAD

**Issue by wslack** [18F/tock#184]
This is for time spent planning and conducting project review work, as well as time spent by teams sharing the knowledge and insights.

**Comment by batemapf** [comment]
is this project intake?

**Comment by batemapf** [comment]
or project out-take?

**Comment by wslack** [comment]
Hah!

It's a new process @yozlet is leading to check-in on projects and close them out. Not strictly connected to intake.

**Comment by batemapf** [comment]
shouldn't time spent checking in on a specific project or closing out a project be billed to that specific project?

**Comment by wslack** [comment]
Per @StephanieRivera, this line item is NB. However, we may bill some related time for this work to the project, depending on where the value is being added.

**Comment by batemapf** [comment]
@wslack ok to close?

**Comment by wslack** [comment]
yep, this is a workgroup.
