### ISSUE TITLE
add additional data fields to employee objects

### ISSUE THREAD

**Issue by batemapf** [18F/tock#186]
add the following fields to employee objects: business line; sub-business line; locality; virtual; and probably other categories cc @adelevie

**Comment by adelevie** [comment]
:+1: @batemapf

**Comment by ramirezg** [comment]
@batemapf and @adelevie are there set options for these fields?  Do you mind describing them in a little more detail? Maybe in a short meeting if we need.

**Comment by batemapf** [comment]
@ramirezg yep, there are set options for each one.  here goes (of course, i am sure edits will be needed later):

Field | Tier 1 Option | Tier 2 Option
------  | ----------------- | -------------------
**Business Line** | *Business Operations and Strategy Division* | Leadership
 | Business Operations and Strategy Division* | Operations
 | Client Services | Engineering
 | Client Services | Product
 | Client Services | Leadership
 | Consulting Division | Consulting
 | Consulting Division | Leadership
 | Creative Comm and Community Division | Outreach
 | Creative Comm and Community Division | Leadership
 | Creative Comm and Community Division | Design Experience
 | DevOps Division | Leadership
 | DevOps Division | DevOps
**Locality** | CALIFORNIA | null
 | DISTRICT OF COLUMBIA | null
 | OHIO | null
 | NEW YORK | null
 | VIRGINIA | null
 | PENNSYLVANIA | null
 | GEORGIA | null
 | NORTH CAROLINA | null
 | OREGON | null
 | WASHINGTON | null
 | ARIZONA | null
 | MASSACHUSETTS | null
 | MISSOURI | null 
 | ILLINOIS | null
**Virtual** | TRUE | null
 | FALSE | null

**Comment by batemapf** [comment]
functionality no longer needed in `tock`
