### ISSUE TITLE
Show the report after submission

### ISSUE THREAD

**Issue by kaitlin** [18F/tock#19]
It would be nice to actually summarize the report for the user after they report so they can make sure it is correct and it is clear what was submitted. Could also take it one step further and maybe give them a nice little report that shows billable vs non-billable, wg/guild time, or other interesting tidbits.

**Comment by seanherron** [comment]
:+1: 

I would like to have a very simple dashboard that allows someone to both see an individual and org-wide representation of how hours are being spent.

**Comment by seanherron** [comment]
How does this look?

https://hub.18f.us/tock/reports/2015-03-30/kaitlin.devine%40gsa.gov/

**Comment by kaitlin** [comment]
Love it!
