### ISSUE TITLE
Deprecate MyUSA line item in favor of USA.gov - Labs

### ISSUE THREAD

**Issue by NoahKunin** [18F/tock#196]
Funding for MyUSA, inclusive of labor, is now coming out of USA.gov - Labs AFAIK as of Phaedra's signature this morning. 

We should remove the MyUSA stand alone line item, as not to create more work for ourselves in the future fixing the funding streams.

**Comment by batemapf** [comment]
cc @ethanheppner can you mark "myUSA" as "myUSA [DEPRECATED]" and add a new line for USA.gov - Labs (if there isn't one already)?  funding should be GSA - OCSIT

**Comment by ethanheppner** [comment]
Done.

On Mon, Jul 6, 2015 at 10:04 AM, Patrick Bateman <notifications@github.com>
wrote:

> cc @ethanheppner <https://github.com/ethanheppner> can you mark "myUSA"
> as "myUSA [DEPRECATED]" and add a new line for USA.gov - Labs (if there
> isn't one already)? funding should be GSA - OCSIT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/issues/196#issuecomment-118883816>.
>



-- 
Ethan Heppner
Operations Specialist
https://18f.gsa.gov/
U.S. General Services Administration

**Comment by jackiekazil** [comment]
Shouldn't we keep all the projects as separate line items?

**Comment by NoahKunin** [comment]
@jackiekazil Tock isn't a tool for project management or resource allocation, it's a tool for billing.

**Comment by meiqimichelle** [comment]
@NoahKunin I thought Tock was being positioned to be a tool for project management in the future.

**Comment by NoahKunin** [comment]
@meiqimichelle Tock's roadmap can't really be discussed effectively in a single issue - suffice to say, while people may want that, that's not something we're currently engaged to do.

**Comment by meiqimichelle** [comment]
@NoahKunin Thanks for the update/close. My comment was OBE.
