### ISSUE TITLE
Unexpected redirect and timeout

### ISSUE THREAD

**Issue by jmcarp** [18F/tock#223]
On loading `https://tock.18f.gov/`, I currently get a redirect to `https://tock.18f.gov/LeagueLookup`, followed by a 504 timeout. The headers appear to be coming from an ASP.net application, presumably not an 18F product, and nothing shows up in the CF logs for Tock. If I load `https://tock-app.18f.gov/` directly, the site works as expected. The former URL is configured in the hub and (normally) proxies requests to the latter. This leads me to think that something's going wrong at the level of the auth proxy or the hub nginx configuration.

@mbland, can you think of anything that would cause the auth proxy or nginx to redirect to a different application? I don't see anything out of place in the nginx configuration.

cc @ramirezg

Here's an example of the behavior I'm talking about:
```
$ http https://tock.18f.gov/ 'Cookie:_oauthproxy=<cookie>'

HTTP/1.1 302 Found
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Cache-Control: private
Cache-Control: no-cache="set-cookie"
Connection: keep-alive
Content-Length: 3845
Content-Type: text/html; charset=utf-8
Date: Thu, 27 Aug 2015 02:16:41 GMT
Location: https://tock.18f.gov/LeagueLookup
P3p: CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
Server: nginx/1.8.0
Set-Cookie: ASP.NET_SessionId=ztxhlmybdplvtq11fdptzd13; path=/; HttpOnly
Set-Cookie: AWSELB=C3E3A761060531C30F1D9347E5E453F3F7AA51F768FAF616EB1D3238B140D3E44FC7E3D4B73CE447C45AB84571E9FE9B73A6E77A5C1347C11D51339DF296E0DFAC0ACDEA4B;PATH=/
Strict-Transport-Security: max-age=31536000
X-Aspnet-Version: 4.0.30319
X-Aspnetmvc-Version: 5.2
X-Frame-Options: DENY
X-Powered-By: ASP.NET

<html><head><script type="text/javascript">window.NREUM||(NREUM={});NREUM.info = {"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"d421981c52","applicationID":"9193761","transactionName":"NlYAZ0YAW0IAB0VaWQ8cL2V3Tn1eDAFyXFgVQQ1fWARHHigKVVZO","queueTime":0,"applicationTime":36,"ttGuid":"D427CA844859573E","agent":"js-agent.newrelic.com/nr-686.min.js"}</script><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(e,n,t){function r(t){if(!n[t]){var o=n[t]={exports:{}};e[t][0].call(o.exports,function(n){var o=e[t][1][n];return r(o?o:n)},o,o.exports)}return n[t].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<t.length;o++)r(t[o]);return r}({QJf3ax:[function(e,n){function t(e){function n(n,t,a){e&&e(n,t,a),a||(a={});for(var u=c(n),f=u.length,s=i(a,o,r),p=0;f>p;p++)u[p].apply(s,t);return s}function a(e,n){f[e]=c(e).concat(n)}function c(e){return f[e]||[]}function u(){return t(n)}var f={};return{on:a,emit:n,create:u,listeners:c,_events:f}}function r(){return{}}var o="nr@context",i=e("gos");n.exports=t()},{gos:"7eSDFh"}],ee:[function(e,n){n.exports=e("QJf3ax")},{}],3:[function(e,n){function t(e){return function(){r(e,[(new Date).getTime()].concat(i(arguments)))}}var r=e("handle"),o=e(1),i=e(2);"undefined"==typeof window.newrelic&&(newrelic=window.NREUM);var a=["setPageViewName","addPageAction","setCustomAttribute","finished","addToTrace","inlineHit","noticeError"];o(a,function(e,n){window.NREUM[n]=t("api-"+n)}),n.exports=window.NREUM},{1:12,2:13,handle:"D5DuLP"}],gos:[function(e,n){n.exports=e("7eSDFh")},{}],"7eSDFh":[function(e,n){function t(e,n,t){if(r.call(e,n))return e[n];var o=t();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(e,n,{value:o,writable:!0,enumerable:!1}),o}catch(i){}return e[n]=o,o}var r=Object.prototype.hasOwnProperty;n.exports=t},{}],D5DuLP:[function(e,n){function t(e,n,t){return r.listeners(e).length?r.emit(e,n,t):void(r.q&&(r.q[e]||(r.q[e]=[]),r.q[e].push(n)))}var r=e("ee").create();n.exports=t,t.ee=r,r.q={}},{ee:"QJf3ax"}],handle:[function(e,n){n.exports=e("D5DuLP")},{}],XL7HBI:[function(e,n){function t(e){var n=typeof e;return!e||"object"!==n&&"function"!==n?-1:e===window?0:i(e,o,function(){return r++})}var r=1,o="nr@id",i=e("gos");n.exports=t},{gos:"7eSDFh"}],id:[function(e,n){n.exports=e("XL7HBI")},{}],G9z0Bl:[function(e,n){function t(){var e=d.info=NREUM.info,n=f.getElementsByTagName("script")[0];if(e&&e.licenseKey&&e.applicationID&&n){c(p,function(n,t){n in e||(e[n]=t)});var t="https"===s.split(":")[0]||e.sslForHttp;d.proto=t?"https://":"http://",a("mark",["onload",i()]);var r=f.createElement("script");r.src=d.proto+e.agent,n.parentNode.insertBefore(r,n)}}function r(){"complete"===f.readyState&&o()}function o(){a("mark",["domContent",i()])}function i(){return(new Date).getTime()}var a=e("handle"),c=e(1),u=window,f=u.document;e(2);var s=(""+location).split("?")[0],p={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-686.min.js"},d=n.exports={offset:i(),origin:s,features:{}};f.addEventListener?(f.addEventListener("DOMContentLoaded",o,!1),u.addEventListener("load",t,!1)):(f.attachEvent("onreadystatechange",r),u.attachEvent("onload",t)),a("mark",["firstbyte",i()])},{1:12,2:3,handle:"D5DuLP"}],loader:[function(e,n){n.exports=e("G9z0Bl")},{}],12:[function(e,n){function t(e,n){var t=[],o="",i=0;for(o in e)r.call(e,o)&&(t[i]=n(o,e[o]),i+=1);return t}var r=Object.prototype.hasOwnProperty;n.exports=t},{}],13:[function(e,n){function t(e,n,t){n||(n=0),"undefined"==typeof t&&(t=e?e.length:0);for(var r=-1,o=t-n||0,i=Array(0>o?0:o);++r<o;)i[r]=e[n+r];return i}n.exports=t},{}]},{},["G9z0Bl"]);</script><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://tock.18f.gov/LeagueLookup">here</a>.</h2>
</body></html>
```

**Comment by mbland** [comment]
@jmcarp Looking...

**Comment by mbland** [comment]
Looks NewRelic-related: https://discuss.newrelic.com/t/what-is-bam-nr-data-net/13848/3

**Comment by mbland** [comment]
Whoops, my bad...scratch that. I just restarted the nginx instance and got:

```
404 Not Found: Requested route ('tock.18f.gov') does not exist.
```

Still looking...

**Comment by mbland** [comment]
Google searches for `requested route does not exist` turn up a bunch of Cloud Foundry-related results. I think the original IP address for tock-app.18f.gov must've gone away, and the original IP was reassigned to a completely different app; nginx must've been caching the original IP. Now that I've restarted nginx, it seems that maybe there's a CF setting restricting the allowed hostnames, hence why tock-app.18f.gov still at least returns a 403, but tock.18f.gov is rejected.

I could be talking complete garbage, but I don't know enough about Cloud Foundry to debug further right now.

**Comment by mbland** [comment]
OK, after a little more thinking and a little more reading, I thought to remove the `proxy_set_header Host $host` directives from the nginx configs, and Tock is happy again. I'll file a PR for the updated configs to close this issue.

**Comment by jmcarp** [comment]
Based on discussion with @mbland, I'm going to reopen, since reverting the `proxy_set_header` directives will bring back the unwanted redirects from `tock.18f.gov` to `tock-app.18f.gov` that we talked about a while back in #42 (which is why we added that directive in the first place). I also don't (yet) understand why the proxied header would cause the redirect we were seeing. I'll continue looking into this.

**Comment by mbland** [comment]
I think you mea #219.

**Comment by jmcarp** [comment]
Er, yes, must have pasted from the wrong buffer.

**Comment by mbland** [comment]
@batemapf just showed me that he got bounced back to tock-app after making some edits, which is part of why I think we needed the `proxy_set_header` directive. Is it possible that we can configure a CF route to recognize proxy requests for tock.18f.gov should go to tock-app.18f.gov?

**Comment by jmcarp** [comment]
Right, that's expected (but also bad), since we just reverted the fix for that behavior. Proxying the `host` header *was* the way we were letting the app know that redirects should go to tock.18f.gov. There may be another way to tell the app how to build redirects, but using headers seems like the right way to do it--if only we could get nginx to proxy to the right address.

I'm wondering if we should try the hack in https://www.jethrocarr.com/2013/11/02/nginx-reverse-proxies-and-dns-resolution/ and see if it helps.
