### ISSUE TITLE
Use “GSA” instead of “General Services Administration” again

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tock#229]
I'm almost certain that Tock used to use the acronym before; now, if you want to enter time under “General”, you have to scroll through every GSA-related entry because the acronym is fully expanded. It was better the old way.

**Comment by pkarman** [comment]
+1

**Comment by maya** [comment]
:100: It takes me forever to find it now.

**Comment by hollyallen** [comment]
+1
