### ISSUE TITLE
Autocomplete Projects

### ISSUE THREAD

**Issue by vzvenyach** [18F/tock#23]

**Comment by afeld** [comment]
Have implemented this a few times across 18F projects recently – happy to help. Also, might be useful to sort them by name, and/or doing grouped options (e.g. USCIS projects, general 18F stuff vs. client projects, etc.)

**Comment by seanherron** [comment]
Merging into meta issue https://github.com/18F/tock/issues/97

**Comment by NoahKunin** [comment]
woooo

and now @batemapf is going to hate me.

In order for autocomplete to work elegantly, we should never put strings together like `Ops/Acquisitions`. As a result, just starting to type `Acquisitions` won't bring up the proper category.

What's the process to change all of these to something like `Ops - Acquisitions`?

**Comment by seanherron** [comment]
We could go a step further and divide them in to optgroups, so 18F Operations is a group under which we have multiple line items or something.

**Comment by NoahKunin** [comment]
I just saw that functionality! Pretty slick. Makes sense. I just want to be sure it doesn't destroy all of 18F Finance's pivot tables...
