### ISSUE TITLE
As a user, I want to be able to easily find the tock line items I use most of the time

### ISSUE THREAD

**Issue by jgrevich** [18F/tock#230]
Suggested solution: provide an option to favorite projects

With so many line items it can be difficult to find the right one. It would be nice if there was an option to create a group of 'favorites' that are pinned to the top of the list; a history of the recent selections would also be helpful.

**Comment by cmc333333** [comment]
Brilliant idea!

**Comment by hollyallen** [comment]
+1 on this idea

**Comment by batemapf** [comment]
@jgrevich we have dramatically reduced the number of tock categories via #246.  has this made finding your projects easier? or is the option to favorite projects still needed?

**Comment by zacharycohn** [comment]
@batemapf I actually came here to suggest @jgrevich's issue. Having a list of favorites that pre-populate would remove a huge friction point for tock (and I imagine for people who context-switch a lot more, it would be a MASSIVE help). The reducing the number of options in tock doesn't seem like it really solves this for me. (for instance, I didn't notice the number of options was reduced, and still came here to suggest this feature)

**Comment by batemapf** [comment]
@zacharycohn for this feature, i suspect the mvp would be a static list of projects that you have logged _x_ hours against in the past _n_ time cards.  think that would be helpful?

**Comment by zacharycohn** [comment]
@batemapf Even if it was just "carry over all projects from last time period" by default or by hitting a button, that would be AWESOME.

**Comment by meiqimichelle** [comment]
Would anyone min if a re-named this issue? It seems to me that there could be other solutions to the core problem "I want to more easily find the things I bill to regularly", and that this is the core problem.

Suggested re-name: As a user, I want to be able to easily find the tock line items I use most of the time

**Comment by hollyallen** [comment]
That does sound like a nice user-centered way to put this.

**Comment by meiqimichelle** [comment]
I moved the original title to a suggested solution in @jgrevich 's original issue description. We've also had another suggested solution in Slack -- we could make most-used line items for each user 'float to the top' of the pick-list.

**Comment by hollyallen** [comment]
Any chance this could get done? I hear a lot about this feature request still.

**Comment by porta-antiporta** [comment]
@hollyallen wouldn't #308 solve this as well?  asking because that issue has been micropurchased and just recently merged to master.

**Comment by hollyallen** [comment]
Oh hey, that's pretty good. Not 100% of this feature request, but should definitely make things better! Thanks @porta-antiporta , I hadn't seen #308.
