### ISSUE TITLE
Admin Interface username/password?

### ISSUE THREAD

**Issue by dburr** [18F/tock#236]
Hi, I am wondering how I can access the admin interface? It asks for a username/password but the README doesn't mention one. I followed [these](http://www.djangobook.com/en/2.0/chapter06.html) standard directions on how to create an Django "superuser" account, however when I enter the account credentials in the admin page, it does not accept it. (I checked to make sure I typed the password in correctly) What am I doing wrong?

**Comment by batemapf** [comment]
@seanherron thoughts on this? i encountered the same issue when setting up tock locally per the README.

**Comment by ccostino** [comment]
@geramirez should me how to resolve this, I will submit a PR with some updates to the README instructions to help solve this issue.  There is probably a better way to fix this over the long term, but the solution works well with the current state of the project.
