### ISSUE TITLE
Add notes field to hours

### ISSUE THREAD

**Issue by cmc333333** [18F/tock#250]
Sometimes the categories in Tock aren't fine grained enough. It'd be handy to have a separate notes field to document a bit more thoroughly. I would _not_ expect this to be per pay period, instead per line entry within a pay period.

Example usage:
* 6 hrs on talent, "4 hours of prep, 2 of actual interviews"
* 20 hrs on projectA, "Mostly usability studies, and demos"

To be clear, I'd expect this to be an optional field

**Comment by ccostino** [comment]
This is actually addressed with #267; note (ha!) that I added support to enable this for any time entry, not just `General` time entries. :-)
