### ISSUE TITLE
As a user, I want the ability to view a message from administrators

### ISSUE THREAD

**Issue by hollyallen** [18F/tock#258]
As a tock user, I want the ability to view a message from the administrators as I'm filling out my timesheet. For example, this week the message might be: "If you took advantage of the early release on Wednesday Nov 25, enter those hours as Out Of Office. Thursday's Thanksgiving holiday should be entered as 8 hours of Out Of Office."

Success criteria:
* Tock users ask fewer questions in #tock and other channels.

**Comment by batemapf** [comment]
@hollyallen

**Comment by batemapf** [comment]
@hollyallen excellent idea.  the easiest solution (w/o making changes to the codebase beyond the message itself) is to drop updates [here](https://github.com/18F/tock/blob/master/tock/tock/templates/hours/timecard_form.html#L6).

of course, each update requires re-deployment of the app (no big deal, but still a step).

**Comment by hollyallen** [comment]
@batemapf I like that idea as a way to test and validate the usefulness of the request. Ultra-light MVP.

**Comment by batemapf** [comment]
@hollyallen tried this out with t-giving. see [original commit](https://github.com/18F/tock/commit/8db7418b4222ab67e3379249ae49836d6e5dedcc) and [tidying commit](https://github.com/18F/tock/commit/f77d823ed3fe08986ff6453c9e93d7395f7f9cca)

**Comment by hollyallen** [comment]
Looks great!
