### ISSUE TITLE
Layout improvement in the time report for individual project 

### ISSUE THREAD

**Issue by HuixianXu** [18F/tock#259]
As lead of finance, I would like to request improvements to layout of the time report for individual project. https://tock.18f.gov/projects/144/
Current layout is hard to read as we are having more and more time periods. It will be even better to have a total hour count at the bottom of each time period and total hour count at the right side for each employee. 
PLs also requested exporting data at a project level if possible.

**Comment by batemapf** [comment]
thanks @HuixianXu! the current state of affairs is really [scary!](https://github.com/18F/tock/blob/master/tock/tock/static/img/project_mess.jpg)

here is what i suggest:

(1) default to a view that displays only the last _x_ reporting periods;

(2) if a different view is desired, allow the user to select that view based on date ranges and the type of time period (week, month, year); and

(3) add a **Total:** to rows and columns.

**Comment by batemapf** [comment]
@vzvenyach @allalala @adelevie happy to break this up or add to it for MP purposes...

**Comment by allalala** [comment]
@batemapf ICWYDT. Let's chat re: specifics.

**Comment by HuixianXu** [comment]
Like @batemapf 's idea.
1. I suggest to use current quarter as default display to match with the billing cycle.
2. I agree that the type should include Fiscal Quarter, Month, Fiscal Year. For date range, I think it will be convenient to include an option to display all data since beginning of the project for multi-yr contract. 
Note that we use end of the week end day as indicator for month. Use Month to indicate quarter.
