### ISSUE TITLE
Change project name for talent related work

### ISSUE THREAD

**Issue by hestherchang** [18F/tock#260]
Talent Team wants to better capture how much time is spent interviewing, recruiting, and reviewing applications - separately. Currently, the only option for SMEs is "Recruiting/Interviewing". I'd like to replace that with the 3 below: 

Recruiting
Interviewing
Reviewing Applications 

Please let me know if this is possible and if it can be done sometime this week.

**Comment by batemapf** [comment]
done! created 
`Talent / Reviewing Applications`
`Talent / Interviewing`
`Talent / Recruiting`

**Comment by hestherchang** [comment]
Can you pls remove the "Talent /"? I'd like it to just be 

Recruiting
Interviewing
Reviewing Applications

so it doesn't get confused with the Talent team activities. The Talent Team activities start with "Talent / "

**Comment by batemapf** [comment]
@hestherchang i added in `Talent \` to provide the user a little more context for the activity, as well as make items easier to find when filling out a weekly time card.  we use a similar tag for `Ops \` things.  this doesn't mean that they are reserved for the ops team, only that they are ops-related tasks.

**Comment by hestherchang** [comment]
Ok makes sense. Thanks.

*H. Esther Chang*
18F Talent Team
U.S. General Services Administration
1800 F St NW, Washington, DC
202.503.6194
