### ISSUE TITLE
add in description for `general` time`

### ISSUE THREAD

**Issue by batemapf** [18F/tock#267]
is the ability to add notes to a line item in Tock a desirable feature? I always wish that I could add in notes about where specifically I spent my time in each category, particularly in General.

cc @theresaanna

**Comment by hollyallen** [comment]
Related: I would love if the tock categories had official descriptions themselves. What does the General category mean to 18F?

**Comment by batemapf** [comment]
@hollyallen many categories do (for instance, https://tock.18f.gov/projects/24/), but of course `General` does not (https://tock.18f.gov/projects/2/).  will filing an issue to get those with missing descriptions addressed

**Comment by hollyallen** [comment]
Oh that's great, I didn't know about that.

**Comment by batemapf** [comment]
refining this issue.  add the requirement to file a snippet for hours logged to the following categories:

`General`
`Consulting / General`

**Comment by ccostino** [comment]
@theresaanna:  I am going to take this on, so I am going to reassign it to me!  Please let me know if you're still interested! :-)
