### ISSUE TITLE
Suggested feature: point people with questions towards Projects page + include more info on Projects page

### ISSUE THREAD

**Issue by ethanheppner** [18F/tock#269]
Hey #tock team! Idea here: what if we changed the link to the Projects page on the menu here to
![screen shot 2015-12-11 at 12 24 21 pm](https://cloud.githubusercontent.com/assets/12718798/11751922/4e8501ce-a002-11e5-85d5-aff5f0c7980a.png)

"What project should I bill to?" 

It seems like people aren't sure where to ask questions about billing time to Tock, and pointing to the Projects page might give them some useful information if the projects page could have a column including "Project description" and "Project point of contact". There could also be a link to the #tock Slack group.

Just throwing out some ideas that Victor and I had, not sure if your user research supports them though.

**Comment by batemapf** [comment]
@ethanheppner catching up on issues! we have added in the project description field. we don't maintain point of contact information in tock, but we could certainly consider that as future addition. would definitely want to coordinate with @mtorres253 re: hub / team api / about.yml efforts to sync up (i know this info exists somewhere already...)
