### ISSUE TITLE
duplicate timesheets appeared in timecards_bulk.csv 

### ISSUE THREAD

**Issue by HuixianXu** [18F/tock#270]
Although we eliminated the possibility of user entering timesheet more than once, somehow duplicate timesheets still appeared in recent bulk time data. 

![screen shot 2015-12-14 at 9 35 11 am](https://cloud.githubusercontent.com/assets/15217277/11783777/f041b02a-a246-11e5-80e1-6c92e2a7d8b6.png)

**Comment by batemapf** [comment]
@HuixianXu have we encountered any duplication behavior lately?

**Comment by HuixianXu** [comment]
Didn't notice any recently.

On Tue, Feb 16, 2016 at 10:01 AM, Patrick Bateman <notifications@github.com>
wrote:

> @HuixianXu <https://github.com/HuixianXu> have we encountered any
> duplication behavior lately?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/issues/270#issuecomment-184716647>.
>



-- 

Huixian (Jackie) Xu
Finance Lead, 18F
U.S. General Services Administration
https://18f.gsa.gov/
