### ISSUE TITLE
get rid of `Billable` field in the bulk timecard endpoint

### ISSUE THREAD

**Issue by batemapf** [18F/tock#275]

**Comment by vzvenyach** [comment]
Why?

**Comment by batemapf** [comment]
we no longer use it for our calculations. not suggesting we change the data
model, just reducing the clutter here
<http://tock.18f.gov/api/timecards_bulk.csv>.

On Mon, Dec 21, 2015 at 11:41 AM, V David Zvenyach <notifications@github.com
> wrote:

> Why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/issues/275#issuecomment-166354510>.
>



-- 
Patrick F. Bateman
Operations Director
18F
U.S. General Services Administration
