### ISSUE TITLE
Move to cloud.gov rds-service

### ISSUE THREAD

**Issue by geramirez** [18F/tock#280]
Both the `DATABASE_URL` and `DJANGO_SECRET_KEY` were deleted. This is why we should move to the rds-service

**Comment by batemapf** [comment]
@geramirez is this still relevant?

**Comment by geramirez** [comment]
yes, but not doing it won't cause tock to fail.

**Comment by batemapf** [comment]
[here](https://github.com/18F/tock/compare/db-work?expand=1) is the work (my notes and steps are in the .rtf file, script is in other file). this uses `dumpdata` and `loaddata` mgmt commands via cf-ssh session to get data out of the old db and into the new db via json fixtures. not perfect by any means...

**Comment by batemapf** [comment]
good reference from @pkarman over [here](https://gist.github.com/pkarman/20f4a4a022a2c59e49bd96675e8101c3)

**Comment by batemapf** [comment]
this is closed via #456 and move to GovCloud
