### ISSUE TITLE
there's no way to delete a line

### ISSUE THREAD

**Issue by leahbannon** [18F/tock#284]
I added a line and then added another line and realized I needed to change/delete the first line. There's no way to do that. Leaving it blank or zero both return the error message "If you have a project listed, the number of hours cannot be blank."

Side note: Victor thought there used to be a type of blank field in the project dropdown list, but there isn't one.

**Comment by batemapf** [comment]
potentially could be handled by a "delete line" feature. will consider this for next round of features.

**Comment by jenniferthibault** [comment]
+1 Ran into the same problem today. 
I didn't mean to add a new project, I was just scrolling through the dropdown list to look for a project name, and stopped on it. Then, couldn't remove the entry, submit with "0," or submit a blank entry.

**Comment by porta-antiporta** [comment]
https://github.com/18F/tock/issues/308 Should address the ability to delete a line.  It's been auctioned.

**Comment by brendansudol** [comment]
With https://github.com/18F/tock/pull/323 now merged, you can now delete lines.
