### ISSUE TITLE
Gemnasium is reporting 5 security vulnerabilities for Django

### ISSUE THREAD

**Issue by monfresh** [18F/tock#286]
https://gemnasium.com/18F/tock

**Comment by monfresh** [comment]
Solution: upgrade to the latest version of Django.

**Comment by batemapf** [comment]
@monfresh latest non-development release of django is 1.8, which is what is tock is now using. thoughts on upgrading to the in-development version (1.9)?

**Comment by cmc333333** [comment]
@batemapf 1.9 is good for production, but I think the more pressing problem is that you're locked at 1.8 -- you should really be using the latest point release in that line (1.8.9)

**Comment by jgrevich** [comment]
Can this issue be closed with #312? It also looks like this duplicates #264
