### ISSUE TITLE
Make it easy to find categories for non-billable, non-project time categories

### ISSUE THREAD

**Issue by meiqimichelle** [18F/tock#297]
User story:  my bigger issue is that I have NO IDEA what all the non-billable categories available to me are, and there's no good way to figure it out most of the time. (and please don't say search, the tock autocomplete guessing game takes way too long.) I'd guess half of what I put under general might go somewhere else, and adding more non-billable categories without addressing the findability issue isn't going to help this at all. I dunno. is it just me? does anybody else suffer from this?

We have this: https://tock.18f.gov/projects/

Suggestion: One better would be if that table could be split into billable and non-billable, perhaps. Or is it something like “project” and “non-project” so the chunk of things y’all want us to use for ‘random office stuff’ is easily finable? It might even just be a special character or something in the name of the thing (so you don’t have to engineering anything). Like, if I could control-F through all the things with “@#$” in the title to read their descriptions and figure out what I should bill where, that would work.

**Comment by batemapf** [comment]
@allalala @adelevie this is a more interesting one for micropurchase because the acceptance criteria would be a bit broader than just "make this thing do that and verify it does so via a test".  instead it would be more like "does the solution resolve the stated user need?

**Comment by abrouilette** [comment]
@shawnbot, this might be of interest.
