### ISSUE TITLE
Display only active tock lines in the projects and activities page

### ISSUE THREAD

**Issue by ric7694** [18F/tock#305]
https://tock.18f.gov/projects/

**Comment by batemapf** [comment]
another one, @allalala @adelevie. this is a micropurchase candidate, with a twist. this is a very basic fix, so i'd like to start the bidding below the typical level.  let's talk.

**Comment by allalala** [comment]
@batemapf still interested in this for micropurchase? If so, I'm looping in @lauraGgit

**Comment by abrouilette** [comment]
@ric7694 , @batemapf , is this still a thing?

**Comment by batemapf** [comment]
how about we show all projects, but indicate whether or not they are active?
