### ISSUE TITLE
Micropurchase candidate: Load project/line items from previous week when opening a current week's timesheet

### ISSUE THREAD

**Issue by porta-antiporta** [18F/tock#308]
From week to week, chances are the projects a user is logging to changes very little.
However, currently when a new timesheet is opened, it starts out blank.
Users have to add in each line item again; and this often leads to people asking for a search function (search for "search" in #tock).  Search can be a pretty complex feature to develop.

If we come back to the original assumption: week to week projects a user logs time to changes very little; a natural enhancement is for the current timesheet to default with the projects from last week's timesheet when opened for the first time (rather than being blank).

*_Acceptance Criteria:_*

* When the user opens a **new** timesheet the timesheet is pre-populated with the previous week's projects.
 * Only the projects are carried over, the hours and snippets (for the General project) are blank.
* When the user opens a **saved** timesheet the timesheet does not pre-populate with the previous week's projects (i.e. the saved timesheet is not overwritten with last week's projects when re-opened)
*  A user can remove line items from an **unsubmitted** (i.e a new or saved) timesheet.  (One may argue scope creep here, but without the ability to delete a line item, this feature becomes unusable).
*  A user can add line items to an **unsubmitted** timesheet.  (This is current functionality that should be preserved).

**Comment by batemapf** [comment]
my concerns are over "autopilot".  do we run the risk of folks just submitting the same time over and over again without thinking critically about it? this could be tested, of course.  would like to hear others thoughts.  @ric7694 you've been spending a lot of time with the tock data, would like to hear from you as well.

**Comment by porta-antiporta** [comment]
I should clarify, it just imports the same projects.  But the *hours* are left blank.  I believe tock currently throws an error if there's a project line item with blank hours.

**Comment by porta-antiporta** [comment]
ping

Is there potential for this to become a micropurchase candidate?  Or should I close the issue?

**Comment by NoahKunin** [comment]
@porta-antiporta I'm thinking it's a perfect candidate for micro-purchase +1!

**Comment by batemapf** [comment]
let's give it a whirl.  @allalala @adelevie please add this one to the queue.

**Comment by porta-antiporta** [comment]
@allalala @adelevie in case micropurchases need a business case attached.

Back of napkin ROI (using survey data with [6 responses](https://docs.google.com/a/gsa.gov/forms/d/1Hc9IBOidYlzmJwel__itY1f_HGgbxTNDLWpWsHVLSIw/viewanalytics))
- 6 out of 6 prefer preloaded timesheets
- 5 out of 6 take anywhere from 1-5 minutes to search for projects each week.

Assumptions:
- $3500 cost to be recovered
- $150/hr billable rate
- 190 18Fers/PIFs that use tock
- 3 min average to find projects
- 0.5 min average to delete projects (case user wants to always start afresh)
- concerns about auto-submit was addressed by AC indicating that hours are zeroed out

Calculations:
($150/60) * (3-.5) * 190 = $1187.5 savings / week
Thus worst case is that cost of this micropurchase will be recovered within 3 weeks through saved productivity.

**Comment by batemapf** [comment]
:heart:

**Comment by adelevie** [comment]
:heart:

**Comment by allalala** [comment]
:us: :100:

**Comment by porta-antiporta** [comment]
Another AC to be added is:
* the mandatory snippet for the "General" project should be cleared when opening a *new* time sheet.

**Comment by brandocalrissian** [comment]
This one feature makes me wonder if micropurchasing rules will let 18F-ers bid $1 to complete this over the weekend.

**Comment by brandocalrissian** [comment]
We can't bid, but we can snipe it before it gets to the bidding stage. _sets bookmark..._

**Comment by brandocalrissian** [comment]
Further clarification about my comments above: https://twitter.com/18F/status/702884148696887299
(_"We had an internal miscommunication. To be clear, if it’s out for bids, we don’t work on it. Period."_)

**Comment by brendansudol** [comment]
PR submitted! (https://github.com/18F/tock/pull/323)

**Comment by brendansudol** [comment]
This PR was merged -- closing this issue.
