### ISSUE TITLE
Tock Project ID Format 

### ISSUE THREAD

**Issue by HuixianXu** [18F/tock#311]
Please revise the format of Tock project ID to include at least one letter. The current number only format often cause issues in google sheet/ excel functions. A fixed width text format with at least one letter is much preferred. Thanks!

**Comment by batemapf** [comment]
@allalala @adelevie this is a micropurchase candidate, with a twist. this is a very basic fix, so i'd like to start the bidding below the typical level.  let's talk.

**Comment by dsiddy** [comment]
@batemapf, no worries.  We could replace the [default](https://docs.djangoproject.com/en/1.9/topics/db/models/#automatic-primary-key-fields) [`AutoField`](https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.AutoField) with a [`UUIDField`](https://docs.djangoproject.com/en/1.9/ref/models/fields/#uuidfield) easily enough.  I'm happy to take care of it.

**Comment by abrouilette** [comment]
@batemapf, did this get taken care of?
