### ISSUE TITLE
Add "General" to new reports automatically

### ISSUE THREAD

**Issue by yozlet** [18F/tock#314]
Thanks to the current methods of searching, it's always a pain to find "General" (the 18F non-billable one) and yet pretty much everyone has to add it to their Tock report. So how about adding the (blank) entry automatically whenever I start a new report?

**Comment by NoahKunin** [comment]
Can you tell me more about this @yozlet? When I type "Gen", it comes right up.

**Comment by yozlet** [comment]
When I first open that dropdown, I get a list with 225 items in it. Typing "general" filters out less than half of them, and the "General" I want - that we _all_ want, every week - is somewhere in the middle.

**Comment by porta-antiporta** [comment]
Wouldn't this enhancement request be covered by https://github.com/18F/tock/issues/308?

**Comment by yozlet** [comment]
@porta-antiporta: Oops, I missed that. Yes, it would. If that's in process then we can close this.

**Comment by porta-antiporta** [comment]
@yozlet last i heard it was making its way to one of the upcoming micro-p auctions. #crossedfingersitmakesthecut

**Comment by batemapf** [comment]
https://github.com/18F/tock/pull/323 :-)

**Comment by batemapf** [comment]
need to test, but looking good thus far

**Comment by porta-antiporta** [comment]
#323 is live.  closing.
