### ISSUE TITLE
Tiny change: Change "Save" button label to "Save, but not Submit"

### ISSUE THREAD

**Issue by zacharycohn** [18F/tock#317]
People keep saving, thinking it's submitted. But it's not, and then they never circle back to submit. According to Ric, this has happened 20+ times since the "Save" feature was enabled.

Can we change the "Save" button label to "Save, but not Submit" (or something equally clear).

**Comment by batemapf** [comment]
how about some visual distinction b/w the buttons (space, colors) and change the wording to "save only"?

**Comment by zacharycohn** [comment]
Revision with @batemapf's advice: 

"how about hitting save takes you to a “thank you, but you still need to submit” page before dumping you back to tock main page?"

**Comment by batemapf** [comment]
i'm game for this. @MKathrynC any interest in taking this on?

**Comment by nicoleslaw** [comment]
+1 @batemapf

**Comment by batemapf** [comment]
addressed via #332
