### ISSUE TITLE
New Feature: Total Hours Billed on Reports Screen

### ISSUE THREAD

**Issue by joshuabailes** [18F/tock#320]
On the Tock Projects pages, we can see hours for 5 columns. It would be a helpful feature to also see the total number of hours billed to that tock project to date on this page as well.

So, for instance on https://tock.18f.gov/projects/195/ being able to see the total hours billed all time to date would be helpful in keeping up with labor burn rates, etc.

**Comment by batemapf** [comment]
closed via #331
