### ISSUE TITLE
Somehow 80 hours were recorded.

### ISSUE THREAD

**Issue by jpyuda** [18F/tock#327]
At the end of the day Friday, I filled out my Tock timesheet. (In Chrome, on Mac OS, in case that matters). I accidentally clicked "save", then remembered that "save" doesn't submit the timesheet and clicked "submit". I got the usual success screen.

I came back to Tock today (Monday) and noticed that last week's timesheet was listed as still being due. When I looked at it, I saw that 80 hours were included in the timesheet, and that it appears to have duplicated my timesheet last week and recorded every line on it twice.

![tock_bug](https://cloud.githubusercontent.com/assets/552095/13587782/820903d0-e498-11e5-88c9-dc0c6418e53c.png)

For now I'm going to hold off on submitting my timesheet just in case you need me to leave this as the current state for debugging.

**Comment by batemapf** [comment]
@adelevie want to bug bounty this one?
