### ISSUE TITLE
Cannot delete pre-populated projects with 0 hours, cannot submit timesheet

### ISSUE THREAD

**Issue by carodew** [18F/tock#338]
Description – 
– I cannot delete projects that have 0 hours on my timesheet that have been pre-populated. When I check those items and click save or submit, I receive an error that I cannot submit a timesheet with projects that have 0 hours (this happens when I leave the field blank and when I type in '0' explicitly) 

– when I put in 0.1 hours in those fields and adjust other fields accordingly to get to 40 (so I can submit anyway), I do not go to a confirmation screen, hence I don't know if I've successfully submitted my timesheet or not. 

– Update: was able to submit when I changed a dropdown that had no project specified to a project that I don't work on and logging 0.1 hour. 

I'm at a conference today and out Monday, so I may not be available to answer questions. 

Expected: 
– I would expect I can submit a timesheet with projects that have 0 hours and that the system will log them accordingly.

**Comment by hollyallen** [comment]
There is a delete check box next to the items, which I was able to use to remove rows that were used last week but not this week. But I think the error itself is totally bogus. If the hours add up to 40, why does the page care that there are blank rows?

**Comment by JenTress** [comment]
Having the same issue as @carodew. Cannot delete pre-populated rows (thus not allowing me to submit)

**Comment by JenTress** [comment]
Still having this issue, which is preventing me from submitting my timesheet. Screen shot here.
<img width="1280" alt="screen shot 2016-03-31 at 9 07 54 am" src="https://cloud.githubusercontent.com/assets/11888370/14176684/3a0563c2-f720-11e5-8ef2-3cdc8f66a8af.png">

**Comment by batemapf** [comment]
interesting. i believe @brendansudol pushed a change yesterday that would have addressed this, but maybe it didn't cover all cases. for now, a hack around this is to drop a `0` in all of the categories, check off the ones that you want to delete, and hit `Save`. that should allow you to delete the ones you don't want to carry forward.

**Comment by JenTress** [comment]
Thanks! That worked.

**Comment by brendansudol** [comment]
Thanks @JenTress -- I just tweaked it so that now you can save/submit entries with blank hours (those will become 0 upon submission). 

I think it's now safe to close this issue. :)
