### ISSUE TITLE
Allow for "Saving" Timesheets with rows with 0 hours (and "Submission" if low marginal cost)

### ISSUE THREAD

**Issue by porta-antiporta** [18F/tock#339]
When opening a new timesheet, last week's projects are loaded (woohoo!).

One usability improvement for those that fill their timesheet each day and save.
For a given week, I may be spending time across my 5-7 tock project entries. 
However, at the end of Monday, I may only have spent time on 2 of those projects.

Currently when I save my timesheet, an error is thrown for any project entries with 0 hours.
So I would have to delete those blank entries to save it, minimizing the value for #308 

Recommend that when *saving* a timesheet allow project entries with 0 hours.

If it's a low marginal cost; should also allow *submitting* timesheets with 0 hours.  If the backend system doesn't allow for 0 hr entries; strip those projects when sending it to the back end (rather than having a front end validation)

**Comment by jtag** [comment]
+1000 on this. Forces me to fake numbers on a Monday in order or categories to persists.

**Comment by jtag** [comment]
![screen shot 2016-03-28 at 10 40 26 am](https://cloud.githubusercontent.com/assets/339243/14084825/89f3dc02-f4d1-11e5-8ebb-025755258e3a.png)

**Comment by brendansudol** [comment]
I just submitted a PR to address this (allowing you to save/submit 0 hour entries). Blank hour inputs will still throw the validation error, but if you type in "0" and save or submit, it will work.

cc: @batemapf to review & merge

**Comment by hollyallen** [comment]
This feature in conjunction with pulling forward last week's projects have made filling out tock a breeze. Thank you so much!

**Comment by batemapf** [comment]
woohoo! thanks @hollyallen, the kudos go to @brendansudol!
