### ISSUE TITLE
As a user I would like to see the date range Im entering time for displayed on the main part of my screen so I can be sure Im entering time for the correct time period.

### ISSUE THREAD

**Issue by jtag** [18F/tock#340]
right now the only assurance is built into the url. 
with new feature pulling up last weeks' time categories the user needs assurance which time period they are entering is correct.

**Comment by batemapf** [comment]
deployed!

**Comment by jtag** [comment]
<heart>

On Fri, May 6, 2016 at 2:36 PM, Patrick Bateman <notifications@github.com>
wrote:

> Closed #340 <https://github.com/18F/tock/issues/340>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/issues/340#event-653181509>
>



-- 

Jesse Taggert
Strategist | 18F |  GSA

jesse.taggert@gsa.gov
cell: 415-730-4965
18F.gsa.gov
