### ISSUE TITLE
Is Chris Goransen's end date correct?

### ISSUE THREAD

**Issue by mtorres253** [18F/tock#343]
I'm pretty sure he's still at 18f. Is this correct? @OpenGlobe 
![screen shot 2016-04-05 at 1 38 16 pm](https://cloud.githubusercontent.com/assets/100149/14297494/d0f98f58-fb33-11e5-9c46-2ddb57fd3570.png)

**Comment by meiqimichelle** [comment]
Hehe, Chris is still at 18F @mtorres253 :)

**Comment by mtorres253** [comment]
So then this is a :beetle:

**Comment by batemapf** [comment]
corrected. these and #344 #345 are data validity issues, rather than bugs. all values are set by application users (non-admin users may alter their own data, admin users may alter data for all users).
