### ISSUE TITLE
Bug: previous week's time card projects autoloaded incorrectly

### ISSUE THREAD

**Issue by hollyallen** [18F/tock#347]
My timecard this week has previous week's time card projects autoloaded, yay! One of the projects is wrong though: I have never worked on "Transformation Services / Master Data Management Evaluation".

I've attached screen capture images of last week's timesheet and this week's unfilled out timesheet.

<img width="797" alt="last_week" src="https://cloud.githubusercontent.com/assets/3476681/14749818/7de4dff2-0876-11e6-9cdc-223ff38b8ec5.png">
<img width="779" alt="this_week" src="https://cloud.githubusercontent.com/assets/3476681/14749817/7dddd234-0876-11e6-81dc-f636339262b1.png">

**Comment by jgrevich** [comment]
Perhaps a project title was changed but the ID remained the same?
