### ISSUE TITLE
Sort Accounting Code Drop Down by Alpha

### ISSUE THREAD

**Issue by joshuabailes** [18F/tock#358]
When creating a project in tock, the accounting code must be selected. Presently, that list is not sorted by alpha, which makes locating the proper agency difficult, and leads to duplication of accounting codes. Would like to have that dropdown sorted by alpha.

**Comment by joshuabailes** [comment]
@batemapf @adelevie This something we could micropurchase?

**Comment by joshuabailes** [comment]
@batemapf Hey. Could we make this update? Consider this a candidate for micropurchase? cc @adelevie 

Picture of the drop down called "Accounting Code" that needs to be alpha. It is currently not ordered by alpha.

<img width="736" alt="screen shot 2016-07-05 at 5 40 52 pm" src="https://cloud.githubusercontent.com/assets/12254935/16600954/cd1266d0-42d7-11e6-8657-aa44459bb834.png">

**Comment by batemapf** [comment]
issue is that the accounting code is made up of two objects: the `agency` object and the `office` object. might be able to figure out how to sort by the this synthesized super object, but might be easier to just sort by `office` or `agency`. preference?

**Comment by joshuabailes** [comment]
Agency is my preference, and if secondary sort on office object, then perfect. But Agency object is the preference as that is always required for every agreement, but office may not be required.

**Comment by batemapf** [comment]
@joshuabailes just deployed this fix. this is like a 50% fix. acct codes are grouped, but alpha is applied oddly. should improve usability, but keep this issue open if it is not sufficient.

**Comment by joshuabailes** [comment]
@batemapf Looks good to me. Thank you!
