### ISSUE TITLE
Create API documentation

### ISSUE THREAD

**Issue by jessieay** [18F/tock#363]
Hello --

a few API questions

1. Where is "Tock" in the list of projects? Viewed every page available and do not see it https://tock.18f.gov/api/projects.json but it is listed at https://tock.18f.gov/projects/

2. Are there API docs somewhere? Trying to figure out who I can up the number of records per page. Seems like there's a way but I am not fluent in python. English docs would be much appreciated!

**Comment by jessieay** [comment]
ps - this is for use in Micropurchase. We are going to populate the "billable to" field in the auctions#new form with data from the Tock API. Excited to use it!

**Comment by batemapf** [comment]
@jessieay `Tock` may not be showing up from api/projects.json b/c of page limits. i believe projects.json is limited to 100 lines until you have send a ?page=2 variable.

only api documentation that exist are in the `README.md` file in the root.

i wrote a little ditty to automatically pull the next page of data which dealt with the problem nicely. now i just need to find it...

**Comment by batemapf** [comment]
ah, looks like that was for something completely different (the Lever API, which has similar pagination issues).

i am going to go ahead and see if i can't kill the pagination for projects. back soon.

**Comment by jessieay** [comment]
@batemapf yeah I saw the page stuff and looked at every page but the Tock project was nowhere to be found!

Killing pagination would be fine. Or, allowing higher page limits would also work (default to 100, but allow up to 1000 or something)

**Comment by jessieay** [comment]
Hi @batemapf - any update on this? We are trying to use the Tock API for a feature in Micropurchase so any leads on how I can help myself to use it would be awesome.

**Comment by abrouilette** [comment]
@jessieay, we're spinning up a Tock team.  Is this still a need?  (I don't speak API very well.)

**Comment by jessieay** [comment]
yes, this is still a need. related: https://github.com/18F/tock/issues/391#issuecomment-235320070

**Comment by jessieay** [comment]
High level summary of this item: Tock API needs documentation

**Comment by batemapf** [comment]
@jessieay is this one OK to close?

**Comment by jessieay** [comment]
Yes, looks like docs are here https://github.com/18F/tock/tree/master/api-docs
