### ISSUE TITLE
broken link to Travel Request

### ISSUE THREAD

**Issue by zacharycohn** [18F/tock#364]
https://handbook.18f.gov/travel-guide-1-authorization/ links to https://handbook.18f.gov/travel-guide-1-authorization/tock.18f.gov/employees/yourFirstName.yourLastName/travel_request, which is obviously incorrect. I fixed it and replaced the default name with mine, but it still 404s.

**Comment by batemapf** [comment]
thanks @zacharycohn. looked into it, seems like the travel guides are ahead of Tock functionality ;-). see https://github.com/18F/handbook/commit/a11d1f5f6284d4599592b8b89d3d380f2348b320#commitcomment-17816312

**Comment by abrouilette** [comment]
@batemapf, @zacharycohn, is this still a thing?

**Comment by zacharycohn** [comment]
it does not appear to still be a thing.
