### ISSUE TITLE
search not returning results from multi-word queries

### ISSUE THREAD

**Issue by zacharycohn** [18F/tock#367]
When I search for "child," a bunch of entries appear for " Acquisition Services / State Child Welfare / ...".

But if I search for "child welfare" or "state child welfare", there are no results.

**Comment by carodew** [comment]
This also caused me grief today.

**Comment by zacharycohn** [comment]
Had this problem again when searching for "Out of office", which returns nothing in the search results.

**Comment by ccostino** [comment]
All fixed as of PRs #662 and #664!
