### ISSUE TITLE
Tock prefills 8 hrs OOO for known holidays

### ISSUE THREAD

**Issue by mtorres253** [18F/tock#368]
As a ops ninja, I don't want to waste time chasing people around when they forget to set 8 hours OOO for known holidays (because I have better things to do). So when those holidays are known, they system should automatically prefill this in their time cards

Scenario: Holiday time is prefilled 8 hours OOO in a timecard
Given I am an employee
And I'm reporting my time for a week that contains a Federal holiday
When I navigate to the time reporting form https://tock.18f.gov/reporting_period/[date]/
Then I should see Out of Office - Administrative/Holiday Leave already selected
And I should see '8' as the value for the Hours input

**Comment by abrouilette** [comment]
+1 and: 

<img width="549" alt="screen shot 2016-06-28 at 12 26 02 pm" src="https://cloud.githubusercontent.com/assets/15253491/16425732/91c07d8a-3d2b-11e6-8d4f-353e670d5bbd.png">

**Comment by abrouilette** [comment]
Closing this one as a (depressingly aged) double entry.
