### ISSUE TITLE
Some HTTP clients are confused by Tock's JSON encoding

### ISSUE THREAD

**Issue by toolness** [18F/tock#371]
This is a long story.

Basically, Django REST Framework, which powers Tock's API, doesn't include a `charset` parameter in its `Content-Type` header because doing so [is not actually part of the JSON spec](http://lucumr.pocoo.org/2013/7/19/application-mimetypes-and-encodings/).

However, some clients (most notably Chrome's built-in JSON renderer) expect there to be a `charset`; if there isn't, then they often mis-interpret JSON data.

Ideally the solution would be to tell Django REST Framework to include a `charset` parameter to satisfy these clients, but its creator [refuses to because it's not part of the specification](https://github.com/tomchristie/django-rest-framework/issues/2891).

Because of this, I've tended to simply set `UNICODE_JSON` to `False` to avoid the issue altogether--this setting tells Django REST Framework to simply take advantage of the JSON specification's `\u` escape sequence to deliver all JSON content as ASCII while still allowing unicode to be transmitted. While this can also increase payload sizes if they contain lots of non-ASCII characters, Tock's data seems to be mostly ASCII, so it shouldn't bloat things too much.

If this sounds like a decent enough solution, I'm willing to submit a PR for it.

Related: https://github.com/18F/api-standards/issues/68

**Comment by batemapf** [comment]
ran this locally and the example cited [here](https://18f.slack.com/archives/tock/p1465845674000130) now returns the value:  `"Working on branding for 18F\u2014internal branding\r\n"` instead of `"Working on branding for 18Fâ€”internal branding”` (which in english is `Working on branding for 18F—internal branding`)

that work, @jessieay?

**Comment by jessieay** [comment]
that works! I mean ideally it would put out a string that is literally what it should be (eg: `-` instead of `\u2014`) but utf-8 is def better than non-utf-8!

**Comment by batemapf** [comment]
👍 will merge and deploy!
