### ISSUE TITLE
alerts stacking up!

### ISSUE THREAD

**Issue by batemapf** [18F/tock#379]
<img width="948" alt="screen shot 2016-06-17 at 6 00 37 pm" src="https://cloud.githubusercontent.com/assets/7645362/16166010/70cb5ea2-34b5-11e6-8efb-d7fc34755997.png">

as a user, when i select one project that has an alert, but then change my project to another that also has an alert, the first alert does not clear.

**Comment by batemapf** [comment]
in the screen shot, the `Please remember to request...` and `If the federal...` notices are two separate alerts.

**Comment by ccostino** [comment]
D'oh!

**Comment by ccostino** [comment]
This should be fixed in #400. :-)
