### ISSUE TITLE
Project numbers mentioned but not available

### ISSUE THREAD

**Issue by toolness** [18F/tock#380]
This is odd... We added autocomplete-by-project-number in #360 and tock.18f.gov currently advertises the feature, but it doesn't actually seem to be available:

<img width="767" alt="screen shot 2016-06-20 at 10 11 47 am" src="https://cloud.githubusercontent.com/assets/124687/16197427/0d4a2aa8-36d0-11e6-893c-1053a65050ec.png">

The "General" entry should really be "2 - General", I think, since the Project ID of General is 2.

**Comment by batemapf** [comment]
@toolness checked `master`, everything you added via #360 is in there... there were not changes to any `models.py` so i don't think it is a migrations issues. the mystery of tock continues!

**Comment by batemapf** [comment]
oh and got rid of the "new feature added..." message re: #360 because, well, it is a lie!

**Comment by ccostino** [comment]
Wait, what?  I was always told numbers don't lie!  Are you saying I've been mislead all this time, @batemapf!? 😆
