### ISSUE TITLE
burn rate alert not clear about which project it corresponds to

### ISSUE THREAD

**Issue by afeld** [18F/tock#399]
This feature is great—just saw it for the first time! My only feedback is that it isn't clear whether it corresponds to the project above or below. Increasing the whitespace above/below or putting a border around the warning+field would help.

<img width="638" alt="Tock screenshot" src="https://cloud.githubusercontent.com/assets/86842/16735133/0197830e-4756-11e6-80d3-6680e468dbfe.png">

**Comment by ccostino** [comment]
@afeld:  I'm going to generalize this a bit and say that the alerts themselves are not clearly associated with the line item they're intended for.  They are meant for the line item above them. :-)

I'll work on getting some visual cues in place at some point to address this, thanks for pointing it out!
