### ISSUE TITLE
sort pulldown for project

### ISSUE THREAD

**Issue by janearc** [18F/tock#40]
this field is cumbersome to look through because it's unsorted
![screen shot 2015-04-06 at 08 29 21](https://cloud.githubusercontent.com/assets/777319/7005642/36fc5d3e-dc37-11e4-890b-1a8057f0fe9f.png)

**Comment by seanherron** [comment]
How should it be sorted?

**Comment by mbland** [comment]
Could it be sorted alphabetically, either server-side or client-side?

**Comment by seanherron** [comment]
Another suggestion would be to use `optgroups`, maybe split by client?

**Comment by janearc** [comment]
Alphabetically seemed like the right way to go; I didn't know how to find 'Unbillable' or whatever it was in the excel timesheet. What other column might we sort it on?

**Comment by seanherron** [comment]
Merging into meta issue https://github.com/18F/tock/issues/97
