### ISSUE TITLE
non-admins can modify any of their own previous tock entries by directory traversal

### ISSUE THREAD

**Issue by jgrevich** [18F/tock#401]
I discovered this by directory traversal/url hacking while adding entries after vacation. I thought it may have been a new feature but apparently that's not the case: https://18f.slack.com/archives/tock/p1468438477000711

It also appears that these changes make their way into the google sheets: https://18f.slack.com/archives/tock/p1468442537000720

**Comment by tbaxter-18f** [comment]
This is long resolved, isn't it @ccostino ?

**Comment by ccostino** [comment]
I'm not sure on this, it'd be good to investigate to double check!

**Comment by tbaxter-18f** [comment]
I can't replicate it. I think it was fixed a long time ago. Closing.
