### ISSUE TITLE
Tock not saving my time or recording my entries

### ISSUE THREAD

**Issue by jtag** [18F/tock#402]
halp. I either entered my time last Friday OR had been keeping track of it as saved. Last week currently presents itself as not entered and completely blank for the hours of week. I had been saving. 

^^ also brings up the point that there is not way for me to see recent entries or total confident confirmation that I entered time. I especially feel that pain when I entered it and it presents as blank as if I had not done anything.

**Comment by jtag** [comment]
for real. Doing this again. but I know for certain I saved my hours last week and 99% sure i also submitted them. Redoing them again. In the future I'll take a screenshot as proof.

**Comment by jtag** [comment]
If anyone exploring this. Last Fri Jul 15th for sure I entered, saved, and submitted my hours. I just re-did them today July 18th. 

Using Chrome on Mac.

**Comment by cydharrell** [comment]
I experienced the same, and have before, but Jesse's report alerted me that it's not some local issue. Last Friday 7/15, I had saved (I think) 38 hours but came back to under 20 on Monday 7/18 and had to reconstruct. Also Chrome on Mac. Tab left open, but computer barely touched over the weekend.

**Comment by abrouilette** [comment]
@jtag, @cydharrell, is this ongoing?

**Comment by cydharrell** [comment]
Actually no, it's not - thanks for asking!
