### ISSUE TITLE
Allow editing of submitted timecard

### ISSUE THREAD

**Issue by jpyuda** [18F/tock#41]
I submitted a partially-complete timecard. When I went back to edit it, I had to start from scratch instead of being able to make changes.

Allowing the editing of a partially-complete timecard until some deadline will make it easier to correct errors and can also allow users to enter their time on a daily basis so they don't have to think through a whole week at the end.

**Comment by seanherron** [comment]
This is actually a bug meaning that your timecard may not have been saved successfully, related to #43 and #44.

**Comment by seanherron** [comment]
This is now fixed. Thanks for the bug report @jpyuda!
