### ISSUE TITLE
Exporting hours billed per week per person for a specific project

### ISSUE THREAD

**Issue by zacharycohn** [18F/tock#414]
I need this data to give some numbers to the client. @ccostino confirmed none of the JSON endpoints were going to work. 

Ideally, there'd be an "export to csv" button on each project page that would export all the people who billed, each week there is data, and the number of hours that person billed that week.

The only way I can find to do this right now is to go through all of the weekly reports and look at every individual person's timecard for every week, which is a non-starter.

**Comment by batemapf** [comment]
@zacharycohn mind sketching out visually want you want to see? or dropping a dummy .csv file in here of the way you would like the data structured? or drawing it on a napkin?

**Comment by zacharycohn** [comment]
Output would look like: 

<img width="420" alt="screen shot 2016-08-12 at 12 26 02" src="https://cloud.githubusercontent.com/assets/614963/17629345/d648e59e-6087-11e6-8920-c090a58f7e69.png">

**Comment by batemapf** [comment]
would be a teensey bit easier to set it up like this (but would meet your needs less):

employee_name,reporting_period_end_date,hours_spent
Jack Sparrow,8/12/85,17
Jack Sonfive, 8/12/85,39
etc..

that workable?

**Comment by batemapf** [comment]
...limited to a specific project, of course.

**Comment by zacharycohn** [comment]
It definitely would require the user to massage the output a little bit, but it does have all the data a user would need.
