### ISSUE TITLE
add /data page 

### ISSUE THREAD

**Issue by gbinal** [18F/tock#415]
There's a ton of links for exporting data that many folks might not know about.  I'd suggest adding a `Data` link in the sidebar, going to tock.18f.gov/data and that lists out the various endpoints and bulk data links.  

If there's interest in this, I can try to file a PR.

**Comment by batemapf** [comment]
great idea @gbinal. going to take a look at your PR, might push some additional commits up, as well.

**Comment by batemapf** [comment]
closed via #413
