### ISSUE TITLE
Negative Hours

### ISSUE THREAD

**Issue by thecapacity** [18F/tock#424]
Likely hours shouldn't be negative but I found myself in that situation (luckily I caught it before submitting). I believe I: Clicked on the page and tried to scroll (with the touchpad) - probably in clicking I clicked in an hours data-entry box - so when I tried scrolling the page up/down it started making my hours positive/negative.

**Comment by batemapf** [comment]
@ccostino sounds like another form validation project!

**Comment by ccostino** [comment]
Sounds like an odd client-side bug, too. :-)

**Comment by thecapacity** [comment]
I believe an appropriate fix (based on the generated page I see) would be to change (whatever generates);
`<input id="id_timecardobject_set-0-hours_spent" name="timecardobject_set-0-hours_spent" step="0.01" type="number" />`

to
`<input id="id_timecardobject_set-0-hours_spent" name="timecardobject_set-0-hours_spent" step="0.01" type="number", min="0"`>`

i.e. add the HTML form specifier; `min="0"`

Unfortunately, I was not able to find where in the code these are generated.

Interesting to note this (non-active code) from: `tock/hours/forms.py`:
```
# For another day :-). Changes step increment in Hours Spent field.
#    )
#    hours_spent = forms.IntegerField(
#        widget=forms.NumberInput(attrs={'step': '0.25'})
#    )
```

Note the step is `.25`, which is different than the current `.01`

Also the fix may include updating the serializer for `DecimalField(...)` to include `max_value` and `min_value`

Sorry I couldn't submit a PR too!
