### ISSUE TITLE
Holiday Prefills

### ISSUE THREAD

**Issue by abrouilette** [18F/tock#426]
As a filler-out of Tock, I would like to have Federal holidays pre-filled in my timecard so I don't forget and have to ask for corrections.

As an administrative user of Tock, I would like employees to have Federal holidays pre-filled in their timecards so I don't have to squander a bunch of time when they ask for corrections.

**Comment by abrouilette** [comment]
@sfvictor, how much time would you say you spent on corrections for those who forgot Columbus Day/Labor Day?

**Comment by sfvictor** [comment]
uh too much time.  But truly, at least two to three hours, including time on Friday even though the holiday was on that Monday.  Can we ensure this is the first entry because I know folks see it, and make the connection.
