### ISSUE TITLE
Can't submit a timesheet

### ISSUE THREAD

**Issue by cmc333333** [18F/tock#44]
When I try, I get an error about adding up to 100%
![screen shot 2015-04-06 at 9 43 33 am](https://cloud.githubusercontent.com/assets/326918/7005830/9406a6e2-dc41-11e4-94b0-b06f2da39f2f.png)

Click Submit

![screen shot 2015-04-06 at 9 43 44 am](https://cloud.githubusercontent.com/assets/326918/7005832/97337a66-dc41-11e4-8ab5-ffe25435eaa6.png)

**Comment by vzvenyach** [comment]
@cmc333333 As a temporary fix, can you put 0 for the project you want to delete?

**Comment by cmc333333** [comment]
I think that comment goes on #43 not here?

**Comment by cmc333333** [comment]
This was resolved with #52

**Comment by seanherron** [comment]
Thanks @cmc333333!
