### ISSUE TITLE
EM/PM approval

### ISSUE THREAD

**Issue by batemapf** [18F/tock#444]
allow EM/PMs to view and "approve" the prior week's time entries against their project. will probably require (off the top of my head):
1. a new "approval" form, with dependencies on TimecardObject, Project, ReportingPeriod, and User classes;
2. addition of an "approved" boolean attribute to the TimecardObject class;
3. addition of "allowed approvers" foreign key attribute to the Project class;
4. update API views to dump approved T/F data with existing views;
5. new list view that displays outstanding approvals to users listed as "allowed approvers" for any project (like the "timecards you need to fill out" view)
6. tests all around!

cc @joshuabailes

**Comment by HuixianXu** [comment]
On the form, the PM should be able to click the username of a staff and see the complete timesheet to evaluate the "availability" of the staff in the week.
