### ISSUE TITLE
Remove repetitive layout for /tock/timesheet/<time-period/ url

### ISSUE THREAD

**Issue by juliaelman** [18F/tock#45]
**Issue**
Currently, the page duplicates the fields when adding a new project to your timecard. 

**Fix**
Remove "Project", "Billable" and "Time Percentage" per added set of project fields, see screenshot below for reference.

![screen_shot_2015-04-06_at_11_13_31_am](https://cloud.githubusercontent.com/assets/955558/7006448/3bb637d8-dc4f-11e4-90a1-2088095dee7a.png)

**Comment by seanherron** [comment]
I'm not sure how to do this while remaining 508 compliant. @nickbristow can we hide the labels on subsequent items while keeping the association somehow?

**Comment by juliaelman** [comment]
Yes! We should definitely still have the labels for accessibility, but they can also be hidden. See examples of three different approaches outlined here: http://www.w3.org/WAI/tutorials/forms/labels/

@nickbristow would love to get your input on this article too and if this is something that is okay to move forward doing.

**Comment by nickbristow** [comment]
Oh yeah definitely hiding things in the label tag is a long standing
tradition for accessibility. If its just there for screen readers, go for
it.

Nick Bristow
18f <http://18f.gsa.gov> Innovation Specialist
Nick.Bristow@gsa.gov

**Comment by juliaelman** [comment]
@nickbristow awesome - thanks for the confirmation! :+1:
