### ISSUE TITLE
Feature: Make budget data available in API

### ISSUE THREAD

**Issue by adelevie** [18F/tock#467]
For micro-purchase, it would be helpful to know if the cost of micro-purchases remains below the assisted acquisitions threshold. We've been good about manually verifying this (and many micro-purchases won't even be close to that threshold) but it would be even better to automagically verify compliance.

**Comment by batemapf** [comment]
@adelevie we don't currently have project budget data in tock which, if i am reading this right, would be necessary to build out to address this issue. that sound about right?

**Comment by adelevie** [comment]
Seems right! It would be cool to have a web service returning budget info that Tock can talk to. At least that's the dream.

**Comment by batemapf** [comment]
We can all dream, @adelevie.
