### ISSUE TITLE
Add ability to remove project lines once added to timesheet

### ISSUE THREAD

**Issue by juliaelman** [18F/tock#47]
**Issue** 
Once you have added a project line item to a timesheet, there is not way to remove it.

**Fix**
Add ability to remove a project line item from timesheet once it has been added.

**Comment by seanherron** [comment]
I think this has been rectified, you should just be able to select `----` in the dropdown and it will be removed on form submission. Does that work?

**Comment by juliaelman** [comment]
@seanherron it would be nice to have some more explicit, like a minus button or something. As labeled, this is more of an enhancement and something I'll leave up to the core team to determine whether or not it's a necessary addition :smile:

**Comment by seanherron** [comment]
Merging into meta issue https://github.com/18F/tock/issues/97
