### ISSUE TITLE
General Snippets Report

### ISSUE THREAD

**Issue by joshuabailes** [18F/tock#471]
I'd like to create a report to show the 
- employees who tocked time to general 
- their hours for that week to general
- and their snippets for that activity

**Comment by joshuabailes** [comment]
@batemapf

**Comment by joshuabailes** [comment]
just checking in on this. timeline? @abrouilette

**Comment by batemapf** [comment]
@abrouilette where does this fall in the @joshuabailes priorities?

**Comment by abrouilette** [comment]
First, as of 11/22.
