### ISSUE TITLE
Output employee utilization rate in API

### ISSUE THREAD

**Issue by joshuabailes** [18F/tock#472]
Would like to incorporate a Utilization Rate into Tock reporting.
1. UR is calculate as (billed hours) / hours worked  - OOO. This would apply to employees that can bill only.
2. This reporting structure would need to be surfaced in a report that managers can access (or anyone for that matter).
3. I'd like as the perosn enters their time into Tock they have a UR calculator that updates with a target of 80% Utilized and the ability to change that target in admin panel.
   @batemapf

**Comment by joshuabailes** [comment]
@abrouilette Any projected timeline? I am asking in a couple of issues and you may have a backlog prioritized somwhere and I just don't know where.

**Comment by abrouilette** [comment]
@joshuabailes: We would either need you to drop into tomorrow's sprint planning for a half hour or for you to spend a half hour with me beforehand, to prioritize.  (Which would delight me.)  Also talking to a researcher today, so we can get rolling on the big buy-or-build question.  You might get all the reports you ever dreamed of :)

**Comment by abrouilette** [comment]
@batemapf, per Bailes this is the top need.  

@joshuabailes, for the individual only? Also: Do we make consideration for how billable that staffer is supposed to be? (i.e., supervisors and Guild leaders are less than 32 hours a week, I believe.)

**Comment by joshuabailes** [comment]
Alan,

No. I think that when we pull the data the reviewer should know how
billable the person should be. We just need the data.

Joshua Bailes
18F Acting Director of Operations
Joshua.Bailes@gsa.gov
202-550-6659
18F.gsa.gov <https://18f.gsa.gov/>

**Comment by abrouilette** [comment]
@batemapf, how we coming here?

**Comment by batemapf** [comment]
@joshuabailes for #3 in your original message, do you want a flat 80% target for everyone, or do you want to use their assignments in Float?

**Comment by joshuabailes** [comment]
@batemapf I think we need both. Something related to Float, but also a target for UR that can be adjusted for groups of folks will be helpful. In particular, I am thinking for those fully billable, partially billable, and exception billable.

**Comment by joshuabailes** [comment]
@abrouilette @annalee Is this ready for production? Need it live ASAP.

**Comment by annalee** [comment]
Hi @joshuabailes, Unfortunately the tests are failing: https://github.com/18F/tock/pull/495 so it's not ready to push yet. I'm in back-to-back meetings from 11:30 onward but I'll see if I can get this up for you today.

**Comment by batemapf** [comment]
@joshuabailes is this addressed in the [utilization report](https://tock.18f.gov/utilization/)?

**Comment by joshuabailes** [comment]
I believe so.

Joshua Bailes
18F Acting Director of Operations
Joshua.Bailes@gsa.gov
202-550-6659
18F.gsa.gov <https://18f.gsa.gov/>

**Comment by batemapf** [comment]
💥
