### ISSUE TITLE
Document the API

### ISSUE THREAD

**Issue by adelevie** [18F/tock#474]
cc @rememberlenny

**Comment by jessieay** [comment]
see https://github.com/18F/tock/issues/458 as well :)

**Comment by adelevie** [comment]
oh nice! lotta good info there!

**Comment by batemapf** [comment]
updated README in latest [commit](https://github.com/18F/tock/commit/30dce2c000606d77d43fa888ce37e6f6811003a0#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by adelevie** [comment]
Looking better, but the HTTP request methods and response schema/samples should also be here ... loving the progress!
