### ISSUE TITLE
Don't make me enter a snippet for General to save my entries

### ISSUE THREAD

**Issue by rdpiazza** [18F/tock#485]
To reproduce:
1) Open a fresh week's Tock entry, where "2 - General" is one of the prepopulated entries
2) Add hours to an entry other than "2 - General".
3) Click Save
4) I receive an error saying my changes cannot be saved without entering a snippet for "2 - General"

I don't want this validation to trigger until (simpler) I click Submit or (more complicated) I enter hours for "2 - General" and Save.

**Comment by batemapf** [comment]
closed via #560
