### ISSUE TITLE
Still cannot see other employee reports

### ISSUE THREAD

**Issue by hollyallen** [18F/tock#486]
Although #218 is marked as closed, I receive a 403 error when viewing another user's report.

**Comment by batemapf** [comment]
Strange. Would you mind dropping in your target URL that is returning the 403?

**Comment by hollyallen** [comment]
for example: https://tock.18f.gov/employees/patrick.bateman/

**Comment by batemapf** [comment]
being addressed in #492 :-)

**Comment by batemapf** [comment]
ok #492 is merged and live. enjoy!

**Comment by hollyallen** [comment]
Yay, I can see other people's tock data now! Excited as only a manager can be.

**Comment by batemapf** [comment]
If there are additional slices / views of employee data that you would be interested in seeing as a manager, don't hesitate to file an issue 😄
