### ISSUE TITLE
My employee report graph is empty

### ISSUE THREAD

**Issue by hollyallen** [18F/tock#487]
When I view my individual tock report, the graph is empty:

![screen shot 2016-09-26 at 2 38 52 pm](https://cloud.githubusercontent.com/assets/3476681/18852827/1cf5c8da-83f7-11e6-9939-c84734db7b22.png)

**Comment by batemapf** [comment]
Please check it out now. Should be fixed!

**Comment by hollyallen** [comment]
Confirmed!
