### ISSUE TITLE
Add hours expected to work [mockups]

### ISSUE THREAD

**Issue by maya** [18F/tock#499]
Here are some mockups of what it could look like to have inline error messaging around hours worked.
## Mockup 1

![error-1](https://cloud.githubusercontent.com/assets/5249443/19002064/268ef654-86ff-11e6-8914-a87768448965.jpg)
## Mockup 2

![error-2](https://cloud.githubusercontent.com/assets/5249443/19002068/2bdd9cdc-86ff-11e6-953f-0315172d0fb1.jpg)
## Mockup 3

![error-3](https://cloud.githubusercontent.com/assets/5249443/19002070/2d2844e8-86ff-11e6-854e-bde612f61449.jpg)
## Mockup 4

![error-4](https://cloud.githubusercontent.com/assets/5249443/19002280/1f39291e-8700-11e6-9f70-2c6f1d123b3f.jpg)

I know it's not an error, but more of a warning so we can keep playing with this.

/cc @shawnbot @abrouilette @batemapf @annalee

**Comment by maya** [comment]
Here are some success options:

## Success 1
![success-1](https://cloud.githubusercontent.com/assets/5249443/19002837/cb54843a-8702-11e6-86cf-11c59856a2b4.jpg)

## Success 2
![success-2](https://cloud.githubusercontent.com/assets/5249443/19002838/cc5a9022-8702-11e6-8b45-cba3a912c48c.jpg)

**Comment by lauraGgit** [comment]
Please rename this to `Add hours expected to work [tockups]`.

**Comment by maya** [comment]
Another help-text style. This would be more general and we could use this for a variety of types of information.

![help-text](https://cloud.githubusercontent.com/assets/5249443/19057313/c45f9588-8983-11e6-8cd8-bd641c33cd11.jpg)

**Comment by vzvenyach** [comment]
FWIW, I would personally caution against using something more than some kind of "help text" style here. I think that a user prompt that indicates user error for something that is not reflected in Float, while well intentioned, could have other bad consequences. As a manager, I would _much rather_ receive a report that reflects disparities between Float and Tock data than having users of Tock enter data in a way to avoid red outlines/get green outlines.
