### ISSUE TITLE
Aloha affirmation when Tocking to OOO

### ISSUE THREAD

**Issue by abrouilette** [18F/tock#501]
As a recorder of hours in Tock, I would like to be reminded that I must also enter certain types of OOO hours in ALOHA, so Ops isn't mad at me later.

As an administrator of Tock, I would like users, when Tocking OOO hours of relevant type, to affirm that they have also entered those OOO hours in ALOHA, so I don't have to chase them later.

**Comment by abrouilette** [comment]
@sfvictor, @joshuabailes, I get all the phrasing right, here?

**Comment by joshuabailes** [comment]
@abrouilette Yes.

**Comment by batemapf** [comment]
This should be able to be handled via the existing alerts feature. Will take a look.

**Comment by batemapf** [comment]
Already set up, in fact:

<img width="678" alt="screen shot 2016-10-05 at 12 56 43 pm" src="https://cloud.githubusercontent.com/assets/7645362/19123165/99559ac6-8afb-11e6-9d67-d9ca8cc4c721.png">

Are you looking for something else?

**Comment by batemapf** [comment]
Ah, the second part, re: the Administrator...

**Comment by abrouilette** [comment]
Yessir. Would it be a great challenge to change "Please remember..." to " [ ] I have requested..." ?

**Comment by batemapf** [comment]
That would be a bit of work @abrouilette. where does this fall in the @joshuabailes priorities?
