### ISSUE TITLE
add timestamp

### ISSUE THREAD

**Issue by batemapf** [18F/tock#51]
add a mm/dd/yyyy hh:mm:ss timestamp to all sheet submissions for all users and include in .csv report

**Comment by seanherron** [comment]
:+1:

**Comment by seanherron** [comment]
Should this be the time of when that individual user submitted?

**Comment by batemapf** [comment]
yessir. or in the case of someone making multiple edits, the time of last
edit.

On Mon, Apr 6, 2015 at 5:18 PM, Sean Herron <notifications@github.com>
wrote:

> Should this be the time of when that individual user submitted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/issues/51#issuecomment-90248029>.
>



-- 
Patrick F. Bateman
Deputy Director, Team Operations
18F
U.S. General Services Administration

**Comment by seanherron** [comment]
Done in https://github.com/18F/tock/pull/56
