### ISSUE TITLE
Active project not showing up in timecard dropdown search

### ISSUE THREAD

**Issue by mtorres253** [18F/tock#515]
To duplicate

Navigate to your timecard for period: Oct. 2, 2016 to Oct. 8, 2016

Click a dropdown and search for "Open Opportunities"

Expected behavior: I see the following match: Custom Partner Solutions / OCSIT / Open Opportunities (206)

Actual behavior: I see a no results message:

<img width="475" alt="screen shot 2016-10-06 at 2 00 59 pm" src="https://cloud.githubusercontent.com/assets/100149/19166509/5fe856a2-8bcd-11e6-9a68-927c404184a9.png">

**Comment by annalee** [comment]
Turns out the project was set to 'inactive.' Resolved.
