### ISSUE TITLE
Link utilization report to timesheets

### ISSUE THREAD

**Issue by rdpiazza** [18F/tock#518]
As a supervisor, I want to be able to quickly access recent timesheets for members of my team so that I can understand their utilization rate.

More info:
Love the utilization report.  As I was scanning through the folks on my team, I noticed that a few people had utilization rates of less than 80% for their most recent time period.  I'd love to be able to click on their last week % to jump directly to their latest timesheet, so I can see what they were working on, and a way to easily jump to their list of all recent timesheets.

**Comment by batemapf** [comment]
closed via #563
