### ISSUE TITLE
Tock as prompt for communication/provocation

### ISSUE THREAD

**Issue by vzvenyach** [18F/tock#519]
Because folks go to Tock every week, I've started to wonder whether we should consider Tock as a means of communication and provocation. 

For example, one idea I'm kicking around is to have a prompt on the front page related to things that merit team-wide attention. This may be event ("New launch! check it out!") or policy related ("Make sure to tock travel time to your client"), or could even be a prompt for Action ("Make sure to take your `Employee Accountability for GSA Personal Property` training, due on 10/19!").

Another idea is to have a digital "suggestions/updates box" that always invites 18Fers to offer ideas, perspectives, news, etc., in an unobtrusive way.

Final thought is to include key performance metrics right on the front page. As a reminder to all of us that when we're tocking our time, it's not just for purposes of compliance, but as a reminder that we had the privilege of serving the American public this week.

**Comment by adelevie** [comment]
Perhaps this could read Dolores quarterly announcements as a data source. Although I personally still prefer Slack for these kinds of things ...

**Comment by batemapf** [comment]
>Final thought is to include key performance metrics right on the front page. As a reminder to all of us that when we're tocking our time, it's not just for purposes of compliance, but as a reminder that we had the privilege of serving the American public this week.

How about # of hours billed in the prior week, FYTD vs. targets? Or other parts of the @joshuabailes reporting discussed in #536? Would be very easy, just need target into...

**Comment by abrouilette** [comment]
@joshuabailes, this one has a lot of components.  Which ones, if any, are the ones you want to make sure happen?   I think maybe we should be splitting this into multiple issues. 

Or, @maya, is this a candidate for user testing?

**Comment by maya** [comment]
There are some interesting ideas here, but worry we're getting away from the focus of Tock and trying to do too much with it. 

I agree with @adelevie that Slack/email should serve as our primary tool for communicating news and Tock be focused on the primary need of time tracking. Is the current format not working? Adding this brings up additional needs like ongoing content review from the comms team. If this is desired to dive in further, we'd need to do user research around it.

A "suggestions/updates box" could be done separately via a Google form (as we've done in the past via periodic 18F team health checks) or GitHub. You can also pin items in Slack if you want certain prompts to subsist. 

The last paragraph around performance metrics is a separate issue and could be broken out to its own issue to be further researched.

**Comment by abrouilette** [comment]
@joshuabailes, @vzvenyach, thoughts on @maya's questions/comments?

**Comment by joshuabailes** [comment]
My thoughts are: we need a central dashboard to reflect what is here: https://docs.google.com/presentation/d/1iLmCAvmcGJ68e5hvbsZydieSTTLniSSpzpxhbjFyl_Y/edit

The need for further messaging isn't as germane to me.

**Comment by vzvenyach** [comment]
I don't fundamentally disagree about scope creep, but I do think it's perhaps a missed opportunity to meet our team where they are once a week. Having a separate google form is *fine*, but you'd need to communicate in slack and they'd have to see it in slack, be in the channel, not overlook it, etc. Tock exists as a thing you do once a week. As long as you're there, we might encourage you to drop a suggestion, or something else. That said, I'm not also *that* attached to the concept.

**Comment by batemapf** [comment]
@joshuabailes what is the single most important element of that google prez?

**Comment by joshuabailes** [comment]
@batemapf The Hours and $ earned to date and by week compared to our goals. The $ estimated at blended rate.

In the meters, the yellow is 3100-4300 and green is 4300 and up.

**Comment by batemapf** [comment]
well that is four things, but let's see what we can do. will work on a basic mock up.
