### ISSUE TITLE
Setup automated a11y testing

### ISSUE THREAD

**Issue by maya** [18F/tock#520]
I was trying to find a way to copy and paste a11y reports so I could more easily create issues for them and @shawnbot recommended setting up Pa11y. 

> Pa11y is your automated accessibility testing pal. It runs HTML CodeSniffer from the command line for programmatic accessibility reporting.

More info here: https://github.com/pa11y/pa11y#command-line-interface

cc: @abrouilette to see if this is something we want to do and how we want to prioritize it.

**Comment by abrouilette** [comment]
Bring this up at the next Sprint planning, unless it is more urgent than that?

**Comment by vzvenyach** [comment]
Could also use https://continua11y.18f.gov

**Comment by maya** [comment]
Thanks for the suggestion @vzvenyach. 

Looks like we may postpone this in favor of more pressing issues for now.
