### ISSUE TITLE
Alert says to tock on Monday instead of Friday

### ISSUE THREAD

**Issue by maya** [18F/tock#524]
The alert says:
>Reminder! Please complete your Tock time card for the prior week no later than end of the day on Monday (or the first business day of the following week).

but we've since changed it to Friday, so we need to update this text to be accurate.

Instead it should say:
>Reminder! Please complete your Tock time card for the prior week no later than end of the day on Friday (or the last business day of the week).

cc: @joshuabailes

**Comment by sfvictor** [comment]
Thanks Maya for catching!  Can we say:  Reminder! Please complete your Tock time card for the current week by no later than the end of day on Friday (or you last business day of the week).   Note: should you work an authorized Saturday overtime, then please enter and submit your time by COB Saturday.   Our work weeks run Sunday thru Saturday.  @joshuabailes @HuixianXu

**Comment by joshuabailes** [comment]
This is perfect.

Joshua Bailes
18F Acting Director of Operations
Joshua.Bailes@gsa.gov
202-550-6659
18F.gsa.gov <https://18f.gsa.gov/>

On Wed, Oct 12, 2016 at 2:40 PM, victor valdiviezo <notifications@github.com

**Comment by maya** [comment]
Added @sfvictor's note here: 100808b. 

Feel free to check the text here: https://github.com/18F/tock/pull/525/files
