### ISSUE TITLE
User data update - GS Level

### ISSUE THREAD

**Issue by rooneywp** [18F/tock#528]
**Issue:** User has received a promotion, the new GS level and effective date needs to be entered into Tock.

**User:** Elizabeth Goodman
**Tock ID:** elizabeth.goodman
**New GS Level:** 15
**Start Date:** 10/02/2016

**Note:** Putting this here, @batemapf did the manual upload previously and I'm not sure if there is an ongoing process defined yet for maintaining this information.

**Comment by batemapf** [comment]
this is done.
