### ISSUE TITLE
Truancy

### ISSUE THREAD

**Issue by abrouilette** [18F/tock#529]
As @joshuabailes, I want to be able to generate a Tock Truancy Report for those who do not Tock their time by the Friday weekly deadline, including Who Has Not Tocked This Week, How Many Times This User Has Been Truant Overall, and How Many Consecutive Weeks They Have Been Truant,  so I can nudge and plead and cajole more effectively.

**Comment by batemapf** [comment]
where does this fall in the @joshuabailes priorities?

**Comment by joshuabailes** [comment]
High Priority. Ranks just below the entry of week before and week after in Tock. and other current inflight items.
