### ISSUE TITLE
link to GitHub activity

### ISSUE THREAD

**Issue by afeld** [18F/tock#53]
From the timesheet form, it would be great to link to that week's GitHub activity as a way to remind folks (that use GitHub regularly) what they've worked on. For example:

https://github.com/search?utf8=%E2%9C%93&q=user%3A18f+created%3A%222014-11-22+..+2014-11-30%22+author%3Aafeld&type=Issues

**Comment by konklone** [comment]
Yessss this is such a good idea. I often refer to that. Same for my sent email for the week, and my GCal for the week, but I could see that as being tougher to generate a reliable link for.
