### ISSUE TITLE
Automate Bailes' Dashboard 

### ISSUE THREAD

**Issue by abrouilette** [18F/tock#536]
https://docs.google.com/presentation/d/1iLmCAvmcGJ68e5hvbsZydieSTTLniSSpzpxhbjFyl_Y/edit#slide=id.p 

As a person who knows @joshuabailes, I want to automate this for him, so he can be free to do other valuable stuff.

**Comment by joshuabailes** [comment]
@batemapf Would an inclusion of float data in this report be too much of a lift? High level type summary of scheduled work etc?

**Comment by abrouilette** [comment]
Per @joshuabailes in Slack, @batemapf, you are good to get rolling here.
