### ISSUE TITLE
Add New Tock User Data Fields

### ISSUE THREAD

**Issue by rooneywp** [18F/tock#539]
In support of reporting (manual or automated), if we add "Billable Category" and "Team (Chapter/BU)" as fields of the user within Tock, we can reduce the number of data sources that need to be integrated to produce the required reporting.

**Comment by maya** [comment]
Noting that GS level / rate is another thing we heard as a request during research. The Talent team has this data.

**Comment by batemapf** [comment]
@rooneywp here is what the UserData data currently looks like:

<img width="763" alt="screen shot 2016-11-22 at 12 47 40 pm" src="https://cloud.githubusercontent.com/assets/7645362/20535191/e97ca284-b0b1-11e6-9303-abda32eaca56.png">

we could update the field type for billable from Boolean to choices which would allow for different gradations of "billable"-ness. the unit / chapter info is already there, though i am not clear on the process of ensuring it is up to date (cc @HuixianXu). there is also another class of objects called EmployeeGrade which are related to UserData that hold GS grade information for each employee.
