### ISSUE TITLE
Associate Tock line items with TTS accounting codes

### ISSUE THREAD

**Issue by adelevie** [18F/tock#541]
This problem arises when I'm logging/reconciling micro-purchases in Pegasys. I know the Tock line item for every micrp-purchase, but it seems to be getting less and less clear as to which TTS accounting code to use. 

Given I am a p-card holder
And I know the Tock line item for a purchase
When I visit the Tock project page for that line item
I should see the appropriate TTS accounting code

**Comment by batemapf** [comment]
@adelevie this should have been addressed in #559, right?

**Comment by adelevie** [comment]
Yuuuuup!
