### ISSUE TITLE
How to rename "434 - cloud.gov - UI/UX (Liberator)" to "434 - cloud.gov - UI/UX (Navigator)"

### ISSUE THREAD

**Issue by adborden** [18F/tock#547]
We changed our project name, we'd like to update it in Tock as well. I'm not sure if this is something we can do or need help from the Tock/Ops teams.

Rename "434 - cloud.gov - UI/UX (Liberator)" to "434 - cloud.gov - UI/UX (Navigator)".

Dependency of https://github.com/18F/cg-design/issues/17

**Comment by suprenant** [comment]
I put a note for this in #tock: https://gsa-tts.slack.com/archives/tock/p1478014684001685

**Comment by adborden** [comment]
Looks like this was [changed in tock](https://gsa-tts.slack.com/archives/tock/p1478032800001729), I'll update this PR.

**Comment by adborden** [comment]
And by that I mean close this :)
