### ISSUE TITLE
Hide Project names with 0 hours for submitted timesheets

### ISSUE THREAD

**Issue by rdpiazza** [18F/tock#552]
I review the timesheets each week for the members of my team using the report at https://tock.18f.gov/reports/[date]/[name]/.  Many people leave Tock lines on their timesheets that have 0 hours against them for the week, which makes them hard to review.  It would be very helpful if the reports at that location hid Project lines that had 0 hours charged against them.

**Comment by batemapf** [comment]
closed via #564
