### ISSUE TITLE
UI Issues for Save/Submit

### ISSUE THREAD

**Issue by AlanAtlas** [18F/tock#555]
For casual or hostile Tock users, there are a couple of ambiguous points in the UI around saving and submitting that you could improve.

If there are errors on Save or Submit, the UI does not highlight them. you have to realize that it didn't work and you have to manually scroll to find the errors. Making sure there was a visible error warning regardless of where the page is scrolled would be a huge improvement.

Also, how about a "Are you sure?" dialog for hitting Save, because a lot of people hit Save but mean Submit.

Also, the snippets are apparently required fields, even if there are no hours against those items. Perhaps you could fix that, and in the case where the field actually needed text, how about a visible error or a forced scroll to the offending field, rather than the current, silent and subtle refusal to Submit?

Thanks!

alan

**Comment by batemapf** [comment]
```If there are errors on Save or Submit, the UI does not highlight them. you have to realize that it didn't work and you have to manually scroll to find the errors. Making sure there was a visible error warning regardless of where the page is scrolled would be a huge improvement.```

```Also, the snippets are apparently required fields, even if there are no hours against those items. Perhaps you could fix that, and in the case where the field actually needed text, how about a visible error or a forced scroll to the offending field, rather than the current, silent and subtle refusal to Submit?```

^^ both of these are addressed in #560. the "are you sure" message has not.
