### ISSUE TITLE
Team Reporting Improvements

### ISSUE THREAD

**Issue by abrouilette** [18F/tock#561]
Convert the Tock python script for getting a report on a team’s reported hours for a week into something more usable than it is now.

**Comment by abrouilette** [comment]
@joshuabailes, can we consider this @batemapf's new focus?

**Comment by joshuabailes** [comment]
Yes.

Joshua Bailes
18F Acting Director of Operations
Joshua.Bailes@gsa.gov
202-550-6659
18F.gsa.gov <https://18f.gsa.gov/>

**Comment by hollyallen** [comment]
In my opinion, an MVP is to make the cli tool run in no more than 3 steps:
1. Clone the repo
2. Obtain an api key
3. Run a command

Even better would be to move this all into the web interface so non-engineers can even more easily use it.

**Comment by rdpiazza** [comment]
Agree with Holly that simplifying the install would be helpful but a web interface would be even better.  That way there's less switching between tools.  If I saw someone was under their hours for the week, for example, the first thing I'd want to do is pull up their Tock report for the week to know why.  Having it all in one tool would be helpful for that.

**Comment by batemapf** [comment]
@hollyallen @rdpiazza (please add others, too): what is the the **one** most critical piece of information you are getting out of the DZ script? i'd like to build this right into the existing app (similar to the utilization reports page), but need a single starting point.

**Comment by abrouilette** [comment]
cc @GailSwanson

**Comment by rdpiazza** [comment]
The most critical thing would be a list of all of the people in Product and how many billable hours they had last week so I could quickly scan to see who was low.  Next thing I'd want added is for each person in the list to link to that person's timesheet for the week so I can easily click through and drill into the details.

**Comment by hollyallen** [comment]
An important note here is that @vzvenyach created the cli tool right around the time the tock utilization reporting functionality came out. Therefore the Tock web tool provided one view, but Dave was measuring us on a different set of metrics. We need to align those.

**Comment by abrouilette** [comment]
@maya, @lauraponce, go ahead and take a run at the folks who are users of this.

**Comment by maya** [comment]
TODO: Find out what info supervisors need that they don't have right now.

**Comment by abrouilette** [comment]
Starting points are @hollyallen, @rdpiazza, & @GailSwanson .
