### ISSUE TITLE
Strategists Missing from CSV

### ISSUE THREAD

**Issue by abrouilette** [18F/tock#565]
Jeremy Zilar, Nikki Lee, Nikki Zeichner, and Cyd Harrell are sorta missing from the downloaded csv for the week of November 6, 2016 to November 12, 2016, per @acolter. (Well, their emails are.  See below.) @sfvictor reviewed their profiles and can find no reason they are not showing up, so the question is now posed to you, @annalee & @batemapf.

**Comment by abrouilette** [comment]
Updating: Same people missing from the prior week's report.

**Comment by abrouilette** [comment]
Further, they do not appear in the CSV at all, so this is not an error in Strategy's function.

**Comment by acolter** [comment]
They don't appear in the CSV, but their time entries do. There's just no email address listed in the User column. (Try this with Cyd Harrell's timesheet, for example. If you go to the Reports by weekly reporting period link for November 6, 2016 to November 12, 2016 and navigate to her time card, you'll see she worked 14.0 hours on FFD. 

But if you search for "Harrell" in the CSV file, you don't see her. You *do* see an entry for 14.0 hours for FFD with no email in the User column. 

Let me know if I can answer any other questions.

**Comment by batemapf** [comment]
closed via #571
