### ISSUE TITLE
add in revenue and expense values to each entry

### ISSUE THREAD

**Issue by batemapf** [18F/tock#57]
#### Formula

Revenue = if project = billable, hours * labor rate, where labor rate is defined by grade level

#### Rates

Grade Level | FY15 Rate
------------ | --------------
7|$59.00
9|$72.00
11|$87.00
12|$104.00
13|$124.00
14|$146.00
15|$172.00

#### Formula

Expense = hours * expense rate, where expense rate is defined by grade AND step and by DC or SFO, with condition that all employees who are not stationed in SFO are stationed in DC

#### Hourly Rates

Grade-Step Level | DC FY15 Rate | SFO FY15 Rate
------------- | -------------------- | -------------------
1-1|13.56|14.76
2-1|15.25|16.59
3-1|16.64|18.1
4-1|18.68|20.32
5-1|20.89|22.73
6-1|23.29|25.34
7-1|25.88|28.16
8-1|28.66|31.18
9-1|31.66|34.44
10-1|34.86|37.93
11-1|38.3|41.67
12-1|45.91|49.94
13-1|54.59|59.39
14-1|64.5|70.18
15-1|75.87|82.55
1-2|14.02|15.25
2-2|15.61|16.98
3-2|17.19|18.7
4-2|19.3|21
5-2|21.59|23.49
6-2|24.07|26.18
7-2|26.74|29.1
8-2|29.62|32.22
9-2|32.71|35.59
10-2|36.02|39.19
11-2|39.58|43.06
12-2|47.44|51.61
13-2|56.41|61.37
14-2|66.65|72.52
15-2|78.4|85.3
1-3|14.47|15.74
2-3|16.12|17.53
3-3|17.75|19.31
4-3|19.92|21.67
5-3|22.29|24.25
6-3|24.84|27.03
7-3|27.61|30.03
8-3|30.57|33.26
9-3|33.77|36.74
10-3|37.18|40.46
11-3|40.85|44.45
12-3|48.97|53.27
13-3|58.22|63.35
14-3|68.8|74.86
15-3|80.93|88.05
1-4|14.91|16.23
2-4|16.54|18
3-4|18.3|19.91
4-4|20.54|22.35
5-4|22.98|25.01
6-4|25.62|27.87
7-4|28.47|30.97
8-4|31.53|34.3
9-4|34.82|37.88
10-4|38.35|41.72
11-4|42.13|45.84
12-4|50.5|54.94
13-4|60.04|65.33
14-4|70.95|77.2
15-4|83.46|90.8
1-5|15.37|16.72
2-5|16.73|18.2
3-5|18.86|20.51
4-5|21.17|23.03
5-5|23.68|25.76
6-5|26.4|28.72
7-5|29.33|31.91
8-5|32.48|35.34
9-5|35.88|39.03
10-5|39.51|42.98
11-5|43.41|47.22
12-5|52.03|56.6
13-5|61.86|67.31
14-5|73.1|79.54
15-5|85.99|93.56
1-6|15.63|17
2-6|17.22|18.74
3-6|19.41|21.12
4-6|21.79|23.71
5-6|24.38|26.52
6-6|27.17|29.56
7-6|30.19|32.85
8-6|33.44|36.38
9-6|36.93|40.18
10-6|40.67|44.25
11-6|44.68|48.61
12-6|53.56|58.27
13-6|63.68|69.29
14-6|75.25|81.87
15-6|88.52|95.38
1-7|16.08|17.49
2-7|17.71|19.27
3-7|19.96|21.72
4-7|22.41|24.38
5-7|25.07|27.28
6-7|27.95|30.41
7-7|31.05|33.79
8-7|34.39|37.42
9-7|37.99|41.33
10-7|41.83|45.51
11-7|45.96|50
12-7|55.09|59.93
13-7|65.5|71.27
14-7|77.4|84.21
15-7|91.05|95.38
1-8|16.53|17.98
2-8|18.21|19.81
3-8|20.52|22.32
4-8|23.03|25.06
5-8|25.77|28.04
6-8|28.72|31.25
7-8|31.92|34.72
8-8|35.35|38.46
9-8|39.04|42.47
10-8|42.99|46.77
11-8|47.24|51.39
12-8|56.62|61.6
13-8|67.32|73.24
14-8|79.55|86.55
15-8|93.58|95.38
1-9|16.54|18
2-9|18.7|20.34
3-9|21.07|22.93
4-9|23.66|25.74
5-9|26.47|28.79
6-9|29.5|32.1
7-9|32.78|35.66
8-9|36.31|39.5
9-9|40.1|43.62
10-9|44.15|48.04
11-9|48.51|52.78
12-9|58.15|63.26
13-9|69.14|75.22
14-9|81.7|88.89
15-9|95.38|95.38
1-10|16.96|18.45
2-10|19.19|20.88
3-10|21.63|23.53
4-10|24.28|26.42
5-10|27.16|29.55
6-10|30.28|32.94
7-10|33.64|36.6
8-10|37.26|40.54
9-10|41.15|44.77
10-10|45.31|49.3
11-10|49.79|54.17
12-10|59.68|64.93
13-10|70.96|77.2
14-10|83.85|91.23
15-10|95.38|95.38

**Comment by batemapf** [comment]
you can blame @adelevie for encouraging me to learn git and markdown.

**Comment by adelevie** [comment]
sweet markdown table, @batemapf

**Comment by seanherron** [comment]
So we should probably have a conversation around how we manage this with regard to time. The way I see it, there are a few things to take in to consideration:

1. 18F rates charged to projects can change between reporting periods
2. Different projects can have different 18F rates charged to them in the same reporting period
3. An individual's hourly may change between reporting periods, either due to grade/step changes or location changes
4. Querying a reporting period's financial information should result in a calculation that is indicative of rates _at the time of the reporting period_, not the time of the query
5. We do not consider information about 18F employee's pay to be sensitive, as it is already publicly available
