### ISSUE TITLE
Recent/saved projects disappeared from my timesheet

### ISSUE THREAD

**Issue by maya** [18F/tock#579]
When I log into tock to my current timesheet page, all the projects that I recently used (but did not have time for disappeared). I'd like these to persist bc they are commonly used.

Is this a side effect of #564? @batemapf

**Comment by batemapf** [comment]
yup, anything without hours logged is zapped on submission. when you pull up your new timesheet, it looks at the last one to see what to bring forward.

**Comment by batemapf** [comment]
Thought about this a bit over the weekend. Right now, a user's "favorites" are generated from the last timecard they submitted. What if we made that functionality a bit more robust by either:

(1) Allowing the user to actually select their "favorites" interactively in the app; or
(2) Generating favorites based on more than one timesheet (i.e. based on last timesheet + frequently selected items)

**Comment by maya** [comment]
I actually liked the original functionality where it automatically saved what I used prior and put the onus on me to remove things I no longer needed, so for #1 adding a favorites functionality adds a separate step that's in addition to the primary use of the app of logging time, that I don't know is necessary / distracts from the primary function. 

#2 is interesting and closer to what I'd imagine. The only worry with using `+ frequently selected items` is that it could be unpredictable, as in people wouldn't know why something disappeared. But if someone didn't use something for a very long time and we removed it, I don't see a big issue with that. The only question is do we need that if it's something they can already do manually?

**Comment by batemapf** [comment]
OK, here is what I am thinking to (at minimum) get back to the original functionality but w/o cluttering up the DB with lots of zero entries:

1. When cleaning the timecard form, grab all zero entries that are _not_ marked DELETE and add them to a UserData-based "favorites" list;
2. When loading a new timecard form, query the DB for the user's favorites, and if present, populate the form with the favorites;
3. Each time a user submits a new timecard and it is cleaned, the favorites are updated. For example, if a favorite is selected for DELETE-tion from the timecard, it will also be removed from the user's favorites.

With an implementation like this, we allow the user to passively "manage" their favorites: users who are fine with a more busy timecard will continue to have it; those who want a less busy timecard will be able to achieve that by checking the existing delete box.

@maya thoughts on this direction? @annalee would like your input too!
