### ISSUE TITLE
bulk load of project descriptions

### ISSUE THREAD

**Issue by batemapf** [18F/tock#59]
we maintain a file (which i will produce shortly) that has short descriptions of all 18F projects.  would be great to load them in w/o manually cut/paste text via admin page

**Comment by batemapf** [comment]
here are aforementioned project [descriptions](https://docs.google.com/a/gsa.gov/document/d/1E4OVGiaGW0cXc-ciRw9FIM-8rbGRG8wt04bmfvpkjO0/edit?usp=sharing) (not in good format for load)

**Comment by seanherron** [comment]
Merging into meta issue https://github.com/18F/tock/issues/97
