### ISSUE TITLE
CPS Burn Doc Automatic Assistance

### ISSUE THREAD

**Issue by abisker** [18F/tock#595]
CPS needs some help automating various functions of the [CPS burn doc template](https://docs.google.com/spreadsheets/u/1/d/1Y312VoZI0nS_tsuJOX5peDJd-Hgw-u0d3u_IQG1TCdw/edit#gid=31205003) which we use to track spending against budgets for all CPS projects. 

Looking to at minimum automatically pull in numbers from each week. Open to other suggestions for improvement/integration though!

**Comment by batemapf** [comment]
@abisker that is an intense workbook! which numbers are you referring to? hours spent on a certain project in total? something more granular? non-hourly expense data, as well?

**Comment by abisker** [comment]
I'm looking for the weekly hours by person, like C6 in tab "Est Scheduled Work vs Actuals (Tock)"
