### ISSUE TITLE
Problem with Tock time charts being one week off

### ISSUE THREAD

**Issue by billygriffin** [18F/tock#599]
It looks like the charts in Tock are potentially a week off. Please see below.

<img width="257" alt="screen shot 2016-11-29 at 11 52 18 am" src="https://cloud.githubusercontent.com/assets/5091167/20842262/39569d4a-b874-11e6-8fad-5c98f8ccad93.png">

This is an image from the 18F Admin Leave Tock Line, located here: https://tock.18f.gov/projects/354/

Thanksgiving and Veterans Day occurred on 11/24 and 11/11, respectively, but this chart shows the corresponding out of office for the week ended 11/20, and 11/6. It looks like the chart is one week off, showing things *before* they actually occurred.

**Comment by rogeruiz** [comment]
Fixed by 9ba9079
