### ISSUE TITLE
Name improvements for utilization report

### ISSUE THREAD

**Issue by maya** [18F/tock#602]
- [ ] Rather than `john.smith`, can we use their actual name as is `John Smith`? 
- [ ] Can we alphabetize the names in the chapter list?

Current:
<img width="921" alt="screen shot 2016-12-02 at 2 56 40 pm" src="https://cloud.githubusercontent.com/assets/5249443/20853250/9c5cb43a-b89f-11e6-82c9-b151a9419b6d.png">

Expected:
<img width="917" alt="screen shot 2016-12-02 at 2 56 24 pm" src="https://cloud.githubusercontent.com/assets/5249443/20853254/a0eb7e1e-b89f-11e6-84e8-f86d7194c05f.png">

Not high priority, just documenting @batemapf @annalee

**Comment by batemapf** [comment]
we have stale PR (#464) that addresses this issue. will try to bring it current this week and get it merged!
