### ISSUE TITLE
Chosen library accessibility issues 

### ISSUE THREAD

**Issue by maya** [18F/tock#604]
[Chosen](https://github.com/harvesthq/chosen), a jQuery plugin we use for our autocomplete dropdowns, has had issues with accessibility since 2011: https://github.com/harvesthq/chosen/issues/264. Some people in the thread have taken passes at making it accessible. We can review their solutions with making the widget accessible or find an alternative. The two solutions with making it accessible appear to be 1.) a more comprehensive deep-dive into making the widget accessible and 2.) display the select element for screenreaders only.

**Comment by ckundo** [comment]
@maya I'm curious where you landed on this concern. A brief look shows you're using Chosen in some forms after all. Did you fork the library, or something else? I'm hoping to learn from your approach. Thanks!

**Comment by maya** [comment]
@ckundo sorry for the delay, indeed we have been using Chosen for our forms. Although we have not been able to incorporate an accessible version of this plugin yet, I'd probably look at some of the work done in this thread https://github.com/harvesthq/chosen/issues/264 to get ideas of what accessible implementations of it look like, as I know there's work that's already been done with it by other users.
