### ISSUE TITLE
Bug: Rows listed twice in utilization report

### ISSUE THREAD

**Issue by rdpiazza** [18F/tock#627]
Bret Mogilefsky's utilization report for this week shows his entries twice for the week of 2017-04-02.  Link: https://tock.18f.gov/reports/2017-04-02/bret.mogilefsky/

<img width="829" alt="screen shot 2017-04-10 at 5 15 19 pm" src="https://cloud.githubusercontent.com/assets/10507124/24883001/173904d4-1e11-11e7-95e1-8914d61d2542.png">

**Comment by ccostino** [comment]
We need to look into this more, and I am curious if this behavior is related to #642 (so making a note of here to check).

**Comment by tbaxter-18f** [comment]
I'm thinking since there haven't been subsequent reports this was resolved with #642. If it re-appears, we'll open a new issue.
