### ISSUE TITLE
Summarize Tock'd time for a set of users

### ISSUE THREAD

**Issue by mogul** [18F/tock#629]
In order to understand how a subset of my team's time is being spent, as a project manager I want to select a set of people and see a summary of what they're Tock'ing to collectively.

---

cloud.gov has multiple Tock lines for subsets of cloud.gov as a project. I can inspect the Tock'd time for an individual via the `/employees` URL and see how their time is Tock'd across those lines, as well as how their non-cloud.gov time is billed to other lines. And I can look at a single line at a time via `/projects`. However, I can't look at data for a particular subset of people in the team. For example, we have a "customer" squad (subset of the overall team), and we would like to be able to see how much of that squad's time is shared with other projects (and which ones) and how much of that squad's effort is dedicated to our different lines in the course of their normal work.

**Comment by pburkholder** [comment]
I'd like to be able to view my own data without have to write scripts against the API. This would've been really useful today when I was trying to make some corrections. So a subset of one user in this case.

**Comment by acolter** [comment]
I'd like a way to see the folks on the 18F P&L for a given week. So when Monday rolls around it's possible to take a look at a page like https://tock.18f.gov/reports/2018-12-23/ and see only who has/hasn't tocked from the 18F P&L. Not CoE, not TTS, not Office of Acquisition, not login or cloud. Not sure if the other offices/P&Ls would find this useful, so it might just be a filter for 18F.

**Comment by tbaxter-18f** [comment]
I think this request is being covered by other filtering issues, notably #968 and by the ability to view utilization at the personal and BU level. So I'm closing it, but am amenable to reopening if I've missed something.
