### ISSUE TITLE
Submission failed and all time entries duplicated

### ISSUE THREAD

**Issue by jseppi** [18F/tock#642]
I just tried to submit my weekly tock report. After submitting, all my time entries were duplicated and it showed I had an 80-hour time sheet.

I deleted the duplicate entries and was then able to successfully submit.

**Comment by ccostino** [comment]
We've noted that this seems to be caused when folks have Tock open in multiple tabs, but will investigate further and work on a solution to prevent in the future.

For now the work-around is pretty much as described:

1. Close all tabs with Tock
2. Reopen Tock
3. Delete any duplicate entries
4. Submit again

**Comment by tbaxter-18f** [comment]
Closing due to age and subsequent fixes.

**Comment by ccostino** [comment]
Yeah I think we finally got this one.  If it happens again, it'd be a new issue.
