### ISSUE TITLE
"snippit for this item" required even if item has 0 hours

### ISSUE THREAD

**Issue by ctro** [18F/tock#648]
![screen_shot_2017-08-07_at_9 42 00_am](https://user-images.githubusercontent.com/11878/29039822-05d4cc30-7b6a-11e7-9073-e4cce41823e4.png)

My expected behavior is for items like 'General' which ask for a 'snippit', will only validate presence of the snippit if the hours logged is >0.

**Comment by ccostino** [comment]
I wonder if this is loosely related to #643 (which has a PR ready to go to fix it) and the person was unable to delete the item to clear it out, so they just left it.

Either way, you're right @ctro, it shouldn't perform the validation if the hours are 0!

**Comment by ctro** [comment]
Thanks Carlo, I think they're separate issues.

I agree deleting the empty line item would prevent the error.
Part of the problem here, I think, is that the error message and the bolding of the errored field don't make it clear exactly what the problem is.

I submitted this bug after I watched someone struggle with why they couldn't submit their report in tock (and remembering that I had struggled the same way a couple weeks ago).

**Comment by ccostino** [comment]
I've been thinking about this issue more as a couple of other folks have mentioned it and I've been bitten by it myself.  I've typically just gone around it by deleting the line if I don't have any hours for `General` (rare, but it happens), but I agree that at the very least the error message could be better in this case!

In terms of fixing this though, is that enough?  In addition to the error message, we could also do the following:

* Simply removing the line item on the user's behalf when they submit their time card - my concern with this though is the case of someone simply forgetting to enter the hours in the first place; if the form is submitted successfully, that will result in a change request for the timecard
* Allow the snippet to be empty if there are 0 hours - similar concern as the other option, though

In terms of adjusting the message, what should that look like?

```
A snippet is required for <project name>.  If you intended to enter 0 hours, please delete this line item from your time card.
```

Would that work?  I could also see the argument that if you enter a line item with 0 hours, that clutters one's timecard and reports and while it shouldn't have any impact on calculations and whatnot, better to only have what's actually needed, right?


@abrouilette and @joshuabailes, what is your take on all of this?

**Comment by abrouilette** [comment]
I vote we stop asking for the snippet at all, and let Carlo do more useful things, like an Auto-Bailes that emails people who haven't Tocked every nine minutes until they do.  @joshuabailes, whaddaya think?

**Comment by ccostino** [comment]
Ah good call - are the snippets useful and providing value?

**Comment by abrouilette** [comment]
@ccostino, go ahead and either 1) remove the “required” status from all Tock snippets *or* 2) remove snippets entirely, based on which will take less work by you + which option you & @annalee believe will cause fewer problems. (cc from Slack)

**Comment by ccostino** [comment]
The decision was to disable them entirely for now.  Noting for the future that when they're required, if `0` hours are entered validation will still occur and we'll have to revisit this!
