### ISSUE TITLE
Can't easily search for "general" and/or scroll in project drop-down menu

### ISSUE THREAD

**Issue by ccostino** [18F/tock#651]
It would appear the bug that prevents you from searching for things like `General` has resurfaced again, and once you do (and don't see the result), you can't scroll easily in the project drop-down menu.  I'm guessing this is related to #367, too, but am not sure yet.

Note though that if you search for the exact project ID and name, e.g., `2 - General`, it will come up.

**Comment by hollyallen** [comment]
This hit me as well. It was pretty frustrating.

**Comment by ccostino** [comment]
From @leahbannon:

>If I start scrolling through the dropdown list in projects, it speedily jumps to the end. I heard this is happening to someone else, too. This prevents me from using tock if I don't know the exact number and project name to type.
>I'm in Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by line47** [comment]
Maybe updating the version of [Chosen](https://harvesthq.github.io/chosen/) to the latest would help with this? Alternatively there is another plugin I've used for long dropdown lists called [Select2](https://select2.github.io/examples.html)

**Comment by ccostino** [comment]
Either of those are good place to start - I was definitely going to take a look at upgrading to see, but I'll do a quick comparison to see if Select2 is lighter-weight, more stable, etc.  Thanks, @line47!

**Comment by ccostino** [comment]
In looking into this more today, this speaks to the need of getting better static asset management in place for Tock...

**Comment by ccostino** [comment]
Looks like it was an outdated version of jQuery impacting this.  Fixing coming soon!

**Comment by ccostino** [comment]
This will be fixed with PR #662!

**Comment by ccostino** [comment]
The scrolling issue is fixed, but searching for `General` is not - I uncovered what the cause is though and am discussing it with the Tock dev team.

**Comment by ccostino** [comment]
Fixed via #664!
