### ISSUE TITLE
Add support for late Tock entry notifications

### ISSUE THREAD

**Issue by ccostino** [18F/tock#653]
It'd be a very nice thing for our Ops team to add support for notifications to be sent out to late Tock entrants automatically as opposed to someone having to manually do this.  There are a few ways we could do this, listed below:

* [ ] Email notifications via a tool like ~Mandrill~ and scheduled jobs through Celery (Mandrill isn't an option anymore)
* [ ] Possible Slack integration via a bot like [angrytock](https://github.com/18F/angrytock) (depends on ATO status and procedure)
* [x] Client-side browser notifications, e.g., PR #647 (thanks, @mgwalker!)

More ideas and details to come in the future as we have time to work through the user needs of this.

**Comment by mgwalker** [comment]
For Slack integration, it could also be done with [Charlie](https://github.com/18f/18f-bot).  The pro of using Charlie is one less bot to maintain.  The con is that angrytock already has integration code, so that would have to be reinvented.  😛

**Comment by ccostino** [comment]
Good to note, thanks!  If it wouldn't take much to get Angrytock back up and running that might the path of least resistance here. :-)  That said, this is much lower on the priority list compared to other things, but we at least have your browser notifications in place! 🎉

**Comment by ccostino** [comment]
We'll investigate including Angrytock in the ATO; otherwise, a note that notifications should show up at about 9:30 - 10:00 AM local time Monday morning for users who are late.

**Comment by tbaxter-18f** [comment]
Some effort has been put into this in the related 18F/tock#779 [WIP] - Notifications integration PR, but someone will need to pick it up and bring it the rest of the way in.
