### ISSUE TITLE
bug: can't scroll through project list dropdown

### ISSUE THREAD

**Issue by leahbannon** [18F/tock#661]
If I start scrolling through the dropdown list in projects, it speedily jumps to the end. I heard this is happening to someone else, too. This prevents me from using tock if I don't know the exact number and project name to type.

I'm in Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by ccostino** [comment]
Hi @leahbannon!  Thanks for noting this, but I've already got it covered in #651!  Going to close this one to keep duplicate issues down, but please add any remarks there!  I've copied your message in it already. :-)
