### ISSUE TITLE
Fix borked static asset references

### ISSUE THREAD

**Issue by ccostino** [18F/tock#665]
While looking into an unrelated issue I noticed several errors show up in the logs while fetching static assets:

```
ERR Not Found: /static/img/uswds/close.svg
ERR WARNING:django.request:Not Found: /static/img/uswds/close.svg
ERR Not Found: /tock/static/js/vendor/underscore-min.js
ERR WARNING:django.request:Not Found: /tock/static/js/vendor/underscore-min.js
```

There might be other related ones, but in any case these references need to be fixed to ensure functionality doesn't break anywhere.

**Comment by rogeruiz** [comment]
At least for underscore, we may just be able to remove it. As it's currently not loading and therefore not being used. As for the `close.svg` that is something that probably just needs to be copied over into the `tock/tock/static/` directory in the right place. Will look at this after #703 #649
