### ISSUE TITLE
Users experiencing 500 errors when there's a Float connectivity problem

### ISSUE THREAD

**Issue by ccostino** [18F/tock#669]
We are experiencing numerous 500 level server errors at the the moment and it all seems to be due to the fact that there's a problem with the underlying API calls to Float directly.  The strange thing about this is that services themselves all appear to be fine according to Float's status page at the time of this writing.

The code managing the Float data processing does not have good error handling or logging in it currently, so we have no clear visibility into what is actually wrong, nor do we have graceful handling of such errors so that users can still see and enter their timecards.

This needs to be fixed immediately to address the error handling issue and provide visibility into the underlying issue with the Float API calls.

**Comment by ccostino** [comment]
The fix has been deployed and time sheets should be accessible again.  It looks like the Float API key is now invalid for some reason based on the errors I'm seeing in the logs.

**Comment by ccostino** [comment]
And after checking this morning the Float integration is working fine again.  I'm not sure what the issue actually was as the status page indicated everything was okay.

@abrouilette since we now have better error handling at least and don't have to worry about the Float integration making life difficult for folks, do you mind if we close this issue and deal with future problems separate?

**Comment by abrouilette** [comment]
Not at all, sir!
