### ISSUE TITLE
Add support for manageable timecard notes

### ISSUE THREAD

**Issue by ccostino** [18F/tock#672]
Tock doesn't currently provide a way to manage any general notes in a timecard except for modifying the text in the template directly.  We have a need to make this just a tad more customizable to help our operations team, so we're looking to do the following:

* [x] Make a global timecard notes model
* [x] Allow an ops admin to manage multiple notes that would appear on all timecards
* [x] Display all of the timecard notes present in the system at the top of any timecard
* [x] Move the existing note in the template into the timecard notes

**Comment by ccostino** [comment]
@joshuabailes, what types of fields/options would you need for these notes?  I see three things that would be useful:

* A title
* A body for the note itself
* A toggle for enabling/disabling it

Would this cover it?  Do you feel you need anything else?

**Comment by joshuabailes** [comment]
This would. And the ability to edit it without bothering you.

**Comment by ccostino** [comment]
Yup!  These would be in the admin.  Whatever notes you add, all of the enabled ones would show up at the top of any given timecard. :-)

**Comment by ccostino** [comment]
This is now done with PR #677!

@joshuabailes if something doesn't work right for you, please feel free to re-open this issue.
