### ISSUE TITLE
UAA Auth Route service is discontinued and needs to be replaced

### ISSUE THREAD

**Issue by ccostino** [18F/tock#679]
Per @brittag:

>Maybe helpful for when Tock comes up for ATO, not sure where to put this: it uses the discontinued experimental cloud.gov UAA Auth Route service, which has a known issue (https://github.com/cloudfoundry-community/cf-uaa-guard-service/issues/16).

>Also good to note: we disabled creation of new instances of the service, and if you try to unbind the service, it'll tell you "action not authorized" (just ask us to remove it manually when you want it removed).

>The recommended alternative is to implement https://cloud.gov/docs/apps/leveraging-authentication/ instead.

Specifically, it is subject to cookie replay attacks.  We need to find an alternative, and this will be a required fix for ATO compliance (#652).

**Comment by ccostino** [comment]
As an alternative, implementing [cg-django-uaa](http://cg-django-uaa.readthedocs.io/en/latest/) should work for this use-case, and in turn fix our routing issue with the [autopilot](https://github.com/contraband/autopilot) plugin for true zero-downtime deploys.

**Comment by rogeruiz** [comment]
Now that #720 is merged into `master` this can be closed once the release makes it into Production.

**Comment by ccostino** [comment]
@rogeruiz: This is fully live now in production, so it's okay for @jmcarp and the cloud.gov team to remove the deprecated service, right?

**Comment by rogeruiz** [comment]
Yes @ccostino
