### ISSUE TITLE
Alert readability is difficult

### ISSUE THREAD

**Issue by line47** [18F/tock#682]
Reading the alerts for where to Tock to is difficult.
It would be great if the messages could have some HTML formatting.
Fr example - this list is much more readable when it can be a `<ul>`. 

### Current alert
<img width="1006" alt="screen shot 2017-11-09 at 8 17 24 pm" src="https://user-images.githubusercontent.com/1449852/32638199-29c09fb8-c58c-11e7-9c3e-9a8cdd74715f.png">

### After formatting alert
<img width="1013" alt="screen shot 2017-11-09 at 8 17 16 pm" src="https://user-images.githubusercontent.com/1449852/32638204-2f0b99f0-c58c-11e7-957a-be9459383355.png">

**Comment by ccostino** [comment]
Thanks, @line47!  @joshuabailes had a recent request in for Markdown support if possible for these but I never put in a formal issue it looks like.

FYI that I had started working on this, but ATO work has to take place first.

**Comment by line47** [comment]
no worries, and thanks for the update! 👍

**Comment by ccostino** [comment]
You're welcome!  Hopefully we'll be able to get to this in the near future. :-)

**Comment by tbaxter-18f** [comment]
Closing as it appears to have been resolved with #808. Please speak up if you disagree.
