### ISSUE TITLE
Labels of added items don't match inputs

### ISSUE THREAD

**Issue by hbillings** [18F/tock#685]
I added a new line to my tock timesheet, then realized I added it in error. Clicking the `Delete` checkbox on the new item selected the `delete` checkbox input of the item above. This is because the new label's `for` didn't match the new input's `id`, but the `id` of the prior input. Screenshot here:
<img width="651" alt="screen shot 2017-11-24 at 12 42 53 pm" src="https://user-images.githubusercontent.com/509309/33222556-62e8e180-d115-11e7-936e-8424526266dc.png">

**Comment by ccostino** [comment]
Thank you, @hbillings!  I thought I was seeing things when I was testing another recent change but it appears not, this is indeed a bug!  Thanks for filing, we'll try and get to it as soon as we can. :-)

**Comment by ccostino** [comment]
Figured out the problem and have a fix ready to go!
