### ISSUE TITLE
Pre-populate expected hours on time cards

### ISSUE THREAD

**Issue by annalee** [18F/tock#687]
When users load a new timecard, they should see the hours they are scheduled to work pre-populated, and be able to modify hours from there.

Tock admins should be able to modify users' scheduled hours in the admin interface, both in the employee admin panel and the project admin panel.

Lastly, we'll want to add a link to the new [Tock guidance in the handbook](https://handbook.18f.gov/tock/) to the timecards so people are aware of the changes and what they're supporting.

cc @joshuabailes @abrouilette

**Comment by annalee** [comment]
@ccostino and I discussed and we're leaning towards doing a model that tracks a relationship between a person and a project, and the hours assigned:

Fields:
Person - manytomany
project - manytomany
hours - int

Then set the timecards to generate by pulling the given user's projects and hours from that table.

**Comment by ccostino** [comment]
In thinking about this more, each record in this table is a mapping of a single person with a single project.  Therefore, the employee and project foreign key relationships should be defined as one to many, but the table housing all of these records will certainly have multiple mappings between the same person and multiple projects and vice versa.

**Comment by annalee** [comment]
Yup, exactly this--we're basically doing a manual version of Django's existing behavior of making tables to map many-to-manys. Since we also need to know assigned hours, we can't use the existing pass-through, but we can mimic the behavior.

**Comment by ccostino** [comment]
Really need a :high_five: emoji reaction here. :-)

**Comment by ccostino** [comment]
Whoops, forgot to close this out now that we finished! :tada:
