### ISSUE TITLE
Add a 'department' filter for employees

### ISSUE THREAD

**Issue by annalee** [18F/tock#689]
Admin users should be able to filter employees by their place in TTS, pulling only 18F or only Acq employees as needed.

This department label should appear on downloaded spreadsheets, as the LAST column for a given user.

cc @joshuabailes @abrouilette

**Comment by annalee** [comment]
We could do this either with a table or with an old-fashioned choices field. [Insert joke here about how many reorgs it takes to justify a table for this].

**Comment by ccostino** [comment]
We caught up about this some more, we're leaning toward just going with the model because of these reasons:

* We can leverage it in multiple spots (`Employee`, `Project`, etc.)
* Admins can manage it directly with no code changes

**Comment by ccostino** [comment]
I knew we discussed this before!  See #668 - this work should help fill the need for both issues. :-)

**Comment by tbaxter-18f** [comment]
I don't think this is needed anymore. If there's disagreement, we can happily reopen.
