### ISSUE TITLE
add sortability to report view

### ISSUE THREAD

**Issue by batemapf** [18F/tock#69]
sort by User (A-Z) or Timecard Filed (A-Z)

**Comment by seanherron** [comment]
What if I made this a little simpler and just sorted this in to non-compliant individuals first, then everyone else alphabetical?

**Comment by batemapf** [comment]
even better!

On Tue, Apr 14, 2015 at 2:25 PM, Sean Herron <notifications@github.com>
wrote:

> What if I made this a little simpler and just sorted this in to
> non-compliant individuals first, then everyone else alphabetical?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/issues/69#issuecomment-93008082>.
>



-- 
Patrick F. Bateman
Deputy Director, Team Operations
18F
U.S. General Services Administration
