### ISSUE TITLE
Import existing expected hours into Tock

### ISSUE THREAD

**Issue by annalee** [18F/tock#690]
We have spreadsheets listing people's current expected hours on projects. We'll need to import this data into Tock, which we should be able to do with a script rather than by hand.

cc @abrouilette @joshuabailes

**Comment by toolness** [comment]
Is this taken care of?  I was talking to @abrouilette and he said that it seems like all the expect hour stuff is in there...

**Comment by ccostino** [comment]
Yes it is, thank you for flagging, @toolness!  We just missed it from before. :-)
