### ISSUE TITLE
Reporting periods that don't exist throw a 500

### ISSUE THREAD

**Issue by jmcarp** [18F/tock#692]
https://tock.18f.gov/reporting_period/2017-12-11/ should probably return a formatted 404 but gives me an ugly 500 instead:

<img width="517" alt="screen shot 2017-12-22 at 2 49 55 am" src="https://user-images.githubusercontent.com/1633460/34289937-d4d61b74-e6c2-11e7-8834-0a6fc5407da0.png">

**Comment by ccostino** [comment]
D'oh! :-(  Thanks for reporting, @jmcarp!

**Comment by ccostino** [comment]
Noting that @tbaxter-18f also reported this.
