### ISSUE TITLE
Disappearing hours

### ISSUE THREAD

**Issue by stvnrlly** [18F/tock#697]
While entering my most recent hours, I scrolled up a couple time to find that my earlier entries had been erased. Oddly, this seemed to even reset a batch of saved hours, and added back in a line that I had deleted. As far as I could tell, it was the stuff that was off-screen that changed, but I can't be sure.

I'm sorry that I don't have more information to give, but I quickly submitted my hours in order to try to avoid them disappearing again.

**Comment by tbaxter-18f** [comment]
This feels like one-time weird caching error, and given that there's no known reoccurrence in ~9 months, I'm going to close it. For now... but I'm watching you, Tock.
