### ISSUE TITLE
Allow float percentages of time worked.

### ISSUE THREAD

**Issue by ozzyjohnson** [18F/tock#70]
If I attempt to enter a 1 hour (2.5%) task I receive a validation warning to round down or up to 2% (0:48) or 3% (1:12) respectively.

**Comment by seanherron** [comment]
Hrm. I need to figure out where `step="1"` is coming from in the input.

**Comment by seanherron** [comment]
Actually I fixed this in https://github.com/18F/tock/pull/68 but it hasn't been merged yet.
