### ISSUE TITLE
Subclass AbstractUser to combine user objects

### ISSUE THREAD

**Issue by annalee** [18F/tock#701]
The User model is Django's built-in auth model that's best left alone. We're currently using entries on the User model as our primary relationship between users and other model objects. We should be using UserData instead, which is our own custom model of information related to users.

Shifting to UserData will mean a lot of little changes throughout this app, which will have a lot of knock-on effects and require a bunch of updated tests, but it will make ongoing development easier and it should make for fewer table joins in our queries.

**Comment by tbaxter-18f** [comment]
I think we should change it so that our UserData subclasses AbstractUser (or AbstractBaseUser, if we must) and then there's just one user object, with no remembering which object to use, and no ugly joins.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
