### ISSUE TITLE
Improve Docker setup and fix Python debugging

### ISSUE THREAD

**Issue by ccostino** [18F/tock#702]
It'd be great if someone could take a look and see if there's any way we can improve our Docker setup with Tock.  While the thought here is just in general (are the files in the right place, are we leveraging container dependencies appropriately, do we have the piece configured optimally, etc.), there is one big piece in particular:  being able to drop into the Python debugger (`pdb`, or a `pdb`-replacement like [`pdbpp`](https://pypi.python.org/pypi/pdbpp/0.9.2)) while running the app, tests, or something else.  That is currently not working for us and it makes development and debugging very difficult.

**Comment by rogeruiz** [comment]
This was done in 498123c1d3510d91229a9d290db20f2687aa070b and #722.
