### ISSUE TITLE
Improve CircleCI setup and leverage build workflows for automated deployments

### ISSUE THREAD

**Issue by ccostino** [18F/tock#703]
We'd like to see if any other improvements can be made to our CircleCI configuration, so it'd be great if someone/some folks could take a look!

In addition, we know we need to leverage build workflows for automated deployments for ATO purposes.  In particular, we are planning on the following:

* Continue committing to `master`, which would trigger a build and deployment directly to the `stage` space.
* Add a workflow looking for a specific tag pattern to deploy to the `prod` space for production releases.

**Comment by rogeruiz** [comment]
This was completed in #712
