### ISSUE TITLE
Improve the graphs/visuals in Tock

### ISSUE THREAD

**Issue by ccostino** [18F/tock#706]
Tock's graphs and visuals in the reports page could use some TLC!  If there's something we can do here in a reasonable amount of time, it would be a big help.

**Comment by tbaxter-18f** [comment]
Can we clarify this issue? What sort of improvements are we looking for? Where?

**Comment by ccostino** [comment]
We sure can and should. :-)  I don't have a good sense of what would be appropriate, @joshuabailes and other admin users might be good folks to start asking first and then we can go from there.  I was thinking predominantly when you see the breakdown of hours for a project or a person when viewing those details pages, where it is hard to see all of the information especially if it's squished together.

**Comment by edmullen** [comment]
@tbaxter-18f I believe I found an issue that is related to this issue. It appears that the chart data are not aligned with the correct dates. See this example for Project 734.

![image](https://user-images.githubusercontent.com/2654503/47446730-d4792280-d789-11e8-9dfd-edb01e2c62ad.png)

**Comment by tbaxter-18f** [comment]
Given that we're phasing out most of these visualizations, I'm closing this.
