### ISSUE TITLE
When user hits submit and there isn't 100% all the project values get reset 

### ISSUE THREAD

**Issue by jackiekazil** [18F/tock#71]
When user hits submit and there isn't 100% all the project values get reset when the error is thrown. 
To recreate, partially fill out the form to <100%, then hit submit. All the values in the projects column are reset.

**Comment by seanherron** [comment]
The system doesn't allow submissions that don't add up to 100%. We could maybe hide the submit button unless it adds to 100% to make this very clear.

I'm not sure why the formset is saving the number value but not the project value - any ideas?

**Comment by seanherron** [comment]
I found the bug! It was a problem with how we were taking inputs in to the model. I think it is fixed now - I can't replicate anymore. #118
