### ISSUE TITLE
Update deploy process to handle expensive migrations

### ISSUE THREAD

**Issue by annalee** [18F/tock#710]
We ran into this when deploying the latest work from the Jingle Sprint. The migrations are running for each instance type, and we don't want that as migrations should only run once.

 ## Acceptance Criteria

- [ ] Push a multi-instance version of Tock to staging and see the migrations only running once.
- [ ] Migrations only run on the zeroth instance.
- [ ] Migrations that take a long time (longer than three minutes) are run as tasks and this is documented.

**Comment by rogeruiz** [comment]
https://github.com/18F/tock/pull/712/files#r163586798
