### ISSUE TITLE
2016 timecard in tock 

### ISSUE THREAD

**Issue by ominina** [18F/tock#711]
For some reason, every week the timecard labeled "January 17, 2016 to January 23, 2016" appears on my tock which is confusing and clearly an error.

**Comment by ccostino** [comment]
Thanks for reporting, @ominina!  Out of curiosity, if you try and open the timecard does anything come up or does it error out?

**Comment by ominina** [comment]
![screen shot 2018-01-30 at 4 46 04 pm](https://user-images.githubusercontent.com/14093625/35593147-210424da-05dd-11e8-91f2-adacc2b547d2.png)

**Comment by ominina** [comment]
![screen shot 2018-01-30 at 4 47 36 pm](https://user-images.githubusercontent.com/14093625/35593227-4cc05ba2-05dd-11e8-9bb3-2ac22a1396ce.png)

these are my choices for timecards this week, and every week the 2016 pops up!

**Comment by tbaxter-18f** [comment]
I think this warrants some investigation in the shell, at least.

**Comment by ccostino** [comment]
This was definitely a mystery and we were never able to solve it.  I'd keep it here just in case it crops up again, but I'm not sure there's much else to be done for now.

**Comment by ccostino** [comment]
Need a :doh: emoji in here...  I'm sorry, @ominina!  @tbaxter-18f, this may be something that could be looked at in the admin and fixed there (I suspect that this particular timecard/reporting period for @ominina is not setup correctly), but I would schedule some time with @lsgitter to review this before doing anything.

**Comment by tbaxter-18f** [comment]
Yeah. As mentioned above, I thought it was worth some investigation in the Django shell at least to see if  @ominina's data looks unusual in any way. I can't say I have any theories, but I do think something is happening that warrants a deeper look as time permits. "As time permits" may not be soon, but I'm not closing it out until we've been able to look at it more.

**Comment by ominina** [comment]
its absolutely not a big deal but just strange that it pops up everytime I tock!

**Comment by Jkrzy** [comment]
This is a `thing` @ominina?

**Comment by ominina** [comment]
haha yes @Jkrzy so weird!

**Comment by Jkrzy** [comment]
In an attempt to resolve this, I'm going to flag the offending timecard as `Submitted`.
