### ISSUE TITLE
Add support for start and end dates to prefill data

### ISSUE THREAD

**Issue by ccostino** [18F/tock#715]
The prefill data now has two optional fields:  `start_date` and `end_date` to account for setting a window of when prefill data should be active.  We're still missing the support for reading from these fields, however, and will need to integrate that into the prefill checks to see if and when prefill data should show up.

**Comment by tbaxter-18f** [comment]
Carlo, I think over the past year we've lost a good bit of context about this. Can you fill in some gaps?

**Comment by Jkrzy** [comment]
The current prefill functionality doesn't take into account these fields- `start_date` and `end_date`. It relies solely on the `is_active` flag which is manually set via the admin.

https://github.com/18F/tock/blob/master/tock/hours/views.py#L533

We currently have 32 prefills used by Login and CoE folks.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
