### ISSUE TITLE
Help Wanted on Code.gov

### ISSUE THREAD

**Issue by jcastle** [18F/tock#716]
It looks like you have quite a few Help Wanted issues in your repo.  You can feature these on Code.gov and reach a larger audience by adding specific tags to your Help Wanted issues.  

Here are the specifics - https://github.com/GSA/code-gov/blob/master/HelpWanted.md
And, an example - https://github.com/GSA/code-gov-web/issues/417

Let me know if you have questions, 
Cheers!
Joe

**Comment by ccostino** [comment]
Hi @jcastle!  I'm sorry for the late reply, we have been focused on other priorities over the last couple of weeks.  We had used that label as a means of helping folks in 18F to quickly identify isolated tasks that they could scrub in on should they have time outside of their billable projects (Tock is an internal tool for us).

Seeing as how we do have a good handful of these, though, this is a good reminder of Code.gov as a resource. :-)  Thank you for bringing it back to our attention!  We'll take a look and see if we'd be able to leverage it in the future for help with some of our outstanding items.

Thanks again!
