### ISSUE TITLE
When user hits "submit" and there is a project listed with no percentage value, the project names get reset

### ISSUE THREAD

**Issue by esgoodman** [18F/tock#72]
To recreate, make a timesheet adding up to 100%. Include one project with no time percentage listed. Hit submit. All the time values are then set to zero.

**Comment by seanherron** [comment]
Can you screenshot this for me?

**Comment by esgoodman** [comment]
Either I misstated the error in the initial description or something's changed since yesterday. Anyway,  looks like submitting a project with no time percentage listed results in the time values staying unchanged and the project names getting reset. 

![screen shot 2015-04-15 at 11 21 56 am](https://cloud.githubusercontent.com/assets/10067318/7166317/eec6a844-e361-11e4-943e-66c0bde37bac.png)

**hit submit**

![screen shot 2015-04-15 at 11 22 18 am](https://cloud.githubusercontent.com/assets/10067318/7166321/f5381474-e361-11e4-9d90-a6beebe0c060.png)

**Comment by seanherron** [comment]
Ah, looks like this is the same as https://github.com/18F/tock/issues/71 - I'm going to close this and we can track it there. Thanks!
