### ISSUE TITLE
Add a test suite that ensures all views are protected by authentication

### ISSUE THREAD

**Issue by toolness** [18F/tock#728]
Since #720 is taking Tock from being an app that didn't have to care at all about authentication (since it was behind a proxy that dealt with it) to one that has to care about it all the time, I think it might be useful to have a test suite that goes through the app's URL config and pokes at every URL (except perhaps a very small whitelist of public pages) and ensures that they return either a 403 or redirect to login.

It might be redundant but I think it could also offer some peace of mind.

@rogeruiz what do you think of this?  If it sounds helpful I'm happy to submit a PR.

**Comment by rogeruiz** [comment]
Perfect! I love this idea. and something that would be good to have with the ATO, considering that we now have an authorization-layer we manage ourselves.

The only public page I can think of is the `uaa_client/login_error.html` everything else should be a redirect to UAA or a 403 to that page. Tock doesn't currently have any public-facing pages in accordance to the SSP.

**Comment by toolness** [comment]
Oh, this was fixed by #729!
