### ISSUE TITLE
Refactor application settings and documentation

### ISSUE THREAD

**Issue by rogeruiz** [18F/tock#734]
This issue is able to be worked on in tandem with #733 but with a specific focus on the `settings.py` files used by the various environments. Parts of this issue can be worked on outside of the scope of the ATO process. Multiple PRs can address this ticket.

_Discovered in #720_

### Acceptance Criteria
- [ ] Each environment is using the specific `settings/*.py` file for the correct environment.
- [ ] [Removing `DEBUG = True` from the tests](https://github.com/18F/tock/pull/720#discussion_r171556911).
- [x] Documentation, or automation, around enforcing these changes going forward.

**Comment by tbaxter-18f** [comment]
@rogeruiz Is this something we still need to do? I'm not sure I'm clear on what needs to be done exactly.

**Comment by rogeruiz** [comment]
As I mentioned in the ACs above, we need to refactor the `settings.py` to be more unique for each environment and clean up some things that we set during the tests. I'm not sure if this should hold up a release, but until those things are addressed, we should keep this issue open.

**Comment by rogeruiz** [comment]
Right now we have a settings.py for each environment, but it's not clear how they override and inherit from one another. Some things are `on` in tests that shouldn't be according to @toolness' comment in #720 and really this card is about re-evaluating how the apps are configured across multiple environments.

**Comment by tbaxter-18f** [comment]
Thanks Roger. Just to sure I'm 100% clear (and that it's 100% clear for whoever eventually picks this up)

*Current state:*
* Settings files may needlessly duplicate some settings that aren't needed for their environments
* Environments may not be using settings specifically for their environment (and are instead falling back on more general settings)
* Some tests currently run in  `debug` state and should not.

Is that correct? Complete?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
