### ISSUE TITLE
Django deprecation warnings are not logged

### ISSUE THREAD

**Issue by toolness** [18F/tock#743]
When working on #742 and preparing the codebase for migration to Django 2, I had to explicitly pass `-W error` to `python` to make deprecation warnings show up.  This is weird, because I _think_ Django is supposed to log deprecation warnings by default, and I'm not sure what's going on. Django/Python's logging system has long been the most confusing technology I've ever used, though, so I have no idea how to fix this.

**Comment by Jkrzy** [comment]
They _definitely_ were verbose in the past, but as of 1.11 they're not displayed by default.

https://docs.djangoproject.com/en/1.11/releases/1.11/#deprecating-warnings-are-no-longer-loud-by-default

**Comment by toolness** [comment]
Ahh, so _that's_ what happened--thanks for investigating!  

I guess I will close this then, since it seems to be standard behavior, rather than a Tock bug.
