### ISSUE TITLE
Error message missing when field-level

### ISSUE THREAD

**Issue by cmc333333** [18F/tock#754]
One of my projects requires a Tock comment every week (though I did not know this). When I went to submit my timesheet, I did not add a comment. This resulted in an empty, form-level error message:
<img width="1122" alt="screen shot 2018-03-09 at 6 39 11 pm" src="https://user-images.githubusercontent.com/326918/37235031-6e42ea9c-23c9-11e8-8253-f34d05db3c0b.png">

Scrolling up, I _did_ see a message describing the requirement in line with the comment form.

**Comment by cmc333333** [comment]
"TTS Acq / Consulting / State of California Child Welfare FY17/18"

**Comment by ccostino** [comment]
@abrouilette or @joshuabailes, the Tock project @cmc333333 noted above shouldn't have a required notes field associated with it, correct?  Is it safe to turn it off and is that one of you or am I cleared to do that?

**Comment by abrouilette** [comment]
Correct.  Please turn it off :)

**Comment by ccostino** [comment]
@cmc333333 and @abrouilette, this should be fixed now!  Reopen if it is not. :-)

**Comment by abrouilette** [comment]
Thank you!!

**Comment by ccostino** [comment]
It turns out that this project is supposed to have the required notes field on per @jposi, so we're going to re-enabled it.

**Comment by ccostino** [comment]
Notes re-enabled and required!
