### ISSUE TITLE
fork current repo and begin working on next iteration

### ISSUE THREAD

**Issue by batemapf** [18F/tock#76]
## Purpose

To build and test the next iteration of Tock that supports the following functionality: (1) recording of billable time in hours instead of percentages, up to forty hours per five business day pay period; and (2) recording of non-billable time in percentages only.

## Background

18F's senior leadership team has decided to implement a modified time tracking system where billable time is tracked on an hourly basis and non-billable time is tracked on a percentage basis.  This Issue is intended to begin the development of a technical solution for this new policy.

## Intended Outcomes

* Testable version of Tock that allows the above described functionality
* Testing plan
* Road map to move into production

**Comment by wslack** [comment]
I think this can be a branch - I think the backend data can be the same, just with a different front end (though the conversions could get nasty).

**Comment by batemapf** [comment]
closing this issue and will start another with more limited scope that provides for a test of today's meeting outcome.
