### ISSUE TITLE
Tock Notifications should be contextually aware

### ISSUE THREAD

**Issue by rogeruiz** [18F/tock#777]
While the current implementation of the Tock Notifications in the browser are good enough to alert users, they aren't contextually aware of the work done in #769 around whether a user is late or not. It would be nice to have the `iconPath` in the notification swap if the user is submitting their time after COB on Friday. 

_Discovered in #769_

### Implementation sketch

- Add an API endpoint for the Notification code to call to determine if the current user is late
- Swap the `iconPath` variable for either HappyTock or AngryTock when alerting even if user keeps the tab open and doesn't reload the page.
- Add a submission Notification when user successfully submits their timesheet after an AngryTock notification.

**Comment by rogeruiz** [comment]
closed by merging #769

**Comment by tbaxter-18f** [comment]
@rogeruiz over time, I'm afraid some of the context has been lost here. Can you add some info on what we were trying to achieve and why?

**Comment by rogeruiz** [comment]
#769 created a `is_late()` method that isn’t being leveraged in the JavaScript that handles alerts via the Notifications API. 

Basically, the work here is about updating the Notification code for folks who keep Tock open in a browser tab. Make it work the way it should leveraging the `is_late()` method to make it change the icon. Right now it always uses the same icon.

**Comment by rogeruiz** [comment]
This is the notification code I’m mentioning. https://github.com/18F/tock/blob/68f9abb6f58419676527c58983d31f6a4dcdb9b7/tock/tock/static/js/components/notifications.js

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
