### ISSUE TITLE
Error submitting tock 

### ISSUE THREAD

**Issue by rrefoy** [18F/tock#780]
Had a saved timecard that I went to submit this AM and was met with the below error when I tried to submit. It also has the same error when I try to save.

<img width="1066" alt="screen shot 2018-04-16 at 8 54 34 am" src="https://user-images.githubusercontent.com/17129887/38811567-dbba5ed8-4157-11e8-94f5-475749e1d60f.png">

**Comment by ccostino** [comment]
Thanks for following up with me, @rrefoy.  So far we've ruled out the amount of hours being submitted, any deactivated projects, or things not set with the user account.

No error seems to be coming through in the logs at the moment, but this is definitely an issue with no error message being displayed here to indicate what's going on.

**Comment by ccostino** [comment]
It appears there's at least one problem with the [timecard template](https://github.com/18F/tock/blob/master/tock/tock/templates/hours/timecard_form.html#L84-L90) - it is referencing `non_form_errors` but perhaps that ought to be `non_field_errors` according to the [Django documentation on form errors](https://docs.djangoproject.com/en/1.11/ref/forms/api/#django.forms.Form.errors).  We should double check that non of the other error attributes need to be displayed, either.

**Comment by ccostino** [comment]
Just noting that @rogeruiz and I have been unable to replicate this issue so far after pulling a copy of production data and trying to retrace the steps.

**Comment by rrefoy** [comment]
Fwiw, when i went to save my new timecard, it worked without the error but the error still shows up in last week's time card.

**Comment by ccostino** [comment]
Oh interesting!  @rogeruiz did you submit @rrefoy's timecard last week on her behalf in the admin?

**Comment by rogeruiz** [comment]
I attempted to, and got the error showing up that they already have a timecard submitted. We have some time on our calendars to verify this info in real-time and get it cleared up. Though I'm not sure about the issue. We should keep it open and try to reproduce it. Rendering pages without error messages is a bad sign.

**Comment by ccostino** [comment]
Oh absolutely, that is a bug with the error message(s) that needs to be fixed regardless.  A bit frustrating it's come back!

**Comment by ccostino** [comment]
And that really shouldn't have happened with the duplicate timecard, so it seems there's still a potential breakdown somewhere with that.

**Comment by tbaxter-18f** [comment]
@ccostino, just to clarify, the only thing we know that is actionable here -- at least at this date -- is that we're not outputting form errors correctly, right?

**Comment by ccostino** [comment]
This should actually be fixed!  @rogeruiz and I both addressed the issues around this with several of the improvements and fixes we made to the timecard submission.  I know I at the very least fixed the display of the errors.

You should be able to test this yourself to verify if you try and submit a timecard with 0 hours or some other condition that would cause submission to fail.

**Comment by tbaxter-18f** [comment]
Oh, cool. If it's fixed I'll close and treat any future reports as new defects. I should have known you'd taken care of form errors already :-D
