### ISSUE TITLE
Add support for additional non-billable project lines for the General snippets report

### ISSUE THREAD

**Issue by ccostino** [18F/tock#781]
@joshuabailes had a request to change the General Snippets report to include the new 18F non-billable project line item instead of the old `General` line item.

We can actually include both (for historical reasons) and set things up for future flexibility should the need arise to account for additional non-billable line items in the report.

**Comment by joshuabailes** [comment]
Great!

Joshua Bailes
Chief Operating Officer, 18F
Joshua.Bailes@gsa.gov
202-550-6659
18F.gsa.gov <https://18f.gsa.gov/>

**Comment by ccostino** [comment]
Fixed with #782!  Once we're able to deploy changes again this will go live. :-)
