### ISSUE TITLE
API requests that take too long kill gunicorn workers

### ISSUE THREAD

**Issue by rogeruiz** [18F/tock#802]
We've discovered a few times that API requests that take too long, such as
`reports/timecards_bulk.csv`, return incomplete data or fail to return anything
at all.

When inspecting the logs, we find that the gunicorn worker is timing out:

```
   [APP/PROC/WEB/1] ERR [] [73] [CRITICAL] WORKER TIMEOUT (pid:76)
```

There are a few ways to rectify this, but for now we could simply set the
timeout in the `bin/run.sh` file to be somewhere around 300 seconds for these long
requests. Although @ccostino has a better suggestion to properly fix this up.

**Comment by ccostino** [comment]
The timeout will certainly work as a stop gap for now and I think it's okay to go forward with that for now.  Thanks for helping look into this, @rogeruiz!

If we're able to invest a bit more time into this and it'd be useful though, we should shift the report processing/generation to tasks that are run through [Celery](http://www.celeryproject.org/) or [RQ](http://python-rq.org/), which would run that code in separate processes that wouldn't take down the site or timeout and allow the reports to fully generate.  Furthermore, it'd provide flexibility for future growth if there are other reports we want to generate or any nightly refresh activities that should take place for automated maintenance, etc.

**Comment by tbaxter-18f** [comment]
Given that this doesn't appear to have been a problem for two years, I'm going to close it. If anyone disagrees, we can reopen.
