### ISSUE TITLE
Consider setting "Cache-Control: max-age=0" by default

### ISSUE THREAD

**Issue by toolness** [18F/tock#803]
I've been thinking about some of the login problems we've been experiencing with tock and filed https://github.com/18F/cg-django-uaa/issues/45 and https://github.com/18F/cg-django-uaa/issues/46 to help resolve them.

However, I also realized that it might behoove us to set an explicit `Cache-Control: max-age=0` header on responses by default, to ensure that weird problems don't eventually occur due to aggressive caches like CloudFront.

As far as I can tell, tock.18f.gov isn't actually fronted by CloudFront, but explicitly setting a `Cache-Control` header might still be a good idea (if only to prevent the user's own browser from caching too aggressively).

For an example implementation of this, see https://github.com/18F/calc/pull/1260.

**Comment by Jkrzy** [comment]
There hasn't been too much noise around login issues in the past few months. Closing this for now.
