### ISSUE TITLE
'Save Timecard' and 'Submit Timecard' should be visually distinguishable

### ISSUE THREAD

**Issue by pburkholder** [18F/tock#804]
I have on two or three occasions 'Saved' my timecard when I meant to 'Submit'

It might help to have them visual distinct to indicate that Submit is the critical element to act on.  Or, 'Save' could pull up an dialog element to say 

> Timecard saved. Be sure to submit hours by 08:00 EST [CONTINUE]

Thanks, Peter

**Comment by ccostino** [comment]
Good call, @pburkholder!  Will take a look and adjust this. :-)

**Comment by tbaxter-18f** [comment]
Given the improvements done in the related #807 I think this can be closed. If anyone objects, I'll happily reopen.
