### ISSUE TITLE
Create a "Tock is Down" page

### ISSUE THREAD

**Issue by annalee** [18F/tock#806]
We should have an "out of order" page we can put up if we need to take the app down on short notice.

**Comment by tbaxter-18f** [comment]
There are two ways I see this could work:
1. The app is down and this file is just statically deployed as index on root.
2. Django is installed and working correctly but for some reason we don't want people using the app, like perhaps it's too unstable, or there's some sort of maintenance going on.

It would be really slick if we could sort out how to automatically route to the static html if the app is down -- perhaps at the nginx layer?

For the latter issue, perhaps a setting that toggles the addition of middleware to capture the request and redirect to the static page?

Definitely open to ideas here.

**Comment by Jkrzy** [comment]
Easier to handle at the cloud.gov router, remapping route to maintenance app, I think. Maintenance app returning our "out of order" page to any request.

I believe CALC does it this way. https://github.com/18F/calc/pull/832

**Comment by tbaxter-18f** [comment]
Done with #830
