### ISSUE TITLE
on boarding @tbaxter-18f

### ISSUE THREAD

**Issue by rogeruiz** [18F/tock#821]
- [x] @tbaxter-18f has access to New Relic.
 - [x] @tbaxter-18f has access to the GitHub repository.
 - [x] @tbaxter-18f has access to SpaceDeveloper roles in Cloud Foundry for spaces staging and prod.
 - [x] @tbaxter-18f has been invited to #tock-dev in Slack.
 - [x] @tbaxter-18f is familiar with the deployment process of Tock.

**Comment by rogeruiz** [comment]
@tbaxter-18f are you familiar with the last item in the checklist here?

**Comment by tbaxter-18f** [comment]
Not at all.  I don't know about the SpaceDeveloper roles either.

**Comment by rogeruiz** [comment]
Take a look at this for more information on `SpaceDeveloper` roles in Cloud Foundry. https://docs.cloudfoundry.org/concepts/roles.html

As far as the deployment process, take a look at the [`.circleci/config.yml` file](https://github.com/18F/tock/blob/master/.circleci/config.yml). It contains the deployment process for staging and production along with the recycle process for redeploying the application once daily. 

Lastly, if you have any questions find some time on my calendar in the afternoon for 45-60 min and I can walk you through it. 👍

**Comment by rogeruiz** [comment]
Created in response to 18F/staffing-and-resources#529

**Comment by tbaxter-18f** [comment]
I believe this is complete now. Roger, if you disagree, please feel free to re-open.
