### ISSUE TITLE
Annual user recertification FY18

### ISSUE THREAD

**Issue by rogeruiz** [18F/tock#822]
Annual user recertification for FY18. This issue will be used to track the completion of this task. For now we will schedule some time in the coming weeks to have @abrouilette, @tbaxter-18f, and @rogeruiz (myself) to review Tock users.

**Comment by rogeruiz** [comment]
We'll be setting a meeting for next week starting Sept 4th.

**Comment by tbaxter-18f** [comment]
Meeting is scheduled for Nov. 9

**Comment by tbaxter-18f** [comment]
@rogeruiz @abrouilette and I met today and reviewed the users in Tock. We confirmed no users have superuser permissions they should not, and the list of users/employees who are asked to Tock each week appear to be correct. We did notice that there are some orphaned accounts in the system that should be cleared out, which @lsgitter and @keiawatkins will be handling in the coming weeks.

With that, I'm going to close this issue, with the usual note that if anyone feels it should be reopened please feel free to do so.
