### ISSUE TITLE
Update on timecard, what happens next?

### ISSUE THREAD

**Issue by jackiekazil** [18F/tock#83]
I found an error on my time card from 2 weeks so I made an update. 
Do I need to take further action? Should I reach out to someone? Did someone receive a notice? (I thought this was worth a ticket, because it will come up in the future.)

Timesheet for 04/05/2015 
/cc @batemapf

**Comment by batemapf** [comment]
thanks @jackiekazil
no further action needed.  we will need to come up with a policy / process that alerts us automatically when a timesheet from a prior period is edited.  will start an issue for that.
