### ISSUE TITLE
FY disallowed dates check bug

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#831]
In tock/hours/views.py we have a disallowed_dates check that ensures a reporting period spanning two fiscal years is not auto-generated:

"""
 If the end of the fiscal year is not on a weekend, then create
 a list of dates around (the buffer) the end of the fiscal year
 where a reporting period will not be automatically created. This
 prevents the automatic creation of a reporting period that has
 working week days that span two fiscal years.
"""

However, in this check, we're making sure the fiscal year start day is not in [5, 6, 1] (Saturday, Sunday or Tuesday). It should be [5, 6, 0] for Saturday Sunday or Monday, since those are the days in which the reporting period would be OK.

In the event that the check still fails, and in turn the create_reporting_period_if_missing function stops, we should probably figure out how to provide some useful feedback that the RP was not auto-created and will need to be manually created.

Note this will not be a problem again until FY20 rolls around, if then, so it can safely be considered
a low priority.

**Comment by adunkman** [comment]
Flag for review on what the expected behavior here is — I’d agree that there seems to clearly be a bug with zero-indexed weekdays, but unclear on what the correct fix is. 

From @Jkrzy via Slack: 

> I’m missing the context around this specific issue but it feels old enough that we should check-in with the #tock team and see how Reporting Periods  — and their automated creation — should be functioning.
>
> Particularly because — `Reporting Period: Sept. 29, 2019 to Oct. 5, 2019` — is a period in :happy-tock: that crosses FY boundaries.

**Comment by Jkrzy** [comment]
Not sure if this is still occurring, will check on FY21 and close if this hasn't re-occurred

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
