### ISSUE TITLE
Timecards may fail to save if related projects and profit_loss_accounts aren't input as expected

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#832]
If a project on a time card has a related profit_loss_account that does not have a start date, the timecard may fail to save. The exact code is in the TimecardObjects save() in tock/hours/models.py:

```
if p_pl and \
        p_pl.account_type == 'Revenue' and \
        p_pl.as_start_date < rp.end_date and \
        p_pl.as_end_date > rp.end_date:
            self.revenue_profit_loss_account = p_pl
        else:
            self.revenue_profit_loss_account = None
```
Which will blow up if it's comparing None (pl.as_start_date was never sent) and the rp.end_date date object.

**We'll know we're done when**
* We've determined if that start date should be required or not
* we've modified the code accordingly
* we've added in some graceful error handling so it doesn't just blow up and instead informs of the problem
* tests!

Note this is probably only an issue at the beginning of a new Fiscal Year or when a new profit_loss_account is created.

**Comment by tbaxter-18f** [comment]
From talking to @martyspence we can remove
```
p_pl.as_start_date < rp.end_date and \
        p_pl.as_end_date > rp.end_date:
```
and, for that matter we can remove start and end date on the profit loss account model.

But it's also worth noting this probably won't happen again until new PLAs are created for FY20.

**Comment by Jkrzy** [comment]
@martyspence, did we run into this again this past October?

**Comment by martyspence** [comment]
i did create new PLs with start/end dates this year. haven't run into any new timecard errors yet that I know of.

**Comment by tbaxter-18f** [comment]
I'm going to close this out, given we had no issue in FY20. If we run into a problem in FY21, we can tackle it then.
