### ISSUE TITLE
handler400 issues

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#842]
We have a custom 400 error handler defined, but there are a few issues:

1. We have no 400.html template so it _shouldn't_ work. Calling it would result in a 500 error.
2. We don't have a test that would have uncovered (1). We only found it by accident.

*We'll know we're done when:*
* Template created
* Tests written
* 400 errors are handled correctly

**Comment by Jkrzy** [comment]
Recommend we tackle this by falling back to the default Django handling of 400 errors, which renders the `400.html` template. No code required on our end.

https://docs.djangoproject.com/en/1.11/ref/views/#the-400-bad-request-view

**Comment by tbaxter-18f** [comment]
Joe, I think that's sensible. My bigger concern here was that we had written custom code that was incomplete, was untested, wasn't working, and only got caught by accident. I don't think I wrote the issue very well, but the real goal is handling 400 errors correctly (and knowing that they are). If we can get there by leveraging built-in Django functionality, even better!
