### ISSUE TITLE
Onboard jgrevich

### ISSUE THREAD

**Issue by jgrevich** [18F/tock#844]
## Team member checklist.
- [x] Generate a Tock API authorization token for the new developer.
- [x] Grant access to New Relic.
- [x] Grant access to the GitHub repository.
- [ ] Grant access to SpaceDeveloper roles in Cloud Foundry for `staging` and `prod` spaces.
- [x] Send invitation to #tock-dev in Slack.
- [x] Grant access to `GSATETockLibrary` and `GSATEUtilitiesLibrary` scripts.

## New developer checklist
You will need to be sure you have:
- [x] Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [x] Reviewed the [Tock deployment process](https://github.com/18f/tock/tree/master/docs/deployment-process.md).

CC @tbaxter-18f

**Comment by tbaxter-18f** [comment]
Justin, take a look at this for more information on SpaceDeveloper roles in Cloud Foundry. https://docs.cloudfoundry.org/concepts/roles.html

**Comment by tbaxter-18f** [comment]
@jgrevich what's still outstanding here?

**Comment by tbaxter-18f** [comment]
@jgrevich can this be closed out?

**Comment by jgrevich** [comment]
I'm all set, thank you @tbaxter-18f! I just need to familiarize myself with cloud foundry again.
