### ISSUE TITLE
Add employee_organization column to weekly report tables

### ISSUE THREAD

**Issue by acolter** [18F/tock#854]
For the reports by weekly reporting period (e.g., [https://tock.18f.gov/reports/2018-12-02/])(https://tock.18f.gov/reports/2018-12-02/) I would like to request adding a column for "Organization" to the Users Who Have Not Filed a Timecard!/Users Who Have Filed a Timecard! tables.

This would use the value in the employee_organization field: 18F, login.gov, cloud.gov, COE, TTS, OA, etc. I'm hoping this will make it easier to tell who we need to chase to fill in Tock (because from my perspective I'm only interested in chasing the folks on the 18F P&L).

**Comment by tbaxter-18f** [comment]
Resolved with https://github.com/18F/tock/pull/857
