### ISSUE TITLE
Update reports page for FY19

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#864]
On the reports page, we show FY17 and FY18, we can remove those, and need to add FY19

https://tock.18f.gov/reports/

**We'll know we're done when**
* FY17 and FY18 are removed
* FY19 is added

**Comment by amymok** [comment]
https://github.com/18F/tock/pull/847 should have added the FY19

**Comment by tbaxter-18f** [comment]
Thanks Amy! I forgot about that. So we can just remove the older years, which in turn means this is less urgent, and if we don't do it before our next deploy it's no big deal.

**Comment by Jkrzy** [comment]
@tbaxter-18f, can you re-confirm which FY should be available on the reports page?

Is it FY20  and FY19 now?

**Comment by tbaxter-18f** [comment]
I'm gonna go ahead and say yes, and if at some future date @saraheckert or anyone else wants to see historical data we can pull it manually or add it to the page.
