### ISSUE TITLE
Update weekly reports to show true expected hours

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#865]
Currently the individual weekly reports (such as https://tock.18f.gov/reports/2018-12-23/timothy.baxter/) are hard-coded to expect 40 hours in the "Reporting Period Summary". Instead, they should use 40 - any OOO time, then calculate the true expected percentage of utilization from that.

**Comment by acolter** [comment]
Would love to bump this up in the prioritization.

**Comment by adunkman** [comment]
> 40 - any OOO time

Do we have a definition of what “any OOO time” would be? I’m not super familiar with Tock’s codebase, but would that just be selecting certain Tock lines?

**Comment by tbaxter-18f** [comment]
Good question, @adunkman. We could probably capture a list of the OOO tock lines pretty easily, but I wonder if it could be so simple as checking if it contains `OOO` or `out of office`

**Comment by acolter** [comment]
The only Tock line we use in 18F is 18F Out of Office.

**Comment by tbaxter-18f** [comment]
Angela, we have other parts of TTS using Tock don't we? Will that work?

**Comment by acolter** [comment]
They do, but nobody else uses it to track staff utilization.

**Comment by tbaxter-18f** [comment]
@Jkrzy we've got this covered with the utilization changes, don't we?
