### ISSUE TITLE
Show total non-billable time

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#866]
On a user page (like https://tock.18f.gov/employees/e/timothy.baxter/) we should combine 968 non-billable and 969 GSA-mandated into a single true non-billable block in the utilization chart.

**Comment by davemcorwin** [comment]
@tbaxter-18f the data comes straight from the project timeline csv report, should the report itself change or should the chart logic handle combining the line items?

**Comment by davemcorwin** [comment]
@tbaxter-18f I'll hold off on this until further notice.

**Comment by tbaxter-18f** [comment]
@Jkrzy I'm thinking this doesn't make much sense anymore, especially in light of the utilization work and the removal of the visualizations. Thoughts?
