### ISSUE TITLE
Update USWDS

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#867]
Tock is using an older version of the USWDS, and may be overriding it more than is necessary. In addition, SNK reports the older version (1.6.9) is introducing a JS vulnerability: 

https://app.snyk.io/org/gsa-18f-tock/project/ab6d14c1-3a1b-43c9-ab25-bca0d9a9db9e/

**We'll know we're done when**
* USWDS version in use on tock is updated to current versions
* Unnecessary USWDS overrides are removed.

**Comment by tbaxter-18f** [comment]
Thank you @hbillings for pitching in to help!

**Comment by hbillings** [comment]
@tbaxter-18f you know it!!

It looks like `1.6.9` is actually the latest version of the `1.x` series. Do we want to investigate adopting the `2.x` upgrade?

**Comment by hbillings** [comment]
(Also, I can't access that Snyk report -- it says I don't have permission to view.)

**Comment by tbaxter-18f** [comment]
After talking with Heather and looking at USWDS there are pros and cons to adopting both the 1.6.x and 2.x branches, and the USWDS team is currently furloughed. Heather is going to investigate and choose a path forward.

**Comment by tbaxter-18f** [comment]
After talking with @hbillings more, it looks like 2.x would be a pretty huge lift right now, especially since it's only in beta. We're recommending we move up to the 1.x trunk and stick with that for awhile.

Heather won't have capacity to do this for awhile, though, so it is once again open for anyone to pick up.

**Comment by adunkman** [comment]
Looks like @cantsin is on this — going to drop you in as an assignee so others don’t pick it up! Thanks for the WIP PR!
