### ISSUE TITLE
Audit and document what admin controls do

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#873]
There are several checkboxes and inputs that need to be entered correctly when an employee onboards, offboards, or just changes status, and if any of them are not entered correctly all sorts of mayhem results. 

So we should take a look at the reports and checks, investigate how they tie back to the admin controls, and document the whole thing.

### We should also watch out for 
- Misleading form labels
- Form controls that don't actually do anything
- Form controls that should be required but aren't

### We'll know we're done when
- Reporting checks and the related controls are documented.
- Form labels are clear and accurate (or a follow-up issue logged to change them)
- Required form controls are required (or a follow-up issue logged to change them)

**Comment by Jkrzy** [comment]
Continuing conversation from #926

@tbaxter-18f said...
> My opinions, for whatever they're worth, based on my understanding of general django concepts:
> 
> 1. No one should be a superuser except Tock core devs
> 2. is_staff is conventionally the expected pathway to the admin
> 
> Not saying that's how we have to do it that way, just clarifying the expectations I'm coming to the conversation with.

I propose we create 3 groups to manage permissions

## Groups

### Developer
A user who has been onboarded per the development documentation. Superuser and therefore has complete and unrestricted access

### Administrator 
A user who updates users, timecards, reporting periods, timecard notes, etc, Has *all* Tock model and specific permissions including access to the admin.

Ops folks like Matt S. and @saraheckert would be part of this group.

### Reporter
A user who has access to the utilization reports


## Django User attributes
&nbsp;|Developer|Administrator|Reporter
---|---|---|---
|SuperUser|Yes|No|No
|Is Staff|Yes|Yes|No|

**Comment by tbaxter-18f** [comment]
That sounds good. I'm not sure I'm seeing the distinction between Reporter and plain old User, but I think those sound like fine groups.

**Comment by Jkrzy** [comment]
Currently, only folks with `is_staff` can access the Group Utilization reports, -- https://tock.18f.gov/utilization/. 

People needing access to that report but not the admin would be assigned the `Reporter` group.

I'm also absolutely open to other names and/or assessing if that page is still useful 😄

**Comment by tbaxter-18f** [comment]
Nope that makes sense. I only wonder if it would make sense to drop the is_staff check and just make it visilble to any User, but I'm ok with a new Reporter role, too. Sounds good.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
