### ISSUE TITLE
Investigate ability to Tock in advance

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#874]
We're not entirely sure what would be required here (hence the investigation) but the goal would be some mechanism that would allow me to Tock for the future, with the most common (maybe only legitimate) use case being able to say "I'm tocking 40 hours OOO next week, cause I'm on vacation"

### We'll know we're done when
* Potential mechanisms to achieve the above are investigated
* Findings are documented
* Follow-up issues logged as needed.

**Comment by tbaxter-18f** [comment]
This seems pretty reasonable to me. I think we shouldn't expose the future reporting periods to the user at all, and the "future tock" form should probably just be "I'm [OOO|On Leave] until [date] which would then create tock issues for [OOO|On Leave] through the end date.

That sounds fully supported and I think it might get us away from having to add the `tock_in_advance` boolean, albeit with a slightly tricky new FormView.

I'd like to hear thoughts from @Jkrzy, @abrouilette and (if he has any spare time) @rogeruiz

**Comment by tbaxter-18f** [comment]
Since it would just be a tock submission, same as current week, we could use the existing change request form with no changes, right @cacraig ?

**Comment by Jkrzy** [comment]
Awesome @cacraig! A few thoughts...

- We'd need to handle weeks w/ holiday or other pre-fills
- 👍 to @tbaxter-18f's approach on the form interface for this. 
- There's multiple OOO tock lines, unless we can divine which a person should use, we'll need a flag as recommended by @cacraig to ID projects which can be `future-tocked`
- I'd like to see  `ReportingPeriod` generation refactored out of  the view function `create_reporting_period_if_missing` and onto the model @ `ReportingPeriod.get_or_create` allowing us to generate `ReportingPeriod` instances as needed.
- If we limit `future-tocking` to entire `ReportingPeriods`, maybe all we need from the user is the number of future `ReportingPeriods` to tock as opposed to an end date. Thereby avoiding the calendar math and feedback cycle of "this isn't a complete ReportingPeriod"

**Comment by tbaxter-18f** [comment]
Thanks Joe. Those are good points.

In my opinion, we shouldn't make holidays or pre-fills be a blocker to this, but I think we'd have to make it clear that if there is a holiday they would _have_ to be manually corrected and resolved in the admin, and be sure that's OK with everyone. Holidays do complicate this effort quite a bit.

As I think about holidays, and incomplete reporting periods, and other factors, though, I start to wonder if this may not be the right approach. I wonder if instead, we might have an admin function along the lines of an admin datefield with "`tock_exempt_until`" that we simply use for outputting angry tock. An Admin would have to set it for each user that's exempt, rather than being something a user could do for themselves, but it would sidestep incorrect or otherwise goofy ReportingPeriod entries. On the other hand, if the admin has to do it, is it really different than them going in and unchecking the relevant checkboxes in the admin, other than having a built-in expiration time, so you don't have to remember to go in and re-check the box.

At any rate, I think validity of the ReportingPeriod and how we handle holidays and other non-tockable days are pretty significant questions. I think the python `calendar` module can help us work around some of those, but not all of them.

Further opinions and thoughts are welcomed.

**Comment by abrouilette** [comment]
Are we gauging the effort required to correct things vs the effort required to do them for folks in the first place?

**Comment by tbaxter-18f** [comment]
I think we certainly need to. @Jkrzy raises some really good points. Making this thing smart enough to understand future untockable days feels tricky at best. My concern is that it will submit a bunch of future tocks that are not only incorrect but are also fairly hard to track down. 

That's my thinking behind the alternate approach, in which the user didn't submit anything but an admin has said they temporarily don't need to. I'm just not 100% sure it's actually much of a solution.

**Comment by Jkrzy** [comment]
@tbaxter-18f on second thought, `untockable` days might not be an issue. We're not currently differentiating between closure/leave/holiday/leave OOO. 

If that distinction isn't necessary, we don't need to worry about prefills for a `future-tocked` period.  It would be all OOO in any case.

**Comment by tbaxter-18f** [comment]
@abrouilette Here's a summary of two approaches we could take and the relative merits:

1. As @cacraig has outlined above, we could leverage existing mechanisms and allow users to actually create future tock timecards, in future reporting periods. This would be limited to them being able to Tock to OOO or, if we really want to, select non-billable Tock lines they may be detailed to. This is all completely doable, but it will get very messy very quickly if we (a) start to differentiate different types of OOO time (like holiday vs vacation vs family leave) or (b) we start to care if they're detailed somewhere and there's a holiday or other OOO in there. So long as we're not concerned about those things, @cacraig has a really solid plan here.

The alternate approach I suggested would just let an admin say "this person isn't tocking until X date" from within the admin, and then we'd just skip over them in the report. That's doable, too, but honestly, I'm not sure it's worth the effort. You can do the same thing today by unchecking a single checkbox.

Your thoughts?

**Comment by abrouilette** [comment]
One question only (because I am not nearly smart enough to understand all of what @cacraig wrote): Is this an easy rollback if someone Tocks a week of OOO time and then needs to rescind it wholly or in part?

**Comment by tbaxter-18f** [comment]
I think in that case we'd handle it like any Tock change request.

**Comment by tbaxter-18f** [comment]
@cacraig: Alan and I spoke today and agreed your plan is the best. Can you go ahead and log the necessary follow-up implementation issues, after which we can consider this investigation complete?

**Comment by tbaxter-18f** [comment]
Since #889 is now logged, I'll close this out and we'll pick it up again there.
