### ISSUE TITLE
Offboard commit-dkp

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#875]
Thanking @commit-dkp for his service and running through the offboarding checklist. 

- [x]  They no longer have access to New Relic.
- [x]  They no longer have access to SpaceDeveloper roles on cloud.gov for spaces `staging` and `prod`.
- [x] Rotating of secrets they had access to:
  - [x] Rotation of cloud.gov service provider Service Keys.
  - [x] Rotation of cloud.gov identity provider Service Keys.
  - [x] Rotation of New Relic API key.

**Comment by rogeruiz** [comment]
@Jkrzy there's potential for downtime with the rotation of the `identity provider` Service Keys if you delete them before the production systems have a chance to deploy with the updated keys.

**Comment by tbaxter-18f** [comment]
Suggested adds:

[ ] staff status removed in Django admin
[ ] Tock API keys removed in Django admin

Both of those _should_ happen automatically when they're marked as not an employee in the "employee" model, but it doesn't hurt to check.

In this particular case, both have been checked.

**Comment by tbaxter-18f** [comment]
Done
