### ISSUE TITLE
Create "Billable Progress Meter" where data visualizations currently live

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#880]
After we remove the existing data visualizations in #879 there is a desire to instead provide a more meaningful "Are we where we should be for billable hours" progress meter that would be in place on the organization-level and employee report pages. So, for example, if i'm supposed to have 1600 billable hours for the FY (32x50) it would show my progress toward that goal for the year.

To do this, we'll have to add a field to the employee model to note their expected billable hours per week, since that can vary from person to person, and we'll have to populate that in the admin. We may be able to set a default of 32 for most people and then just adjust the ones that aren't 32.

We'll also need to determine the exact math we want to use to represent the target.
And we'll want to pull in some design help for a very-simple-yet-meaningful way of illustrating this, that _won't_ require a ton of dev work to build.

### We'll know we're done when
* New billable hours target field is added to model
* DB migrated
* Field is populated correctly for everyone
* Math is determined and documented 
* Visualization is designed
* Progress meter shown on front-end
* Documentation/explanations added
* Tests are written

**Comment by tbaxter-18f** [comment]
@jenniferthibault How are we looking at finding a little capacity for this?

**Comment by jenniferthibault** [comment]
Folks from visual design are all booked up with either full time project work, or other prioritized non-billable commitments.  I'll hustle around for other design folks and will let you know!

**Comment by jenniferthibault** [comment]
Nada this week. 
One way this might get a little more traction is if you can break the issue up into smaller pieces, and separate the database/data model tasks from the front end work. If you put a design-specific task into the [design lab repo](https://github.com/18F/design-lab) that'll make it easier for design folks looking for non-billable pickups to find it

**Comment by tbaxter-18f** [comment]
Thank you Jen! Logged https://github.com/18F/design-lab/issues/52 to coordinate with design-lab.

**Comment by Jkrzy** [comment]
Summing billable and non-billable hours is straightforward:

```python
TimecardObject.objects.filter(timecard__user=user, timecard__submitted=True, project__accounting_code__billable=True).aggregate(Sum('hours_spent'))
```

Figuring out the target billable or denominator is more complicated, thinking out loud....

- Billable expectations for a user **may** vary throughout the FY (e.g. staff to supervisor transition)
- Weekly Billable expectations **will** vary  (holidays, PTO?)

Therefore, we need a weekly view of billing expectations for each user

Given a weekly `(billed / expected)` view, we can sum across weeks for the overall picture.

**Comment by tbaxter-18f** [comment]
@saraheckert do you think it would be adequate to just put a target number, knowing that if it were to change during the year (transition to a super role or whatever) then the rolling average would be off for a few weeks. 

I _think_ that would be ok, but what do you think?

**Comment by saraheckert** [comment]
Yes, a target percentage would work.  We should be able to adjust the number of billable vs. non billable hours for each person depending on their role.  The percentage should remain unchanged as utilization would take only from those available billable hours.  I would set the lowest bar at 62% which is the minimum number for the org.

**Comment by saraheckert** [comment]
Now that I have more time to review this entire request over, I am looking at some of the reports I also receive from Matt.  He has been able to back out the out of office hours that include holidays and such.  In our reports, we call this field "Utilization minus OOO / Micropurchase work."

@Jkrzy I was reviewing this formula: For a given week and user, the billable target then becomes: (total_hours_tocked * timecard.billable_expectation).  Would the billable_expectation include the OOO hours backed out?

**Comment by Jkrzy** [comment]
@saraheckert Yes, apologies that wasn't clear.

It should read: `( (total_hours_tocked - ooo_hours_tocked) * timecard.billable_expectation )`

I think I've got enough to go on, let me circle back here with an MVP.

**Comment by saraheckert** [comment]
wonderful, thank you so much @Jkrzy

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
