### ISSUE TITLE
Enforce project line submission at timecard submission

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#881]
In some cases, somehow, when a user submits a timecard the project lines will not be marked as submitted. This will present to the user as an undefined error, and can be seen in the admin by the project lines having red "unsubmitted" checks when the timecard itself has been entered.

We need to determine why the project lines have their own "submitted' independent of the timecard "submitted'. If they're not needed, remove them. If they are, be sure that they're in sync and don't throw an error.

**Comment by Jkrzy** [comment]
I've been unable to replicate inconsistency between `Timecard.submitted` and TimeCardObject.submitted`. 

However I don't believe a discrepancy there would prevent submission of a Timecard.

`TimeCardObject.submitted` is functionally a copy of `Timecard.submitted` and any instance where it is evaluated should be replaced with `timecard__submitted`. It looks like the only place its used at the moment is in the utilization reports.

**Comment by tbaxter-18f** [comment]
Yes, timecard.submitted is definitely used. You can see the inconsistency if you force an error on a tock submission  -- apparently, judging from Slack conversations, leaving out required notes is the easiest way -- then view the submission in the Tock admin. You'll get a "submitted" timecard with unsubmitted timecardobjects.

That said, I understand you'd prefer to pull that work into a separate issue, which I'm totally fine with.

**Comment by tbaxter-18f** [comment]
@Jkrzy is this resolved with the merge of #886 above?

**Comment by Jkrzy** [comment]
No, thanks for the reminder @tbaxter-18f  that didn't address an assessment/refactoring of `TimeCardObject.submitted`. I'll follow-up later this week with a plan to close this issue.
