### ISSUE TITLE
Handle unique_together validation errors on timecard submission

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#887]
Users submitting a timecard which violates the `TimeCardObject` unique_together constraint are unable to submit/save and not provided with a useful error message or any direction on how to resolve the issue. 

In practice this happens when users attempts to swap `Project` values between tock lines on a saved `Timecard` and then submits or saves.  

This one is super frustrating for users as it prevents submission, provides no helpful error message, and presents the user with the invalid form for resubmission.  

### We'll know we're done when
* All `non_field_errors ` are rendered on the timecard submission page
* Users are able submit and save timecards when swapping `Project` values between tock lines

**Comment by Jkrzy** [comment]
The root cause of the validation failure here is obscured from the user by Django's inline formset and model validation mechanics. Even if the default error message, `Timecard object with this Timecard and Project already exists`, was displayed the submitted data appears valid to the user.

### Proposed fix

To maintain the existing user workflow, leverage core Postgres functionality, and allow submission of Timecards which, as a whole, are valid we will:

* Bypass Django's `unique_together` model validation by overriding `TimeCardObjectForm.clean` without calling the parent classes's `clean()`
* Process incoming `Timecard` formsets in a transaction with `DEFERRED` constraints, allowing intermediate table states to violate the `UNIQUE` constraint if needed.
  * Django doesn't allow specification of `UNIQUE` constraint behavior on creation and the Postgres default is `NOT DEFERRABLE`
  * We'll need to re-create the constraint as `DEFERRABLE`. 

### Why this doesn't work as-is
`TimeCardObject` records  must be unique by `Timecard` and `Project`. This is intuitive, as we only want one entry per `Project` on a timecard. This restriction is implemented at both the Django model and database level.

#### Django's validation
Inline formsets allow users to modify multiple model instances with a single POST by processing a set of `ModelForms`. 
In validating a submission, Django checks `unique_together` separately for each incoming `ModelForm` instance. Although the incoming `Timecard` as a whole is correct and upon commit would result in a valid submission, Django's row/statement level unique validation prevents success.

#### Postgres validation
Django's `unique_together` is implemented in Postgres as: 
```sql
ADD CONSTRAINT hours_timecardobject_timecard_id_project_id_b3d0a465_uniq
    UNIQUE (project_id, timecard_id)
```
`IntegrityErrors` are thrown by this as Django attempts to save each incoming `ModelForm`  with separate statements.


### A few others considered approaches:
* Remove the `unique_together` constraint
  * Would require rolling our own validation on the model and form
* Prevent these types of submissions by rendering existing `Timecard` project entries as disabled/readonly
  * Shifts burden to the user and changes their workflow
* Catch validation failures and handle ourselves w/ a placeholder value
  * Adds extra database hits and requires required code is a bit hacky

**Comment by tbaxter-18f** [comment]
Resoved with merge of 886
