### ISSUE TITLE
Implementation - Tock in Advance

### ISSUE THREAD

**Issue by cacraig** [18F/tock#889]
"Tocking" in advance was explored in: #874 

**Identified use cases:**

(1) A person going on Detail for an extended period of time.
(2) A person going on Leave for an extended period of time >1 week.

**Outcome**

An Admin - should be able to tock in advance for any reason.
A User  - should be able to submit tock reports in advance if the report is 100% OOO, or Detail. 

**Implementation**

- An Admin can create reporting periods in advance. This is already supported.
    - ReportingPeriodListView.create_reporting_period_if_missing - could be extended to create more reporting periods ahead of time (Maybe 8 periods in the future?).
- An Admin can already edit/submit timecards early with any project code or hours - assuming the reporting period has been created.

Add query for selecting not yet submitted reporting periods (ReportingPeriodListView) where the start date is in the future.

Add an additional header below “Reporting Periods You Need to Fill Out“, and show these future periods - maybe, “Future Reporting Periods“.

Future reporting periods should only be Tockable in advance by a user if they are 100% OOO or on Detail.

- Add a boolean field to Project model ‘tock_in_advance’  
    - TRUE  = Can be tocked in advance
    - FALSE = Cannot be tocked in advance 
- An Admin should be able to change the ‘tock_in_advance’ field in the Admin dashboard (Project). Should be also be a checkbox field when creating a new Project.
- When a user is submitting a future report (start date > today), verify that the report contains only tockable codes where “tock_in_advance” = TRUE. Reject if it contains anything else. 
    - (1) Check if start date is in the future
    - (2) Does report contain 100% codes with “tock_in_advance” = TRUE

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
