### ISSUE TITLE
Onboard Tim

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#899]
Welcome and thanks @timothy-spencer!

Lets work through this per https://github.com/18F/tock/blob/master/docs/onboarding.md 

- [x] Generate a Tock API authorization token in the admin for the new developer.
- [x] Grant access to New Relic.
- [x] Grant access to the GitHub repository.
- [x] Grant access to SpaceDeveloper roles on Cloud.gov for `staging` and `prod` spaces within the  `gsa-18f-tock` org.
- [x] Send invitation to #tock-dev in Slack.
- [x] Grant access to `GSA_TE_TockLibrary` and `GSA_TE_UtilitiesLibrary` scripts.
- [x] Grant access to `gsa-18f-tock` org on Snyk.

**Comment by Jkrzy** [comment]
Hey @timothy-spencer, almost through the prep checklist above. Feel free to get started here when able.

## New developer checklist
You will need to be sure you have:
- [ ] Familiarized yourself with the systems and scripts your onboarding partner has granted access to
- [ ] Reviewed the [Tock deployment process](https://github.com/18f/tock/tree/master/docs/deployment-process.md).

**Comment by timothy-spencer** [comment]
OK.  I think I'm done with most of the cloud.gov stuff, so I'll get re-engaged with this stuff now!

Sorry for me dropping out of sight there for a day or so, I kind of went into autistic mode there to try to finish the cloud.gov stuff up so I'd have space for this!

**Comment by timothy-spencer** [comment]
Hmm.  I don't seem to be a part of the cf org yet.  Did that get missed?

**Comment by Jkrzy** [comment]
Granted @timothy-spencer  access to the cf org. Closing this out once he's had a chance to `Familiarized yourself with the systems and scripts your onboarding partner has granted access to`
