### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by vzvenyach** [18F/tock#9]
Picking up @mbland's issue from [abb](https://github.com/18F/abb/issues/6), integrate snippets into the timecard as an optional (?) ManyToMany relationship.

**Comment by seanherron** [comment]
This could also just be an additional field on `TimecardObject` entry (if we wanted to do different fields for each object in a timecard) or on `Timecard` (if we wanted one snippet for the whole thing).

**Comment by jpyuda** [comment]
I'd say not optional. If somebody puts 90% of their time into, say, 18F General, I'd like to know what they were doing. ;)

**Comment by quepol** [comment]
As a user, if I choose 18F General as a time category, I would like a way to provide an explanation of the work done.

=)

**Comment by jgrevich** [comment]
I agree, this would be good to have as an optional field for any `TimecardObject`, not just `18f General`. To @jpyuda's point, it would be nice if people document aberrations for any entry.
