### ISSUE TITLE
Show latest periods with hours logged in Users

### ISSUE THREAD

**Issue by acolter** [18F/tock#900]
It would be useful to see a users last several weeks of timesheets. 

In the same way you can see who tocked how many hours per week on a project -- e.g., [https://tock.18f.gov/projects/848/](https://tock.18f.gov/projects/848/) -- let's have the ability to see which projects a person tocked each week: 

- column labels = week beginning dates for the last 4 or 5 weeks
- row labels = tock numbers (or tock descriptions)
- data cells = number of hours per week for that tock line

So for https://tock.18f.gov/employees/melissa.braxton/ you might display: 

![image](https://user-images.githubusercontent.com/9788211/59149921-d4145b80-89e9-11e9-80c4-38d102bf4798.png)

**Comment by tbaxter-18f** [comment]
@acolter would you be OK with pivoting that table, so the rows are the dates?

**Comment by acolter** [comment]
That would work for most folks, but would it work for people who are billing 6-8 projects at a time? 

I also found the page on Tock that shows all the 18F OOO time, which kind of solves my immediate need: https://tock.18f.gov/projects/670/
