### ISSUE TITLE
Guidance for Login Team Members when tocking their time

### ISSUE THREAD

**Issue by akhlaqkhan** [18F/tock#901]
Login has drafted internal guidance for our team to tock their hours properly across the multiple tock lines that we have in our program. We'd like to link this in tock just for login folks, maybe show it as a "tip" to checkout the guidance before tocking their time. Note that this is only applicable for FY19 so this should not appear after that. Please communicate the level of effort, cost and estimated timeframe before starting work on this.

Tock/Time Split Draft Guidelines: https://docs.google.com/document/d/1xFkooZQLzOjpaz3nHcNcoiW3Uo5uYmIwgOhbi3s5ojM
Demo slides shared to the team for walk through: https://docs.google.com/presentation/d/1yKihc_M1_AIpcdw_fiLX7hRecDklxZUTnT0FSF_c-nA

**Comment by lauraGgit** [comment]
In addition to an alert that might look a bit below. It would be great to have the tock lines prepopulated for those on the 18F in the p&L.

![image](https://user-images.githubusercontent.com/5840989/59298094-c06e2c80-8c57-11e9-8633-dd1decb69b3f.png)

```
      For login.gov members, please tock 45% of your time to the Login.gov authentication 1053 Login.gov P&amp;L_IAL2 and 55% with 1102 Login.gov P&amp;L_LA. For more information please see: <a href="https://docs.google.com/document/d/1xFkooZQLzOjpaz3nHcNcoiW3Uo5uYmIwgOhbi3s5ojM/edit#">Guidance</a>.
```

**Comment by adunkman** [comment]
> Note that this is only applicable for FY19 so this should not appear after that.

This appears to be out-of-date, closing — but feel free to re-open should I be wrong! 👍
