### ISSUE TITLE
determine scope/ownership

### ISSUE THREAD

**Issue by afeld** [18F/tock#924]
Creating as a placeholder issue for conversations that have been had many times in many places. Please add links.

## Open questions

- Should Tock (continue to?) be used TTS-wide? Or should it be scoped more narrowly (like only 18F)?
- What is the data actually being used for?
- Does it still make sense for everyone who currently needs to log time every week to continue to do so? Could that information be derived?
- What functionality / use cases can be cut out?
- Who should maintain it long-term?

These are big questions, so it may make sense to split some out into their own issues.

## Links

- [Most recent Slack thread](https://gsa-tts.slack.com/archives/C2L9V7K47/p1573242584003100)

**Comment by afeld** [comment]
https://gsa-tts.slack.com/archives/C2L9V7K47/p1592581001033200

**Comment by Jkrzy** [comment]
Answers as I understand the world at this moment 😅 

> Should Tock (continue to?) be used TTS-wide? Or should it be scoped more narrowly (like only 18F)?

Yes, at least 18F, Login, and CoE are using it to track/manage/report billable hours against active agreements

> What is the data actually being used for?

Varies by org but, tracking of hours (billable and non). 18F has more broad uses/reporting than other parts of TTS.

> Does it still make sense for everyone who currently needs to log time every week to continue to do so? 
> Could that information be derived?

Maybe, but each org within TTS will need to decide. For example, [Login recently reduced the scope of the hours they track in Tock.](https://gsa-tts.slack.com/archives/C5AUR5XUK/p1596809818074100)

> What functionality / use cases can be cut out?

None that immediately come to mind at the application level but I think fails under the response above as well.

> Who should maintain it long-term?

I _believe_ Tock is funded at the TTS level but 18F, as the creator and biggest user, has dedicated hours/week from a few folks to ensure the ongoing feeding and care for Tock. 

We (18F) are happy to continue on this course but are also ready and willing to invite our Tech Portfolio friends into the mix

**Comment by afeld** [comment]
> We (18F) are happy to continue on this course

Honestly, this is what I was looking for. Going to consider this issue closed for now. Thanks for the responses!
