### ISSUE TITLE
Onboard James T

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#937]
- [x]  Generate a Tock API authorization token in the admin for the new developer.
- [x]  Grant access to New Relic.
- [x]  Grant access to the GitHub repository.
- [x]  Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x]  Send invitation to #tock-dev in Slack.
- [x]  Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x]  Grant access to gsa-18f-tock org on Snyk.

**Comment by Jkrzy** [comment]
Hey @cantsin, welcome to :tock: and thanks for your help!

Feel free to get started here when able.

### New developer checklist

- [ ]  Familiarize yourself with the systems and scripts your onboarding partner has granted access to
- [ ]  Review the Tock deployment process

**Comment by Jkrzy** [comment]
All set with the access checklist for @cantsin

**Comment by cantsin** [comment]
Thank you for all the help regarding onboarding, @Jkrzy !

**Comment by lauraGgit** [comment]
@cantsin Can you please confirm that you still have access to the items on the checklist above?

**Comment by cantsin** [comment]
@lauraGgit I confirm I have access to everything... except Snyk. It gives me `The organization does not exist, or you do not have permissions to access it.` so I must have lost access at some point.
