### ISSUE TITLE
Explore approaches to automate manual application log reviews

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#944]
Tock developers currently conduct manual weekly application log audits, https://github.com/18F/tock/blob/master/docs/logging.md#tock-log-auditing

As a Tock developer, I want these audits to be automated so that manual application log reviews are no longer required.

## We'll know we're done when
- Blockers to automating this process have been identified
- If possible, a path towards automation has been proposed
- We've recognized opportunities to share AU-6 automation approaches with other users of cloud.gov

**Comment by tbaxter-18f** [comment]
Joe, what's the thinking behind moving this to icebox?

**Comment by cryptofilegsa** [comment]
For reference, AU-6 has a lot of moving pieces, ten of them are here:
https://nvd.nist.gov/800-53/Rev4/control/AU-6

**Comment by cryptofilegsa** [comment]
As a middle step between full manual query and fully automated, it is nice to use visualization so that large amounts of data can be scanned by looking at an image by the audit.  The kibana visualizations may provide a way to address?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
