### ISSUE TITLE
Audit and clean-up python dependencies

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#947]
~`django-webtest` is no longer in use by Tock.~

~It should be removed from the `Pipfile` and we should take this opportunity to purge any other included dependencies which are no longer in use.~

Django webtest is in use. We'll close this issue out on completion of inventory of current python dependencies.

## Known issues
~`django-webtest` is no longer in use by Tock but it is still installed as a dependency~

## We'll know we're done when
~- [ ]  `django-webtest` has been removed~
- [ ]  We've confirmed all other python dependencies are actively used

**Comment by cryptofilegsa** [comment]
packages
- [ ] django = "~=2.2"
- [ ] dj-database-url 
- [ ] gevent
- [ ] gunicorn 
- [ ] whitenoise 
- [ ] djangorestframework 3.8
- [ ] djangorestframework-csv 
- [ ] bleach 
- [ ] newrelic 
- [ ] cfenv 
- [ ] cg-django-uaa 
- [ ] psycopg2-binary
- [ ] markdown 
- [ ] django-webtest 1.9

development packages
- [ ] bandit 
- [ ] coverage 
- [ ] django-debug-toolbar 
- [ ] django-webtest
- [ ] factory-boy
- [ ]  flake8
- [ ] nplusone
- [ ] codecov

**Comment by cryptofilegsa** [comment]
Summary:

checkmarks above mean in-use and recommend leaving in place or keeping updated to current version.


codecov support for codecov.io seems more like an external dependency than something needed int he project, not aware of and codecove use and would like to remove.

remove django-debug-toolbar, do not have evidence of anyone using that

bandit replaced by either snyk or github security scanning or both so remove?

coverage is already included so would like to run that and get a sense of the analysis it provides

**Comment by Jkrzy** [comment]
A few notes:

`codecov` and `coverage` are in use within the circleci pipeline to generate coverage reports.
`django-debug-toolbar` supports local development
`bandit` is a static code analyzer, not replaced by Snyk or Github

**Comment by Jkrzy** [comment]
Original issue was incorrect, `django-webtest` is in-use throughout the test suite. e.g. https://github.com/18F/tock/blob/b6ddb1a42f29b450c933b35e13e7495b2c60b993/tock/utilization/tests/test_views.py#L7

Update issue to reflect.

**Comment by Jkrzy** [comment]
Thanks @cryptofilegsa! The un-checked packages are in active use, we'll leave them there now.

But it does look like there's an opportunity to update our versions for more than a few dependencies.

**Comment by cryptofilegsa** [comment]
this was addressed in: https://github.com/18F/tock/commit/665952a4d2b19f1761bc05147bc2c4425d0e6d6b
