### ISSUE TITLE
Render billable time expectations on timecard form

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#949]
Let's bring together the work of https://github.com/18F/design-lab/issues/52, Issue #880, and PR #940 to enhance the Timecard submission form to communicate expectations and progress towards billable time.

https://github.com/18F/design-lab/issues/52 contains potential visual representations of this information.

PR #940 makes available, in javascript, the data necessary to calculate target billable hours.

## We'll know we're done when

- [ ] Users are presented with the information necessary to understand how many hours they're expected to Tock to `billable` projects for a given week and how that number is calculated.
- [ ] Progress towards the target billable hours is updated as tock lines are completed on the form.
- [ ] Users are directed to the #tock and the [handbook](https://handbook.18f.gov/tock/#weekly-billable-hour-expectations) if they have questions re: target billable hours.

**Comment by tbaxter-18f** [comment]
🥇
