### ISSUE TITLE
Migrate away from Snyk

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#950]
We're currently using both Github Security and Snyk to monitor dependencies. Reports have been comparable.

In an effort to consolidate our Dependency Analysis tooling, let's move entirely to Github Security as our sole provider of Dependency analysis/scanning.

## We'll know we're done when

- [ ] Snyk integration has been removed
- [ ] Snyk account has been deactivated: https://app.snyk.io/org/gsa-18f-tock
- [ ] Documentation has been updated
- [ ] Compliance documentation (SSP) has been reviewed and updated if necessary

**Comment by tbaxter-18f** [comment]
Does this have any ATO implications? Do we need to chat with Susan Frederick first?

**Comment by Jkrzy** [comment]
So long as we're still implementing the [RA-5: vulnerability scanning](https://nvd.nist.gov/800-53/Rev4/control/RA-5) -- and we are -- we should be ok. 

I also updated the last checklist item there to specifically include a review of the SSP to make sure our control narratives are up-to-date.

**Comment by cryptofilegsa** [comment]
We should confirm that GitHub security covers everything that snyk does before removing.  I would assume that these tools complement one another given that github integrates both.

**Comment by cryptofilegsa** [comment]
Vytas Fidleris of snyk submits the following: 

"Snyk works across the entire SDLC (CLI -> production), not just in the git repo, as well as being able to support multiple Gits at once.  Even if you only plan on working on security within Github, Snyk provides license compliance support, deeper reporting and vulnerability prioritization and a more extensive vulnerability database (only 1/3 of the database is publicly available knowledge). The dependency tree that Snyk builds out is extensive and lists ALL transitive dependencies (where ~78% vulnerabilities lie), while providing automated remediation for the vulnerabilities. 
Github's security capabilities are great for individual developers, Snyk is built out more as a tool to be used by organizations."

**Comment by tbaxter-18f** [comment]
I'm moving this back into to-do.

**Comment by Jkrzy** [comment]
As an immediate step, I've removed the stalled Snyk checks from the `required` steps before merging into `master`

**Comment by Jkrzy** [comment]
Sticking with snyk per: https://github.com/18F/tts-tech-portfolio/issues/403
