### ISSUE TITLE
Error when pulling a report

### ISSUE THREAD

**Issue by saraheckert** [18F/tock#956]
<img width="251" alt="Screen Shot 2020-01-10 at 1 27 31 PM" src="https://user-images.githubusercontent.com/42154564/72184220-29b04c80-33ad-11ea-9871-094bfe48f173.png">
Trying to pull complete timecard data for FY19, and receiving an error

**Comment by saraheckert** [comment]
cc: @StephanieRivera

**Comment by tbaxter-18f** [comment]
Given that it was a network error, and I don't think we've seen it since, I'm going to close this. @saraheckert if you see it again, please re-open this or start another issue. Thanks!
