### ISSUE TITLE
Cloud.gov login error

### ISSUE THREAD

**Issue by jdamis4XD** [18F/tock#962]
I have attempted several times today to tock my time for the week today and every time the page loads I get cloud.gov login error.  Please see the attached screenshot below.
<img width="1425" alt="Screen Shot 2020-01-31 at 5 08 56 PM" src="https://user-images.githubusercontent.com/42155104/73577955-720ed780-444c-11ea-8034-3b564d3e7bad.png">

**Comment by Jkrzy** [comment]
Tock had accidentally been denied access to cloud.gov information for the account.

Resolved by going to https://login.fr.cloud.gov/profile, revoking access for the tock application and re-logging into Tock.

Will open a new issue to see if we can better catch and communicate this error state.
