### ISSUE TITLE
Convert business units to DB table

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#965]
Currently the business units are coded as choices in employees/models.py. We need to change to (and migrate the data to) a DB table. We'd like to support sub-disciplines and easier changes.

**Comment by cryptofilegsa** [comment]
Choices is now a hard-coded array, and so you want that to be contents in a table?

**Comment by tbaxter-18f** [comment]
Well, in django parlance, they're "choices", which is really just a tuple. But yes.

OTOH, though, sit tight. I found some time to pick this up.

**Comment by Jkrzy** [comment]
Apologies @cryptofilegsa, some crossed wires this morning. @tbaxter-18f is going to tackle this one.
