### ISSUE TITLE
Schedule tock timecard notes in advance

### ISSUE THREAD

**Issue by allisonnorman** [18F/tock#967]
From @saraheckert: As Chief of Projects, I want to be able to schedule tock timecard notes in advance so that I do not have to manually enable and disable them.

For federal holidays, Sarah manually adds a tock timecard note to remind the team to include the OOO when submitting their time. As OOO federal holidays are traditionally scheduled in advanced, we should support the ability to schedule these to enable and disable based on a date range, rather than relying on someone to manually do so, which is tedious and takes time.

Examples:
- An OOO timecard note could be scheduled to display the notification for President's Day for the period 2/16-2/22. (which will translate to "show between these dates" with a date range)
- This note, along with other ones for other federal holidays (Christmas, Thanksgiving, etc) could be set up in advance earlier in the year and will be enabled for the respective reporting period set up as tock timecard notes.

## We'll know we're done when
- [ ] Admins have the ability to schedule time card notes for all federal holidays in a calendar year so that the note shows during a given time range
- [ ] Admins no longer need to manually enable/disable time card notes that are pre-scheduled
- [ ] Ad hoc time card notes are still supported (for example, federal employees are given an unscheduled federal holiday, or a one-off message needs to be displayed).

**Comment by saraheckert** [comment]
Thank you, this captures the request.

**Comment by tbaxter-18f** [comment]
@Jkrzy I set this as "to-do" just based on @cryptofilegsa being already assigned, but if there are more pressing issues, I'm OK with "soon-ish" too
