### ISSUE TITLE
Filter reports by division (18F, COE, Login.gov, etc)

### ISSUE THREAD

**Issue by allisonnorman** [18F/tock#968]
From @saraheckert: As Chief of Projects, I want to view only users who have not submitted timecards **within my division** (e.g. 18F) so that I can follow up with them to tock. 

Steps to pull this information today:
- Select Reports by Weekly Reporting Period and select relevant week
- See Users who have not filed a timecard -> All divisions are present, including COE, Login, etc.
- Visually filter out team members from other divisions (this is the problem)

![Screen Shot 2020-02-11 at 3 10 48 PM](https://user-images.githubusercontent.com/6900926/74288327-fb41cc00-4ce0-11ea-957e-f8d6eb8f5c5f.png)

## We'll know we're done when
- [x] Users have the ability to view timecards by division (18F, COE, Login.gov) on the Weekly reporting period reports (https://tock.18f.gov/reports/)

**Comment by saraheckert** [comment]
This looks great, thank you
