### ISSUE TITLE
META ISSUE: Clean Up Line Item List

### ISSUE THREAD

**Issue by seanherron** [18F/tock#97]
This meta issue is designed to encapsulate all the desired changes to list line items in Tock. Right now, it's just a jumbled list in a dropdown of everything which isn't really working as we add new things all the time. Here's a summary of concerns and my initial thoughts:

**Retiring Projects**
https://github.com/18F/tock/issues/95
Add a flag to disable a project from being selected. This is tricker than I thought it originally would be - we need to implement some sort of temporal sense so that line items can be triggered on/off depending on the Reporting Period (and design behavior so that previous RP defaults are carried on to new RPs)

**Show Project Descriptions**
https://github.com/18F/tock/issues/59
Figure out a way to display project descriptions below line items, so people are sure they are reporting the right thing

**Remove Line Items from Timesheets**
https://github.com/18F/tock/issues/47
I think this is a non-issue now as you can just make it a blank item, but there may be a desire from others

**Sort by Internal/External or Billable Projects**
https://github.com/18F/tock/issues/40
Maybe use optgroups? This would kill the ability to type and get the item in the dropdown you want, I think.

**Autocomplete**
https://github.com/18F/tock/issues/23
I'm super skeptical of autocompletes, as they will make it difficult to find an item if you don't know the exact name of it (for instance, `hiring` vs `talent`). Anyone have ideas for improving this?

**Comment by gbinal** [comment]
I'm not sure if this is will dovetail with whichever of these you want to go with, but if there's not conflict with other improvements, can the list go from unordered to alphabetical?

**Comment by NoahKunin** [comment]
@seanherron I'd like to help on this, but I'm guessing I will need admin access to the web client to properly contextualize changes?

**Comment by seanherron** [comment]
@NoahKunin Actually I'm moving away from using the admin entirely - all of the sorting and logic takes place in the Django views and forms.

Pull request coming shortly for #23

**Comment by NoahKunin** [comment]
Got it, I'll hang tight.

**Comment by seanherron** [comment]
#23 is now live!

**Comment by NoahKunin** [comment]
All of the individual issues were close, so closing this one.
