### ISSUE TITLE
onboarding for cryptofilegsa

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#970]
- [x]  Generate a Tock API authorization token in the admin for the new developer.
- [x]  Grant access to New Relic.
- [x]  Grant access to the GitHub repository.
- [x]  Grant access to SpaceDeveloper roles on Cloud.gov for staging and prod spaces within the gsa-18f-tock org.
- [x]  Grant access to GSA_TE_TockLibrary and GSA_TE_UtilitiesLibrary scripts.
- [x]  Grant access to gsa-18f-tock org on Snyk.
- [x]  run through log auditing at: https://github.com/18F/tock/blob/master/docs/logging.md#tock-log-auditing

**Comment by tbaxter-18f** [comment]
@timothy-spencer I've done a chunk of the onboarding, can you pick it up from here, as well as explaining/handing-off the weekly report you're doing? 

Thanks!

**Comment by timothy-spencer** [comment]
Certainly!  Thanks for the ping!

**Comment by timothy-spencer** [comment]
Mat is on the road, so we will be doing the log audit stuff next week together.  @tbaxter-18f, I'm not sure what the dependencies.txt checklist item is, though...  Is it possible you meant requirements.txt?  Would that be just going over them and seeing if they could be updated or something?

**Comment by tbaxter-18f** [comment]
honestly, I'm not sure. I don't think I added that to the onboarding, or if I did I've forgotten why. I think a walkthough on requirements to understand what we're pulling in makes sense, though.

**Comment by Jkrzy** [comment]
Hmm, I'm not sure where that line item came from either -- it's not in the onboarding docs.

In anycase, let's punt it for now. We know we need an audit of those dependencies, https://github.com/18F/tock/issues/947

**Comment by cryptofilegsa** [comment]
Now have kibana process and will plan to do the log auditing on Friday onwards...
