### ISSUE TITLE
Do not use `Exclude` in forms

### ISSUE THREAD

**Issue by amymok** [18F/tock#973]
`Exclude` should be avoided in forms due to security concerns, here's one place where it is being used in the code:
https://github.com/18F/tock/blob/master/tock/hours/forms.py#L39

Here's the reference:
https://docs.djangoproject.com/en/3.0/topics/forms/modelforms/#selecting-the-fields-to-use

Here's also the comment where this is from:
https://github.com/18F/tock/pull/955#discussion_r365346882

**Comment by cryptofilegsa** [comment]
so this raises the question of why form validation was being avoided for 'time_spent', 'reporting_period', and 'user' variables.  is this lack of validation currently necessary for the TimeCard form to work?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
