### ISSUE TITLE
Tock ate my time

### ISSUE THREAD

**Issue by jtag** [18F/tock#98]
I entered my time yesterday, it flashed weirdly when i hit entered, showed blank again. I hoped it had recorded my time but based on DMs from team ops it didnt. Bug?

**Comment by seanherron** [comment]
Did your total percentage = 100? I've seen a intermittent strange bug where submitting an incomplete timecard accidentally deletes everything. I see a timecard created for you, but with no entries inside it.

**Comment by jtag** [comment]
I don't know? I thought I saw it added up to 100 and then everything
happened so fast after clicking enter.

ugh. maybe build in a review/confirm stage before submitting?
I'll recalculate/add my time again.

-I still love Tock btw. So glad we are building internal tools.

Jtag

On Tue, Apr 28, 2015 at 11:22 AM, Sean Herron <notifications@github.com>
wrote:

> Did your total percentage = 100? I've seen a intermittent strange bug
> where submitting an incomplete timecard accidentally deletes everything. I
> see a timecard created for you, but with no entries inside it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/issues/98#issuecomment-97161761>.
>



-- 

Jesse Taggert
Product Strategy, User Experience & Design Practices
18F Consulting Services | GSA
cell: 415-730-4965
18F.gsa.gov <http://18f.gsa.gov/>

**Comment by batemapf** [comment]
@jtag @seanherron can this be closed now that we have moved to hours?

**Comment by seanherron** [comment]
I found the bug! It was a problem with how we were taking inputs in to the model. I think it is fixed now - I can't replicate anymore. https://github.com/18F/tock/pull/118
