### ISSUE TITLE
Update test fixtures and/or create a better alternative for generating test/demo data.

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#986]
Our test data is getting stale and should be updated. Among deficiencies noted:

1. Does not account for billable target
2. Does not account for organization (or soon, business unit) models.

**Comment by tbaxter-18f** [comment]
@Jkrzy started this so we could start tracking this.


We may also need some new tests to go with the new data.

**Comment by amymok** [comment]
@tbaxter-18f I have a few questions here:

Are we talking about updating `data-update-deduped.json` file?

What would be some `organizations` that would be useful?  I am seeing the list of 18F Unit available right now, so what would be the difference between that and "organizations"?  Unless random ones are okay, I would like to use something that make sense for our case.

Can you also elaborate more on the billable target?  Are you talking about `billable_expectation` being set at 0.8?  Do you want to see some `employees` having a different number as well?

**Comment by tbaxter-18f** [comment]
> Are we talking about updating data-update-deduped.json file?
Yes, although there are some objects created in tests. I'm not sure yet if we need updates there or not. I suspect we may have some test gaps though, so it's likely.

>What would be some organizations that would be useful? 

Because we have organization objects, and we do things with them, but currently don't really test for them?

> I am seeing the list of 18F Unit available right now, so what would be the difference between that and "organizations"?

Unit is a business unit within an org. So, like Engineering Chapter is within 18F.

Some amount of organizations (and probably more units) will be added with the issue I'm working. I don't think that will necessarily mean we shouldn't add more, but I do mention it because it may change how we look at this one. I hope to get that one out for PR today (fingers crossed).

Also note that this issue is just a scratch pad for where we'd already noted gaps. There may very well be other gaps, these are just ones Joe and I had noted while chatting one day.

**Comment by amymok** [comment]
I have a few more questions before I can proceed:
- How was the data originally created?
- Are we trying to now link up employees with unit and organization?
- Carter already included Units and Organizations in this data, do we want more or this is the “official” list we want to work from?
- Do we want to fill in Org/Business Unit for everyone?
- Everyone is currently an 18F employee, if they are PIF/Solutions, we need to create some employees with those orgs and they are not 18F Employee
- What other data do we want to fill out?
- How do we want to fill out billable target/expectation?
- We are only focusing on data-update-deduped.json? There are other fixtures, do we need to worry about them? What are the usage difference between data-update-deduped.json and other fixtures?
- Anything else?

**Comment by Jkrzy** [comment]
Thanks @amymok, broad answers to your questions.

The history/use-cases for the current fixtures _should_ be discernible from the current state of the code and the commit history.  

I'd like to limit the scope of this issue on generating _new_ test data to approximate what we would expect to see in a production environment. To be used for populating staging and local environments. `data-update-deduped.json` attempts to fill that role now. The other fixtures are to support testing and can be updated if/when needed.

Let's start with just 18F at the moment and look to the current production data to determine a reasonable approximation.

We'll need at a minimum
- Active 18F Employees, their business units (already defined by Carter), their timecards
- ReportingPeriods
- Projects and accounting codes (At least one representing Out of Office (non-billable and excluded from billability)
- Submitted timecards for each employee with varying projects/hours reports

To the extent possible we should try to make this generation an automated process.

**Comment by tbaxter-18f** [comment]
Agreed on everything Joe said. For best testing, we'll one one org with at least one BU and person assigned to it, other than 18F. We don't need a lot of people rolling up to that org, but we should have one for testing per-org functionality.

As I look at it, it looks to me to be a mixture of auto-generated data, serialized DB data (possibly after being generated) and manually inserted data. If it were me, I would probably"
* take what we have now then go into the admin and make sure the data looks realistic. 
* Add data and relationships as needed to fill gaps and make things more up to date
* re-serialize DB
* update existing tests and add tests for new data

There are surely other good ways to do it, but that's what I'd do.

**Comment by Jkrzy** [comment]
Hi @amymok, as you roll off Tock development can you update here with your progress and push any WIP code so that we may hand off to another dev? Thanks!

**Comment by tbaxter-18f** [comment]
@amymok can you provide an update here so this can be picked up again? Thanks!

**Comment by amymok** [comment]
I added a draft PR on the work I started doing.  Description on what I did is there in #1040.

**Comment by Jkrzy** [comment]
I'll pick this one up!

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
