### ISSUE TITLE
Complete business impact analysis for Tock

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#990]
It's time to review and update our Business Impact Analysis (BIA) document.

We've gotten started on this but need to bring it to completion.

Reach out in #tock-dev for access to the template.

**We'll know we're done when**
- [x]  The document is complete and has been accepted by our ISSO

**Comment by cryptofilegsa** [comment]
Updated BIA with response from Matthew Spencer.

**Comment by cryptofilegsa** [comment]
Was confused at one point that there were separate DIA and BIA documents.  Have a draft BIA started.  Working with Sue on this.  Will report back when draft is complete and sent over to her for review.  ETA today for completion this week.

**Comment by Jkrzy** [comment]
BIA revisions look good to me, @tbaxter-18f  -- want to take a look-over for final 👍 ?

**Comment by tbaxter-18f** [comment]
Happy to. @cryptofilegsa will you kick me the link?

**Comment by cryptofilegsa** [comment]
done, see your inbox.
