### ISSUE TITLE
audit and tidy up javascript dependencies

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/tock#994]
review and confirm that these [dependencies](https://github.com/18F/tock/blob/master/package.json) are current:

 node dependencies
- [x] [chosen-js](https://harvesthq.github.io/chosen/) 1.8.7
- [x] [jquery](https://jquery.com/) 3.4.1
- [x] [jqueryui](https://jqueryui.com/) 1.12.1
- [x] [node-sass](https://github.com/sass/node-sass) 4.13.1
- [x] [uswds](https://designsystem.digital.gov/) 1.6.9 covered elsewhere in https://github.com/18F/tock/issues/867

devDependencies
- [x] [jest](https://jestjs.io/) 23.6.0
- [x] [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer) 3.9.1
- [x] [puppeteer](https://github.com/puppeteer/puppeteer) 1.19.0

**Comment by Jkrzy** [comment]
Hi @cryptofilegsa, just a heads-up -- there are javacript packages in use that are not represented in package.json. https://github.com/18F/tock/blob/master/docs/dependency-management.md#production

**Comment by cryptofilegsa** [comment]
OK, cool, I added jquieryui above, the only one in tock/static/vendor/ directory that wasn't already included in the package.json.  We might consider adding jqueryui to the package.json.

**Comment by cryptofilegsa** [comment]
seems noteworthy: https://github.blog/2020-03-16-npm-is-joining-github/

**Comment by cryptofilegsa** [comment]
Still need to check versioning but this jscript dependency set looks good.
